### ISSUE TITLE
Symfony paketleri versiyon problemi

### ISSUE THREAD

**Issue by enverarslan** [mewebstudio/pos#1]
Bu paketi Laravel 5.6 üzerinde kullanmak istediğimizde Symfony paketlerinin bağımlılığından dolayı yüklenemiyor.

laravel-pos paketi buna bağımlı ve bu paket de symfony/http-foundation paketinin 4.1 versiyonunu kullanıyor. Eğer symfony/http-foundation paketinin 4.1 versiyonunda spesifik bir kullanım yoksa daha fazla kullanım alanı için bağımlılığı eski versiyonlara güncellemeliyiz.

Laravel 5.6 projesinde yüklemeye çalıştığımda aldığım hata şu:

`
Problem 1
    - mews/laravel-pos 0.1.8 requires mews/pos ~0.1.8 -> satisfiable by mews/pos[0.1.8].
    - Installation request for mews/laravel-pos ^0.1.8 -> satisfiable by mews/laravel-pos[0.1.8].
    - Conclusion: remove symfony/http-foundation v4.0.8
    - Conclusion: don't install symfony/http-foundation v4.0.8
    - mews/pos 0.1.8 requires symfony/http-foundation ^4.1 -> satisfiable by symfony/http-foundation[4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.2].
    - Can only install one of: symfony/http-foundation[4.1.x-dev, v4.0.8].
    - Can only install one of: symfony/http-foundation[4.2.x-dev, v4.0.8].
    - Can only install one of: symfony/http-foundation[4.3.x-dev, v4.0.8].
    - Can only install one of: symfony/http-foundation[4.4.x-dev, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.0, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.0-BETA1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.0-BETA2, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.0-BETA3, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.10, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.11, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.12, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.2, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.3, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.4, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.5, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.6, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.7, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.8, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.1.9, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.0, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.0-BETA1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.0-BETA2, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.0-RC1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.10, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.2, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.3, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.4, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.5, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.6, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.7, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.8, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.2.9, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.3.0, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.3.0-BETA1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.3.0-BETA2, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.3.0-RC1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.3.1, v4.0.8].
    - Can only install one of: symfony/http-foundation[v4.3.2, v4.0.8].
    - Installation request for symfony/http-foundation (locked at v4.0.8) -> satisfiable by symfony/http-foundation[v4.0.8].

`

**Comment by mewebstudio** [comment]
@enverarslan geç cevap için özür dilerim. Sorunu çözdünüz mü? Güncel birkaç projemde sorunsuz kurulum gerçekleşti ve kullanıyorum.

**Comment by enverarslan** [comment]
paketi klonlayıp symfony/http-foundation paketini ve symfony/serializer paketini 4.0.8 versiyonuyla isteyerek çözdüm. bunun için packagiste de atmam gerekti. https://packagist.org/packages/enver/pos

eski versiyonlar için ayrı bir release çıkarabilirseniz silerim paketi bu daha doğru olur.

**Comment by mewebstudio** [comment]
Açıkçası paketi ilk etapta Laravel'den bağımsız şekilde, güncel paketlerle geliştirmiştim. Şimdi kontrol ettim, Laravel 5.7 ile geliştirdiğim projede kullanacağım için de ona uygun şekilde Laravel'e paketlemişim. Sorununuzu bu şekilde çözdüyseniz, sizin oluşturduğunuz paket kalsın, 5.6 projelerde kullanmak isteyenler olabilir. Bu durumda sizin repoya yönlendirmek daha mantıklı :)

**Comment by enverarslan** [comment]
genelde böyle durumlar için bağımlılıklara göre paketi farklı versiyonlarla sunuyorlar. açıkçası bir bütünlük sağlamak için paketinizde farklı versiyonlar oluşturursanız daha iyi olur. katkı yapacak insanlar tek paket üzerinde yoğunlaşabilirler böylece.

**Comment by mewebstudio** [comment]
İsterseniz şöyle yapalım; ben bir branch oluşturayım, siz buraya PR gönderin. Sonrasında bunu versiyonlayalım.

**Comment by mewebstudio** [comment]
Yoğunluktan dolayı geç bakabildim, kusura bakmayın. Yeni bir branch oluşturdum.
https://github.com/mewebstudio/pos/tree/master-old-pkg

Laravel paketi için de aynı şekilde bir branch oluşturdum.
https://github.com/mewebstudio/laravel-pos/tree/master-old-pkg

Gerekli ayarlamaları fırsat bulduğunuzda yapıp PR gönderirseniz, onların versiyonlamasını da yaparım.

Kolay gelsin.

**Comment by enverarslan** [comment]
#3

Sorun değil, Laravel paketinde bir değişiklik yok aslında, pos paketi düzelince o da çalışacaktır. Ona bir istek atmıyorum bu yüzden.

İyi çalışmalar.

**Comment by mewebstudio** [comment]
Merge ettim. Versiyonlama için bir öneriniz var mı?

**Comment by enverarslan** [comment]
Buradaki çözüm composer'a uygun şekilde versiyonlamak olmalı sanırım. Packagist'te iki farklı branch'ten install yapabiliyor muyuz bilmiyorum. Packagist semantik versiyonlamayla çalıştığı için (https://packagist.org/about#managing-package-versions) master-old-pkg branchini masterla birleştirip 0.1.9 etiketleyerek gönderebilirsiniz. güncel versiyonu da 0.2.0 olarak etiketleyerek sunabilirsiniz gibi geliyor.

**Comment by mewebstudio** [comment]
Söylediğiniz şekilde bu branch'ı master ile birleştirirsem, masterda da aynı versiyonlar geçerli olacak. Bu durumda farklı bir branch açmamızın da bir anlamı kalmıyor :)

**Comment by enverarslan** [comment]
https://github.com/mcamara/laravel-localization/ şunu inceleyebilirsiniz.

**Comment by mewebstudio** [comment]
Tekrar merhaba. 5.6 ve yeni versiyonlar için farklı build'ler oluşturdum.
Eski versiyonlar için:
https://github.com/mewebstudio/pos/releases/tag/0.2.0
Yeni versiyonlar için:
https://github.com/mewebstudio/pos/releases/tag/0.3.0

Bunlara göre Laravel paketini de güncelledim.
Eski versiyonlar için:
https://github.com/mewebstudio/laravel-pos/releases/tag/0.2.0
Yeni versiyonlar için:
https://github.com/mewebstudio/laravel-pos/releases/tag/0.3.0

Test edebilirseniz sevinirim.

**Comment by mewebstudio** [comment]
Konuyu kapatıyorum, problem olursa tekrar açarsınız.
