### ISSUE TITLE
Yapıkredi Bankası "Payment" Aşamasında XID Hatası

### ISSUE THREAD

**Issue by yorulmazsinan** [mewebstudio/pos#101]
Merhabalar, YKB posunu kullanırken şöyle bir hata alıyorum:

Error {#1613 ▼
  #message: "Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]])"
  #code: 0
  #file: "/home/eceo/public_html/app/Mews/src/Gateways/PosNet.php"
  #line: 196
  trace: {▼
    /home/eceo/public_html/app/Mews/src/Gateways/PosNet.php:196 {▼
      Mews\Pos\Gateways\PosNet->get3DFormData(): array …
      › \t$this->logger->log(LogLevel::ERROR, 'enrollment fail response', $data);
      › \tthrow new Exception($data['respText'], $data['respCode']);
      › }
      arguments: {▼
        $message: "Xid hatalı."
        $code: "E189"
      }
    }
  }
}

**Comment by nuryagdym** [comment]
Merhabalar, tahminim test edilen kart Yapikrediye ait degil veya o kartta 3D etkin degil.

Yine de bu hatayi duzgun vermesi icin kodu guncellerim

**Comment by yorulmazsinan** [comment]
Böyle bir durumda NON_SECURE olarak mı ödeme almamız gerekiyor? Kart Yapıkredi onda bir sorun yok. 3D etkin olmaması nasıl oluyor? Ödemelere açık kart, internet alışverişi yapılıyor.

**Comment by nuryagdym** [comment]
hmm, kartta degil sanirim, Account objesi olustururken  hangi modeli kullaniyorsunuz? MODEL_3D_SECURE mi?

"Xid hatalı." mesajdaki Xid siparis ID olmasi lazim. gonderdiginiz siparis ID'yi paylasabilir misiniz.

**Comment by yorulmazsinan** [comment]
`$order = [
						    'id'                    => uniqid(time()),
						    'amount'                => floatval($manuelposTotalPrice),
						    'currency'              => 'TRY',
						    'installment'           => intval($request->installment),
						    'success_url'           => route('control-panel.manuelpos.payment-status'),
						    'fail_url'              => route('control-panel.manuelpos.payment-status'),
						    'ip'                    => getIp(),
						    'email'                 => $request->customer_email,
						    'name'                  => $request->customer_name_surname,
						    'rand'                  => md5(uniqid(time())),
						    'lang'                  => AbstractGateway::LANG_TR,
						    'card_association'      => checkCardType(str_replace(' ', '', $request->card_number)),
				    ];`

Bu oluşturduğum $order değişkeni. $account ise şu şekilde:

`$virtualPos = [
					'bank'                          => $bank,
					'merchant_number'               => siteSettings($bank . '_' . 'merchant_number'),
					'posnet_id'                     => siteSettings($bank . '_' . 'posnet_id'),
					'username'                      => siteSettings($bank . '_' . 'api_user'),
					'password'                      => siteSettings($bank . '_' . 'password'),
					'use_3d_secure'                 => siteSettings($bank . '_' . 'use_3d_secure'),
					'enc_key'                       => siteSettings($bank . '_' . 'enc_key'),
					'terminal_number'               => siteSettings($bank . '_' . 'terminal_number'),
					'authorization_type'            => siteSettings($bank . '_' . 'authorization_type'),
					'minimum_instalment_amount'     => siteSettings($bank . '_' . 'minimum_instalment_amount'),
					'instalment'                    => siteSettings($bank . '_' . 'instalment'),
					'addinstalment'                 => siteSettings($bank . '_' . 'addinstalment'),
			];
			$account = AccountFactory::createPosNetAccount(
					$virtualPos['bank'],
					$virtualPos['merchant_number'],
					$virtualPos['username'],
					$virtualPos['password'],
					$virtualPos['terminal_number'],
					$virtualPos['posnet_id'],
					AbstractGateway::MODEL_3D_SECURE,
					$virtualPos['enc_key']
			);`

Bunlar direkt YKB için olan ayarlar.

**Comment by nuryagdym** [comment]
order id'yi su sekilde olusturup dener misiniz: `substr(uniqid(time()), 0, 20)`

cozmezse bu sekilde `substr(uniqid(time()), 0, 18)`

**Comment by yorulmazsinan** [comment]
> order id'yi su sekilde olusturup dener misiniz: `substr(uniqid(time()), 0, 20)`
> 
> cozmezse bu sekilde `substr(uniqid(time()), 0, 18)`

Bu sorunu çözdü, teşekkür ederim.
