### ISSUE TITLE
Posnet 3D Ödeme 148 Hatası

### ISSUE THREAD

**Issue by onurryildirimm** [mewebstudio/pos#103]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  |
| PHP versiyonu | 8.0 |
| Gateway ismi| Posnet |
| Banka ismi| YapıKredi |

### Hatanın özeti

Shared Hosting kullanıyorum. Ancak çıkış ip adreslerim vs hepsi bankada tanımlı. Başka bir posnet arayüzünde sorunsuz şekilde hostingimde çalışabiliyorum. Ancak Mews ile deneme yaptığımda #message: "148 MID,TID,IP HATALI:185.106.210.86" şeklinde hata almaktayım. 

$baseUrl = $bankTestsUrl.'/3d/';
//account bilgileri kendi account bilgilerinizle degistiriniz
$account = AccountFactory::createPosNetAccount(
    'yapikredi',
    '6706598320',
    '',
    '',
    '67322946',
    '27426',
    AbstractGateway::MODEL_3D_SECURE,
    '10,10,10,10,10,10,10,10'
);

Bu kısımda mid, tid, enc key gibi ögeler hangi kısımlara gelecek? Örnekten yorumlayarak yaptığımda dediğim gibi hata almaktayım. Boşluk olan kısımlar nedir ? Açıklama yazabilirseniz sevinirim.

* [x] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [x] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
Merhabalar, hala sorun devam ediyor mu?
Hata mesajinda yer alan IP'yi YKB tarafindan izin verdirtmeyi denediniz mi?

**Comment by onurryildirimm** [comment]
evet sorun devam ediyor. banka tarfında bu ip adresi tanımlı şimdi tekrar kontrol ettim.
![image](https://user-images.githubusercontent.com/119333026/209535402-ef8a3492-3f8e-474f-8a78-0e056d3738cc.png)

**Comment by nuryagdym** [comment]
account bilgileri su sekilde olmasi gerekiyor:

$account = AccountFactory::createPosNetAccount(
    'yapikredi',
    'musteri(merchant)_id',
    '',
    '',
    'terminal_id',
    'posnet_id',
    AbstractGateway::MODEL_3D_SECURE,
    'encryption key, ornekte verildigi gibi arasinda virguller olan bir deger olmasi gerekiyor',
);
Birde deneme yaparken dogru ortam kullanin, yani **test** bilgileri ise `$pos->setTestMode(true);`. production bilgiler ise `$pos->setTestMode(true);` bu satiri kaldirmanin gerekiyor. 
Bu ortam degerini hem ilk istekte, hem de bankadan donen degeri islerken (odemeyi tamamlarken) dogru ortam secilmesi gerekiyor.

bu sekilde account degerleri tanimlandiginda, hata devam ediyorsa bankayla iletisime gecip durumu sorar misiniz.

**Comment by onurryildirimm** [comment]
$pos->setTestMode(true); bu satırı kaldırınca sorun çözüldü hocam emeğinize sağlık teşekkür ederim.
