### ISSUE TITLE
Kuveyt Türk - TDS_SYSTEM_ERROR

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#104]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  |
| PHP versiyonu | 8.0 |
| Gateway ismi|  |
| Banka ismi| Kuveytürk |

### Hatanın özeti

Merhabalar, bazı kartlarda ödeme sonucunda ödemeyi almayıp tds_system_error hatası veriyor

**Comment by t-uzun** [comment]
Aynı sorunu bende alıyorum. Çözüm bulabildiniz mi?

**Comment by nuryagdym** [comment]
Merhabalar, en son @mettleshade bankayla bu konuyu gorusecekti,  ben kodda bir sorun bulamadim, bankayla sorun tespit edilmesi gerekiyor. Ona gore kodu guncelleyebilirim

**Comment by mehmetpacal** [comment]
Bankayla görüştüm fakat bir sorun olmadığını, api sahibi kartında bu hatayı vereceğini dediler ama benim müşterilerimde alıyor bu sorunu dedim ve örnek liste attım ve dönüş şu şekilde oldu;

Hata BKM tarafından sistem sorunu ve kart doğrulaması esnasında kart bilgilerinin doğrulanamamasından dolayı oluşmaktadır.

**Comment by mettleshade** [comment]
Sorunu çok saçma bir şekilde çözdüm test ettim o hatayı almıyorum,

Ödeme isteği oluşturduğum sayfada

`try {
                            $formData = $pos->get3DFormData();
                        } catch (\Throwable $e) {
                            print_r($e);
                        }`

altına 

`<div style="display: none">
                            <?=  print_r($pos); ?>
                        </div>`

ekledim düzeldi.

**Comment by nuryagdym** [comment]
Sorun tespit edildi, bug hata icinde cozum yayina alinacak

**Comment by nuryagdym** [comment]
@mehmetpacal musait oldugunda v0.10.3 versiyonu indirip kontrol eder misin.
