### ISSUE TITLE
YKB - 3d secure odemeyi tamamlayamiyor

### ISSUE THREAD

**Issue by nuryagdym** [mewebstudio/pos#106]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  0.10.2 |
| Gateway ismi|  Posnet |

### Hatanın özeti
YKB 3D secure odeme siparis taksit sayisi **1** verildiginde tamamlanamiyor.
`PosNet::check3DHash()` kontrolu gecemiyor, cunku bankadan donen taksit degeri **0**,
` $this->order->installment` ise 1

Reporter: @semihyilmaz
related issue: #93, #22

**Comment by onurryildirimm** [comment]
aşağıdaki şekilde taksitlendirme tanımlandığında sistem sorunsuz çalışıyor. Başka bir posnet modülünde de aynı hata ile karşılaşmıştım ykb tarafı installment değerini 1 olarak kabul etmiyor. 

$installments = [
    0  => 'Peşin(Tek Çekim)',
    2  => '2 Taksit',
    3  => '3 Taksit',
    4  => '4 Taksit',
    5  => '5 Taksit',
    6  => '6 Taksit',
    7  => '7 Taksit',
    8  => '8 Taksit',
    9  => '9 Taksit',
];

**Comment by nuryagdym** [comment]
aynen, butun gatewaylar icin kutuphane normalde Taksi 1 verildiginde dogru degere (0 veya bos string) donusturur. YKB icin de bunu yapiyordu ama 0.7.0 versiyonda yaptigim guncellemede silmisim o donusturmeyi. 
Yeni versiyonla yine Taksit 1 verilsede calisacak

**Comment by semihyilmaz** [comment]
@nuryagdym çok teşekkür ederim. Yoğunluktan yeni kontrol edebildim. Elinize sağlık. Sorunsuz çalışıyor.
