### ISSUE TITLE
YKB Session Sorunu Hakkında

### ISSUE THREAD

**Issue by onurryildirimm** [mewebstudio/pos#107]
Merhaba,

YKB ile 3d şifre gönderildikten sonra response sayfası "sipariş bulunamadı session sıfırlandı" tarzı bir hata dönüyor. Açıklama kısmında yazan şekilde bir kaç deneme yaptım ama sorunu çözemedim. örneğin Example dosyalarında nerelerde ne tarz bir değişiklik yapmamız gerek bu sorunu geçmek için ?

**Comment by nuryagdym** [comment]
Merhabalar,
hangi PHP versiyon kullaniyorsunuz?

**Comment by onurryildirimm** [comment]
PHP 8.1 versiyonunu kullanmaktayım

**Comment by nuryagdym** [comment]
session extension enabled mi? emin degilseniz bu kodu calistirmayi dener misiniz:
```
if (!extension_loaded('session')) {
    die('You must enable PHP session support for the system to work.');
}
```
bazi shared hostinglerde default olarak session extension disabled geliyor

**Comment by onurryildirimm** [comment]
çalıştırdığımda herhangi bir hata dönmüyor. cpanel den kontrol ettiğimde session aktif gözüküyor
![image](https://user-images.githubusercontent.com/119333026/210077321-68518352-192b-4a78-8463-7cb9919809e0.png)

**Comment by nuryagdym** [comment]
burda https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict/51128675#51128675 anlatildigi gibi samesite=None denediniz mi? Denerken taraycida gizli modda denenmesi iyi olur, yoksa taraycida var olan cookielerin samesite degerini guncellemeyebilir.

Redis kullandigimda bu sorunu yasamamistim, ama PHP session'da sorun cikiyor ara sira.
Ben de session konusunda uzman olmadigim icin cokta bir yardimci olamiyorum.

**Comment by erenilhan** [comment]
"sipariş bulunamadı session sıfırlandı"
bu mesaj ykb tarafından mı dönüyor?  @onurryildirimm

**Comment by onurryildirimm** [comment]
template/_payment_response.php dosyasında

requestten sonrasına ;

if(isset($_COOKIE["PHPSESSID"])){
    header('Set-Cookie: PHPSESSID='.$_COOKIE["PHPSESSID"].'; SameSite=None');
}

kod bloğunu ekledim. şimdi hata dönüşü olmadı. Deneme yapmaya devam edeceğim hata ile karşılaşırsam bilgi vereyim tekrar.

**Comment by onurryildirimm** [comment]
> 

hayır _payment_response.php dosyasındaki hata bu 

if (!$order) {
    throw new Exception('Sipariş bulunamadı, session sıfırlanmış olabilir.');
}

order değerini boş algılıyor session yok gibi ondan dolayı bu hatayı döndürüyor.

**Comment by nuryagdym** [comment]
SameSite=None sorunu giderdi mi?

**Comment by onurryildirimm** [comment]
> SameSite=None sorunu giderdi mi?

Şu an sorun yok gibi gözüküyor, dediğim sayfaya bu kodu ekleyince response sayfası düzgün şekilde çalıştı. Çekim işlemi yaptım sorunla karşılaşmadım.

**Comment by nuryagdym** [comment]
dokumantasyona bakmakta fayda var :) https://github.com/mewebstudio/pos#session-s%C4%B1f%C4%B1rlanmas%C4%B1

**Comment by nuryagdym** [comment]
Not olarak yaziyorum, yukarda belirtilen stackoverflow kaynakta da belirtildigi gibi `SameSite=None`, `Secure` flag olmadan calismaz (yada calismayabilir).
yani @onurryildirimm paylastigi kod 
```php
header('Set-Cookie: PHPSESSID='.$_COOKIE["PHPSESSID"].'; SameSite=None');
```
yerine su sekilde kullanmaniz gerekebilir.
```php
header('Set-Cookie: PHPSESSID='.$_COOKIE["PHPSESSID"].'; SameSite=None; Secure');
```

Benim durumda `Secure` flag olmadan denedigimde session cookie, SameSite=None dememe ragmen, screenshot'ta goruldugu gibi SameSite deger bos olarak gozukuyor:
![image](https://user-images.githubusercontent.com/26792980/210325149-9a49ac6a-7055-458e-9a9d-792669925643.png)

`Secure` flag'le beraner kullanildiginda ise su sekilde gozukecek ve duzgun calisan sekli:
![image](https://user-images.githubusercontent.com/26792980/210325274-76c319b8-8dff-4bf7-b47f-0788cfda72e0.png)


Kod orneklerde symfony session component kullanilmaktadir, orda da dogru ayar su sekilde:
```php
$sessionHandler = new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage([
    'cookie_samesite' => 'None',
    'cookie_secure' => true,
]);
```

**Comment by canerd7u** [comment]
@nuryagdym bunu projede nereye nasıl ekleyeceğiz ?
