### ISSUE TITLE
GarantiPos 'da Tutarlar x 100 dönüyor.

### ISSUE THREAD

**Issue by semihyilmaz** [mewebstudio/pos#110]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  0.10.4|
| PHP versiyonu | 8.1 |
| Gateway ismi| Garanti |
| Banka ismi| Garanti |

### Hatanın özeti

_(yaşadığınız sorunun detayları)_

### Bağımsız kod veya hatayı yeniden oluşturmanın bir yolu

GarantiPos.php Line 400

 'amount'               => $raw3DAuthResponseData['txnamount']/100
ile sorunu düzelttim.

### Beklenen Sonuç

Tutar / 100 geri gelmeli.

### Gerçek sonuç

Tutar x 100 olarak dönüyor. 1 Tl için 100 TL

## Göndermeden önce kontroller

* [x] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [x] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
son 1 aydir bu bank response'lari ele alan kismi tekrardan yaziyorum. Hala bitmedi. 
Banka response'e maplerken gereken donusumler yapilmiyor, hatada belirtildigi gibi amount'un 100 bolunmesi. Zamanla duzeltilecek.

Ancak benim bilmek istedigim response'da hangi degerleri gormek istiyorsunuz? @semihyilmaz @onurryildirimm @erenilhan @mettleshade @yorulmazsinan @necoakdogan @lansas @fabyo0 @zeydduran @mhunesi


Yani burda belirtilenlerin hangileri sizin icin onemli?
https://github.com/mewebstudio/pos/blob/3b9d63280723ee60166de2bed4a7649519d36aef/src/Gateways/GarantiPos.php#L380

Response mapping kodlari guncellerken, sadece su asagida listelenen degerleri birakip, geri kalanlari kaldirmayi dusunuyorum. 
```
order_id
auth_code
trans_id
md_status
proc_return_code
host_ref_num
status
status_detail
masked_number
amount
currency
error_code
error_message
md_error_message
all
3d_all
 ````

**Comment by onurryildirimm** [comment]
order_id
auth_code
trans_id
status
amount
error_code
error_message

Ben şu anda böyle kullanıyorum, response sayfasında işime lazım olmayanları çıkardım. order_id özellikle çekme sebebim bankanın sanalpos yönetim sayfasında karşılaştırma yapabiliyorum. error_message zaten şart, hata olduğu zaman hatanın sebebini müşteriye söyleyebilmek için gerekli.

**Comment by semihyilmaz** [comment]
Merhaba,
order_id
auth_code
trans_id
md_status
proc_return_code
host_ref_num
status
status_detail
masked_number
amount
currency
error_code
error_message
md_error_message
all
3d_all

buradaki tüm alanları kullanıyorum. Erp’ye aktarırken buradan ve all ve 3d_all daki verileri kullanıyorum. Şuan mapping gayet iyi.
Teşekkürler.
İyi çalışmalar.

> nuryagdym ***@***.***> şunları yazdı (3 Oca 2023 12:14):
> 
> order_id
> auth_code
> trans_id
> md_status
> proc_return_code
> host_ref_num
> status
> status_detail
> masked_number
> amount
> currency
> error_code
> error_message
> md_error_message
> all
> 3d_all

**Comment by erenilhan** [comment]
merhaba,

order_id,
trans_id,
host_ref_num,
status,
auth_code,
error_code,
error_message

ben de bunları kullanıyorum.

Çok teşekkürler.

**Comment by mettleshade** [comment]
Bende yaklaşık hepsini kullanıyorum.
