### ISSUE TITLE
Vakıfbank VPOS 7/24 - Merchant cannot be found for this bank

### ISSUE THREAD

**Issue by SahinOzden** [mewebstudio/pos#115]
Vakıfbankta test dahil productionda aşağıdaki hatayı alıyorum sürekli. 

^ Exception {#69 ▼
  #message: "Merchant cannot be found for this bank"
  #code: 2005
  #file: "C:\xampp\htdocs\sp\src\Gateways\VakifBankPos.php"
  #line: 131
  trace: {▼
    C:\xampp\htdocs\sp\src\Gateways\VakifBankPos.php:131 {▼
      Mews\Pos\Gateways\VakifBankPos->get3DFormData(): array …
      ›     $this->logger->log(LogLevel::ERROR, 'enrollment fail response', $data);
      ›     throw new Exception($data['ErrorMessage'], $data['MessageErrorCode']);
      › }
    }
    C:\xampp\htdocs\sp\examples\_common-codes\3d\form.php:34 {▼
      require …
      › try {
      ›     $formData = $pos->get3DFormData();
      ›     //dd($formData);
    }
    C:\xampp\htdocs\sp\examples\vakifbank\3d\form.php:3 {▼
      › 
      › require '../../_common-codes/3d/form.php';
      › 
      arguments: {▼
        "C:\xampp\htdocs\sp\examples\_common-codes\3d\form.php"
      }
    }
  }
}

**Comment by nuryagdym** [comment]
Merhabalar, Vakifbank icin
1. Banka tarafindan IP address izni verilmesi gerekiyor. Shared hosting ise Cpanel'den gorunenden ayri bir IP address daha oluyor, o IP'ye de izin verilmesi gerekiyor.
2. localhost'tan gonderilen istek calismayabilir, canli ortamda, yani sunucudan istek gonderilmesi gerekebilir.
3. Dogru ortam kullandiginizdan emin olun. 
       - production bilgileri kullaniyorsaniz`$pos->setTestMode(false);`
       - test bilgileri kullaniyorsaniz`$pos->setTestMode(true);`

Bu cozumler sorununuzu gidermiyorsa, bankayla da iletisime gecmeyi deneyin.

**Comment by SahinOzden** [comment]
testmode da "üye iş yeri aktif değil" gibi bir hata alıyorum. test bilgilerini de hiç bir yerde bulamıyorum malesef. Productionda da muhtemelen sizin dediğiniz gibi request ip izniyle ilgili bir problem var. Banka bize sanal pos verirken bunlardan bahsetmedi bir ip istemedi halbuki. En azından sandboxda çalıştrıbileceğim bir örnek arıyorum günlerdir ama muhtemelen sandbox bilgilerini de banka veriyor. Banka da hiç bir şekilde telefonlara bakmıyor destek ekibi yok. Kısır döngü ve pişmanlık yani. 

Elinize emeğinize sağlık daha önce payten entegrasyonları yapmıştım, onları da bu kütüphanede denedim çalışıyor. Çok iyi bir kütüphane oluşturmuşsunuz tebrik ederim.

**Comment by nuryagdym** [comment]
Yapikredi ve Vakifbank sanal ortamda calismiyor, IP izinler verilmesi gerekiyor, en azindan bildigim oyle, aksi bir durum varsa bilmek isterim :).
Bankaya genelde entegrasyon icin verdikleri eposta uzerinden haberlesmekte fayda var. Ben hep o sekilde iletisim kurdum.

Composer ile https://github.com/mewebstudio/laravel-pos bu kutuphaneyi indirmis olabilir misiniz?

Yine de zamanim oldugunda composer ile denerim indirmeyi

**Comment by SahinOzden** [comment]
hayır laravel değil. zaten projem laravel değil. laravel reponuzu sonradan gördüm. Bu reponun readme.md sinde belirttiğiniz composerdan kurulum yaptım sorunluydu. 

Bankanın bugün verdiği iletişim numarasını aradık ama cevap yok. hat kapatılmış. Mantık olarak bir sandbox ortamı kurmaları lazım ve biz bunu test edebilmeliyiz. Kendi verdikleri dökümandaki örnek php kodları zaten bir çok syntax hatalarıyla dolu. hepsini düzeltim denediğimde "string(247) "The requested URL was rejected. Please consult with your administrator." şeklinde hata aldım. bu da dediğiniz ip iznine çıkıyor. bize email de verilmedi aslında ama emailini bulup denemeye devam edeceğim. Kurulumu halledebilirsem ilk iş size haber vermek yerine bir kurban kesip ardından size de yazarım :) teşekkürler

**Comment by nuryagdym** [comment]
hmm, bugun composer ile cekmeye calistim, son versiyonu indirdi:
```
$ composer require php-http/curl-client nyholm/psr7 mews/pos
Using version ^2.2 for php-http/curl-client
Using version ^1.5 for nyholm/psr7
Using version ^0.11.0 for mews/pos
./composer.json has been updated
Running composer update php-http/curl-client nyholm/psr7 mews/pos
Loading composer repositories with package information
Updating dependencies
Lock file operations: 19 installs, 0 updates, 0 removals
  - Locking clue/stream-filter (v1.6.0)
  - Locking mews/pos (0.11.0)
  - Locking nyholm/psr7 (1.5.1)
  - Locking php-http/curl-client (2.2.1)
  - Locking php-http/discovery (1.15.2)
  - Locking php-http/httplug (2.3.0)
  - Locking php-http/message (1.13.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking php-http/promise (1.1.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (3.0.0)
  - Locking symfony/deprecation-contracts (v3.0.2)
  - Locking symfony/http-foundation (v6.0.20)
  - Locking symfony/options-resolver (v6.0.19)
  - Locking symfony/polyfill-ctype (v1.27.0)
  - Locking symfony/polyfill-mbstring (v1.27.0)
  - Locking symfony/serializer (v6.0.19)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 19 installs, 0 updates, 0 removals
  - Downloading php-http/discovery (1.15.2)
  - Downloading symfony/polyfill-ctype (v1.27.0)
  - Downloading symfony/serializer (v6.0.19)
  - Downloading symfony/polyfill-mbstring (v1.27.0)
  - Downloading symfony/deprecation-contracts (v3.0.2)
  - Downloading symfony/http-foundation (v6.0.20)
  - Downloading psr/log (3.0.0)
  - Downloading symfony/options-resolver (v6.0.19)
  - Downloading psr/http-message (1.0.1)
  - Downloading psr/http-factory (1.0.1)
  - Downloading psr/http-client (1.0.1)
  - Downloading php-http/message-factory (v1.0.2)
  - Downloading clue/stream-filter (v1.6.0)
  - Downloading php-http/message (1.13.0)
  - Downloading php-http/promise (1.1.0)
  - Downloading php-http/httplug (2.3.0)
  - Downloading php-http/curl-client (2.2.1)
  - Downloading mews/pos (0.11.0)
  - Downloading nyholm/psr7 (1.5.1)
php-http/discovery contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "php-http/discovery" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] yes
y - add package to allow-plugins in composer.json and let it run immediately
n - add package (as disallowed) to allow-plugins in composer.json to suppress further prompts
d - discard this, do not change composer.json and do not allow the plugin to run
? - print help
Do you trust "php-http/discovery" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
  - Installing php-http/discovery (1.15.2): Extracting archive
  - Installing symfony/polyfill-ctype (v1.27.0): Extracting archive
  - Installing symfony/serializer (v6.0.19): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.0.2): Extracting archive
  - Installing symfony/http-foundation (v6.0.20): Extracting archive
  - Installing psr/log (3.0.0): Extracting archive
  - Installing symfony/options-resolver (v6.0.19): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing clue/stream-filter (v1.6.0): Extracting archive
  - Installing php-http/message (1.13.0): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing php-http/httplug (2.3.0): Extracting archive
  - Installing php-http/curl-client (2.2.1): Extracting archive
  - Installing mews/pos (0.11.0): Extracting archive
  - Installing nyholm/psr7 (1.5.1): Extracting archive
 17/18 [==========================>-]  94%
    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
11 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
8 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
  - Locking psr/container (2.0.2)
  - Locking symfony/http-client (v6.0.20)
  - Locking symfony/http-client-contracts (v3.0.2)
  - Locking symfony/service-contracts (v3.0.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Downloading psr/container (2.0.2)
  - Downloading symfony/service-contracts (v3.0.2)
  - Downloading symfony/http-client-contracts (v3.0.2)
  - Downloading symfony/http-client (v6.0.20)
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.0.2): Extracting archive
  - Installing symfony/http-client-contracts (v3.0.2): Extracting archive
  - Installing symfony/http-client (v6.0.20): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
11 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
```

**Comment by SahinOzden** [comment]
bankayla yazıştım test kart bilgileri ve test işyeri bilgileri değişmiş sanırım onları uygulayınca çalıştı. 

examples/vakifbank/_payment_config.php de test kart bilgilerini aşağıdaki şekilde 
```
$testCards = [
    'visa1' => [
        'number' => '4938460158754205',
        'year' => '24',
        'month' => '11',
        'cvv' => '715',
        'name' => 'John Doe',
        'type' => AbstractCreditCard::CARD_TYPE_VISA,
    ],
```
    
    
 examples/vakifbank/3d/_config.php de işyeri test bilgileri aşağıdaki gibi
 
```
$merchantId = '000100000013506';
$terminalId = 'VP000579';
$isyeriSifre = '123456';
```

Benim asıl yapmak istediğim diğer bankalardaki 3DPayHost yöntemini burda kullanmak. Yani kullanıcı kart bilgilerini bankanın güvenli ödeme sayfasında girsin istiyorum. Israrla bunun dökümanını göndermiyorlar her seferinde 3d pay i gönderiyorlar...

**Comment by nuryagdym** [comment]
Tesekkurler, ben deneyince bu ekran cikti: 
![image](https://user-images.githubusercontent.com/26792980/222926480-7a7d5af2-a0a7-460d-8674-6712ab783004.png)
**DEVTAGON** sizin is yeri ismi ise, demek size ozel verilen bilgiler bunlar, durum bu ise is yeri bilgileri benim icin ise yaramaz.

Ama 3DPay dokumani varsa paylasirsaniz iyi olur, onu da eklerim zaman buldukca.

3DPayHost durumunda ise, benim hatirladigim bankalarda 3D, 3DPay ve 3DPayHost icin gonderilmesi gereken data ayni, sadece 3D host icin banka kredi kart bilgileri gondermiyorsunuz ve account modeli `\Mews\Pos\Gateways\AbstractGateway::MODEL_3D_HOST` olmasi gerekiyor. Vakifbanka kredi kart bilgileri gondermeden denedim su an calismadi, "Sistem hatası oluştu." hatayi aldim. Yani dokumantasyon lazim olacak.

**Comment by SahinOzden** [comment]
Localde denedim. Ecampledaki vakıfbank çalışmıyordu bu yeni test bilgilerini girince bu ekran öyle geldi. İndirdiğim halinde localde çalışmıyor bende. Bu arada 3d hostu vakıfbank için tanımlamamışsınız. Kodlarda göremedim. Diğer bankalarda var ama vakıfbankta yok.

**Comment by nuryagdym** [comment]
aynen 3dPay ve 3dHOst dokumanlari paylasirsaniz eklerim, elimde dokuman olmadigi icin sadece 3D eklendi

**Comment by SahinOzden** [comment]
https://www.vakifbankpos.com.tr/assets/files/GUVENL%C4%B0%20ORTAK%20%C3%96DEME%20ENTEGRASYON%20DOKUMANLARI.zip burda paylaşılmış

**Comment by nuryagdym** [comment]
Bu API, farkliymis. kutuphaneye eklemeye basladim bu API'yi. 3DHost islemini de denedim calisiyor, 3DPay farkli olarak kart bilgileri gondermeyince otomatik 3DHost methoda geciyor, ama tamamlayabilmem icin 3D odeme dokumani lazim bana.

**Comment by SahinOzden** [comment]
https://www.vakifbankpos.com.tr/SanalPosKilavuzlari bunlar işgörür mü?

**Comment by nuryagdym** [comment]
burdaki dokumanlarda 3D odeme icin sadece eski (kutuphanenin destekledigi) API bilgileri var. Yeni (ORTAK ÖDEME)'nin 3D dokumanini bulamadim.

Ayrice bana ozelden yazar misiniz, 3D Pay ve 3D host destegi ekledim, test icin destek lazim.
ce.nuryagdy@gmail.com

**Comment by SahinOzden** [comment]
Doğru bana da bunun eski olduğunu söyleyip başka bir link yollamışlardı. Yarın ofise geçince yazarım size.

**Comment by nuryagdym** [comment]
Hangisi eski oluyor? Ortak Odeme olan mi eski?

https://github.com/mewebstudio/pos/tree/rector-integration bu branch'te Ortak Odeme API icin 3DPay ve 3DHost ekledim. 
`/examples/vakifbank-cp/` altinda ornek kodlari ekledim.
Bir de config.php'ye bu configleri ekledim:
```php
        'vakifbank-cp' => [
            'name'  => 'VakifBank-POS-Common-Payment',
            'class' => Mews\Pos\Gateways\VakifBankCPPos::class,
            'urls'  => [
                'production'    => 'https://cpweb.vakifbank.com.tr/CommonPayment/api/RegisterTransaction',
                'test'          => 'https://cptest.vakifbank.com.tr/CommonPayment/api/RegisterTransaction',
                'gateway'       => [
                    'production'    => 'https://cpweb.vakifbank.com.tr/CommonPayment/SecurePayment',
                    'test'          => 'https://cptest.vakifbank.com.tr/CommonPayment/SecurePayment',
                ],
                'query'       => [
                    'production'    => 'https://cpweb.vakifbank.com.tr/CommonPayment/api/VposTransaction',
                    'test'          => 'https://cptest.vakifbank.com.tr/CommonPayment/api/VposTransaction',
                ],
            ],
        ],
```

**Comment by nuryagdym** [comment]
PR #114 'de bu issue ile alakali sorunlar giderildi. 
composer sorunu ise anladigim bazi `.md` dosyalarin ismi turkce karakter icermesinden olmus.
`.md` dosyalarin isimlerinden turkce karakterler kaldirildi, simdi sorun olmamasi gerekiyor.
