### ISSUE TITLE
Garanti test gateway url problemi

### ISSUE THREAD

**Issue by FikretCin** [mewebstudio/pos#121]
| Kütüphane versiyonu |  | 0.12.0
| PHP versiyonu |  | 7.4
| Gateway ismi|  | GarantiPos
| Banka ismi|  | Garanti 

### Hatanın özeti

Merhabalar, master branch üzerinde example çalıştırdığımda doğru gelen garanti test urli, 0.12.0 da hatalı geliyor. Çalışmayan bir sayfaya yönlendiriyor. config/pos.php yi fixleyip tag çıkmanız mümkün mü ? Bu şekilde testler patlıyor.

Şimdiden teşekkürler.

![Screenshot_4](https://user-images.githubusercontent.com/98125934/235124951-1ebcdaac-7b1b-4d51-afaf-5aabdb8c7f62.png)

**Comment by nuryagdym** [comment]
Merhabalar,
0.12.1 release olusturdum.
