### ISSUE TITLE
Kuveytürk İade ve İptal

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#122]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  |
| Gateway ismi|  |
| Banka ismi| Kuveyttürk  |

## Sorunuz

Ödemeyi iade ve iptal etmek için kuveyttürk kütüphanesinde gerekli alanlar ekli değil, eklemek için birkaç alanı diğer bankalardan aldım fakat kuveyttürk için gönderilmesi gereken data verilerini nerden bulabilirim

**Comment by nuryagdym** [comment]
Merhabalar, Kuveytturk bankanin entegrasyon destegine sorman gerekiyor.
Onlar ya dokuman ya da ornek kod paylasirlar. Ona gore implement edilmesi gerekiyor.
Bu bilgiler elimde olmadigi icin ekleyemedim. Bu bilgileri eline gecerse, paylasirsan eklerim kutuphaneye.

**Comment by FikretCin** [comment]
Daha önce KuveytTürk entegrasyon ekibine bir müşterimiz aracılığı ile talepte bulunmuştuk. Regular, cancel, refund için apilerinde uç noktanın mevcut olmadığını iletmişlerdi. Güncelleme olduysa bizi de bilgilendirirseniz seviniriz @mettleshade.

**Comment by mettleshade** [comment]
Bankadan dönüş aldım api dökümanını ilettiler, inceledim iade, kısmi iade, iptal mevcut. Pdf @nuryagdym iletilmiştir.

Bilginize @FikretCin

**Comment by mettleshade** [comment]
Bankadan dönüş aldım api dökümanını ilettiler, inceledim iade, kısmi iade, iptal mevcut. Pdf @nuryagdym iletilmiştir.

Bilginize @FikretCin

**Comment by sekizlipenguen** [comment]
Selamlar,

Bununla ilgili bir geliştirme var mı? Bitirdiniz mi?

**Comment by sekizlipenguen** [comment]
Selam, ben canlı bilgiler geldiğinde bu alanı da deneyeceğim. teb tarafı da çalıştı yukarıya yazdım. kuveytturk için bilgi bekliyorum ancak bunun için sana mail atıyorum test ve pdf dokümanları elimde mevcut.
