### ISSUE TITLE
VakifBankPos 'Invalid installment' hatası

### ISSUE THREAD

**Issue by FikretCin** [mewebstudio/pos#123]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 0.12.1 |
| PHP versiyonu | 7.4 |
| Gateway ismi| VakifBankPos|
| Banka ismi| Vakıfbank |

Merhabalar;

### Hatanın özeti

Paket içerisindeki ödeme geçitlerinin verileri eşleyen sınıflarında  ({Gateway}RequestDataMapper), siparişe atanan taksit sayısını düzenleyen mapInstallment metodu taksit sayısı 1 olarak gönderildiğinde gayet düzgün çalışmakta. Fakat VakifBankPosRequestDataMapper ın içerisindeki mapInstallment'a 1 gönderildiğinde bankadan geçersiz taksit (Invalid installment
) hatası alınmakta. Regular ile test edildiğinde bu işlem problem çıkarmıyorken 3d işleminde sorun yaratıyor. 

Sorunu çözmek için belirttiğim dosyadanın belirtilen satırındaki operatörü >= ile değiştirdiğimde problem çözüldü.
 
https://github.com/mewebstudio/pos/blob/master/src/DataMapper/VakifBankPosRequestDataMapper.php#L275

`return $installment > 1 ? (string) $installment : '0';` 
`return $installment >= 1 ? (string) $installment : '0';` 

Çözüm yöntemim doğru ise paketi günceller misiniz ? Eğer kullanım yöntemimde bir sorun var ise örneğin peşin fiyat için 1 değil de 0 gönderdiğimde tüm ödeme geçitleri sorunsuz çalışacak ise projemi revize edeceğim.

**Comment by FikretCin** [comment]
Bilgilendirme ve güncelleme için teşekkürler.

**Comment by nuryagdym** [comment]
sorunu kapatiyorum,
cozum olarak taksit miktari ya 0, ya da >= 2 deger verilince sorun olmuyor.
