### ISSUE TITLE
TX_STATUS ile TX_HISTORY arasındaki fark

### ISSUE THREAD

**Issue by sekizlipenguen** [mewebstudio/pos#127]
Selamlar,

TX_STATUS ile TX_HISTORY arasında tam olarak ne gibi bir fark var? çekimi yaptığımda durumunu kontrol ettirdiğimde başarılı gösteriyor ve çekimi iptal ettikten sonrada her ikisini de sorguluyorum halen başarılı oluyor.

"trans_id" => "gizlendi dolu geliyor"
    "error_message" => "Record(s) found for 1"
    "ref_ret_num" => "gizlendi dolu geliyor"
    "order_status" => array:9 [
      "ORD_ID" => "1"
      "CHARGE_TYPE_CD" => "S"
      "ORIG_TRANS_AMT" => "10"
      "CAPTURE_AMT" => "10"
      "TRANS_STAT" => "V"
      "AUTH_DTTM" => "2023-05-18 11"
      "CAPTURE_DTTM" => "2023-05-18 11"
      "AUTH_CODE" => "gizlendi dolu geliyor"
      "TRANS_ID" => "gizlendi dolu geliyor"
    ]
    "transaction_type" => null
    "masked_number" => "gizlendi dolu geliyor"
    "num_code" => "0"
    "first_amount" => 0.1
    "capture_amount" => 0.1
    "status" => "approved"
    "error_code" => null
    "status_detail" => "approved"
    "capture" => true

**Comment by sekizlipenguen** [comment]
Bu arada akbank ve yapıkredi de TX_STATUS her zaman approved gelirken garantide iade ve iptal sonucunda void olarak düşüyor. Diğer bankalar içinde denedikçe bilgi vereceğim.

**Comment by nuryagdym** [comment]
Merhabalar,
Mews\Pos\Gateways\AbstractGateway::TX_HISTORY => rapor amacli, orgenin bugun gerceklesen islemleri listelemek icin kullanilir, ama bankadan bankaya yine davranis degisebilir.
Mews\Pos\Gateways\AbstractGateway::TX_STATUS => yapilan bir islemin sonucu ogrenmek icin kullanilir.

kutuphanenin `status|history` istek sonucu dondurdugu response'da yer alan `tx_status` guvenilir bir deger degil.
Ordaki sorun sundan kaynaklaniyor:
Bankadan donen `status` neyin statusu? sorgu yaptigim odemenin durumu mu yoksa su an gonderdigim **status** sorgulama istediginin durumu mu? Yani ornegin status istege hatali bir istek gonderince, bankada donen status deger odemenin durum degil de _status istegin_ durumunu belirtir. 

Bu status ve history sorulari duzgun map edilmemis oldugunu dusunuyorum.
Cok kullanan olmadigi icin zaman ayirasim yok. Analiz ve anlama sureci ugrastirir.

Akbank, Isbank ve diger bir kac banka ayni (EstPos/Asseco) alt yapiyi kullaniyor, bu yuzden ayni veri donmesi gerekiyor.

**Comment by sekizlipenguen** [comment]
öncelikle dönüş için teşekkürler, 

evet aslında ben bir kaç tanesi için çözüm sağladım değerleri içinde değişiyor ancak dediğin gibi hepsi sağlıklı sonuç verecek gibi durmuyor ve iade işlem talebi göndersen bile yine true olarak geliyor burada herkes kendi yapısını kurarak devam etmesi daha mantıklı(db vs gibi yerlerde iade/iptal sonuçlarını saklayarak çözmeleri)
