### ISSUE TITLE
Finansbank PayFor Desteği

### ISSUE THREAD

**Issue by faguvenli** [mewebstudio/pos#14]
QNBFinansbank'ın yeni kullanmaya başladığı PayFor altyapısını da sisteme ekleyebilir misiniz? Eski altyapıyı kullanmayacaklarmış artık.

**Comment by nuryagdym** [comment]
PayFor ilk defa duyuyorum. Genelde farkli Postnetlerin entegrasyonunun gelistirilmesi icin elimizde bir test yapabilmemiz icin kullanici girisleri, banka tarafinda sunucu IP'mize erisim bilgileri tarzi bilgiler lazim.
Eklenebilir bir sey, gereken bilgileri olursa bu hafta sonu bakabilirim diye dusunuyorum.
https://github.com/ahmett/payconn-qnbfinansbank buldugum bu kutuphane de guzel kodlanmis bir kutuphaneye benziyor. isterseniz bunu deneyin.

**Comment by faguvenli** [comment]
> PayFor ilk defa duyuyorum. Genelde farkli POS yapilarin entegrasyonunun gelistirilmesi icin elimizde bir test yapabilmemiz icin kullanici girisleri, banka tarafinda sunucu IP'mize erisim bilgileri tarzi bilgiler lazim.
> Eklenebilir bir sey, gereken bilgileri olursa bu hafta sonu bakabilirim diye dusunuyorum.
> https://github.com/ahmett/payconn-qnbfinansbank buldugum bu kutuphane de guzel kodlanmis bir kutuphaneye benziyor. isterseniz bunu deneyin.

Hocam bankanın verdiği linkte gerekli açıklamalar var ama ben beceremedim bi türlü
https://vpos.qnbfinansbank.com/Help/home

**Comment by nuryagdym** [comment]
:), dedigim gibi ortam lazim bana, Firma olarak Finansbanka basvurup gereken bilgilerin alip bana iletilmesi lazim. Baska turlu gelistirme sansimiz yok.

**Comment by mewebstudio** [comment]
@nuryagdym konuyla ilgili QNB FinansBank sanal pos desteğe mail gönderdim. Test ortamı ve dökümanlar hakkında yardımcı olup olamayacaklarını sordum. Olumlu bir yanıt alırsam gönderdikleri bilgileri paylaşırım.

**Comment by nuryagdym** [comment]
Ben konusmustum destekle, test ortami icin firma olarak sanal POS icin basvurulmasi gerekiyormus, baska turlu olmaz dediler.

**Comment by faguvenli** [comment]
Bende bütün dokümanlar var. Hatta ben işimi görecek kadar kısmını da yazdım. Yarın ofise gidince elimdekileri paylaşabilirim.

**Comment by mewebstudio** [comment]
@nuryagdym desteğe yazdığım maili cevapladılar ve test ortamıyla birlikte, test kullanıcı bilgisi ve dökümanları ilettiler :)
@nuryagdym sizi takibe aldım. Dökümanları mail adresinize iletebilirim.

**Comment by faguvenli** [comment]
Hocam ben kendi işimi görecek kadar bir kısmını 3D Secure için yazdım. Sizin yazdığınız pakete uydurmak için diğer kısımlarını ekleyebilirsiniz. Class'ın içine yazdığım methodları buraya gönderiyorum. Belki yardımcı olur.

public function __construct($config, $account, array $currencies)
    {
        $this->config = $config;
        $this->account = $account;
        $this->currencies = $currencies;

        $this->url = isset($this->config['urls'][$this->account->env]) ?
            $this->config['urls'][$this->account->env] :
            $this->config['urls']['production'];

        return $this;
    }

    public function get3DFormData()
    {
        $data = [];

        if ($this->order) {
            $this->order->hash = $this->create3DHash();
        }

        $inputs = [
            'MbrId' => $this->mbrId,
            'MerchantID' => $this->account->client_id,
            'UserCode' => $this->account->username,
            'UserPass' => $this->account->password,
            'OrderId' => $this->order->id,
            'SecureType' => '3DPay',
            'TxnType' => $this->type,
            'PurchAmount' => $this->order->amount,
            'InstallmentCount' => $this->order->installment,
            'Currency' => $this->order->currency,
            'CardHolderName' => $this->card->name,
            'Pan' => $this->card->number,
            'Expiry' => $this->card->month . $this->card->year,
            'Cvv2' => $this->card->cvv,
            'OkUrl' => $this->order->success_url,
            'FailUrl' => $this->order->fail_url,
            'Rnd' => $this->order->rand,
            'Hash' => $this->order->hash,
            'MOTO' => 0,
            'Lang' => 'TR',
        ];


        $data = [
            'gateway' => $this->url,
            'inputs' => $inputs
        ];

        return $data;

    }

    public function create3DHash()
    {

        $hash_str = $this->mbrId . $this->order->id . $this->order->amount . $this->order->success_url . $this->order->fail_url . $this->type . $this->order->installment . $this->order->rand. $this->account->merchant_pass;

        return base64_encode(pack('H*', sha1($hash_str)));
    }

    public function check3DHash($data) {

        $return = false;
        $hash_str = $this->account->client_id . $this->account->merchant_pass . $data['OrderId'] . $data['AuthCode'] . $data['ProcReturnCode'] . $data['3DStatus'] . $data['ResponseRnd'] . $this->account->username;
        $hash = base64_encode(pack('H*', sha1($hash_str)));
        if($hash == $data['ResponseHash']) {
            $return = true;
        }
        return $return;
    }

    public function prepare($order, $card = null)
    {
        $this->type = $this->types['pay'];
        if (isset($order->transaction)) {
            if (array_key_exists($order->transaction, $this->types)) {
                $this->type = $this->types[$order->transaction];
            } else {
                dd('Unsupported transaction type');
            }
        }
        $this->order = $order;
        $this->card = $card;
    }

    public function payment($card)
    {
        $this->card = $card;
        $this->make3DPayPayment();
        return $this;
    }

    public function make3DPayPayment()
    {

        $this->request = Request::createFromGlobals();
        $status = 'declined';
//TODO: burdayım. neden status declined dönüyor ona bakacam.
        if ($this->check3DHash($this->request->request->all()) && (string)$this->request->get('ProcReturnCode') == '00') {
            if(in_array($this->request->get('3DStatus'), [1,2,3,4])) {
                $status = 'approved';
            }
        }

        $transaction_security = 'MPI fallback';
        if ($this->request->get('3DStatus') == '1') {
            $transaction_security = 'Full 3D Secure';
        } elseif (in_array($this->request->get('3DStatus'), [2, 3, 4])) {
            $transaction_security = 'Half 3D Secure';
        }

        $this->response = (object) [
            'status' => $status,
            'request' => $this->request
        ];

        return $this;
    }

**Comment by mewebstudio** [comment]
@nuryagdym mailinize ilettim.

**Comment by nuryagdym** [comment]
PayFor ekledim, tum modullerini calistirdim. Code refactoring yapip PR yaparim. en gec onumizdeki hafta sonuna hazir olur

**Comment by mewebstudio** [comment]
@nuryagdym harika, kolay gelsin :)

**Comment by nuryagdym** [comment]
bendeki branch'e push ettim yayinda. 3DModel odeme de 3D authorization basarili durumda da `ProcReturnCode` *00* yerine *V033* . bankaya yazdim cevap geldiginde duzeltmeleri yapip PR olustururum.

**Comment by mewebstudio** [comment]
Elinize sağlık.

**Comment by mewebstudio** [comment]
Issue'yu artık kapatıyorum. Bu konuyla ilgili herhangi bir şey olursa tekrar açarsınız.

**Comment by faguvenli** [comment]
Destekleriniz için çok teşekkür ederim

**Comment by MehmetUluc** [comment]
Selamlar, payfor hata verdi bugün denedim. Finansbankla da görüştüm bana ilettikleri URL ile paketteki urller birbirini tumuyordu bunun yanısıra Guzzle'dan body olarak gönderdiğimizde karşı taraftan 500 error hatası dönüyordu. Guzzle'da body yerine form_data gönderdiğimde sıkıntısız işlem sıkıntısız gerçekleşti ancak bu sefer de response farklıydı, ben kabaca bazı düzeltmeler yaparak çalıştırdım. Kodu refactor ederek göndermeye çalışırım.

**Comment by nuryagdym** [comment]
Evet, en son calisiyordu, bir seyler degistirmisler. Su an 3D odemede bu hatayi veriyor: 

```
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://vpostest.qnbfinansbank.com/Gateway/XmlGate.aspx` resulted in a `500 Internal Server Error` response: <html> <head> <title> _404 </title> </head> <div class="main"> <h3> 404 </h3> </div> (truncated...) in /var/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /var/www/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/vendor/guzzlehttp/promises/src/P in /var/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```
@faguvenli en son siz kullaniyordunuzu diye biliyorum PayFor'yu. bu sorunu yasiyor musunuz?

**Comment by faguvenli** [comment]
ben payfor apiyi kullanıyorum. karttan çekim yapmak istediğimde limitimin üstünde bir işlem denediğimde herhangi bir hata vermedi. Kart Limiti Yetersiz uyarısını sorunsuz bir şekilde ekrana basıyor. 
Sistem canlıda olduğu için gerçek bir alışveriş deneyemedim ama limit yetersiz dediğine göre tahminimce çekimi de sorunsuz bir şekilde gerçekleştiriyordur.
sizdeki 500 hatası veren yerde cep telefonuna 3d kontrol mesajı gelmeden önce mi hata veriyor yoksa sonra mı?

**Comment by faguvenli** [comment]
benim config dosyasındaki payfor ayarları şu şekilde:
'qnbfinansbank-payfor' => [
            'name'  => 'QNBFinansbank-PayFor',
            'class' => Mews\Pos\Gateways\PayForPos::class,
            'urls'  => [
                'production'    => 'https://vpos.qnbfinansbank.com/Gateway/XMLGate.aspx',
                'test'          => 'https://vpostest.qnbfinansbank.com/Gateway/XmlGate.aspx',
                'gateway'       => [
                    'production'    => 'https://vpos.qnbfinansbank.com/Gateway/Default.aspx',
                    'test'          => 'https://vpostest.qnbfinansbank.com/Gateway/Default.aspx',
                ],
                'gateway_3d_host'       => [
                    'production'    => 'https://vpos.qnbfinansbank.com/Gateway/3DHost.aspx',
                    'test'          => 'https://vpostest.qnbfinansbank.com/Gateway/3DHost.aspx',
                ],
            ]
        ]

**Comment by nuryagdym** [comment]
bende hata 3d onay ekranindan geri websiteye yonlendirdiginde yapiyor. orda PayFor gateway kodu 3D authentication barili olup olmadigini kontrol edip, Finansbanka odemenin tamamlanmasi icin bir istek gonderiyor. o istek patliyor nedense.

**Comment by MehmetUluc** [comment]
> bende hata 3d onay ekranindan geri websiteye yonlendirdiginde yapiyor. orda PayFor gateway kodu 3D authentication barili olup olmadigini kontrol edip, Finansbanka odemenin tamamlanmasi icin bir istek gonderiyor. o istek patliyor nedense.

Evet bende de burada patlıyor, dediğim gibi sorunu çözdüm. En kısa zamanda paylaşırım.

**Comment by nuryagdym** [comment]
@MehmetUluc musteride calisiyorsa, var olani degistirmek yerine yeni bir Gateway olusturup (belki PayForPos'u extend eder) o sekilde ilerlemeniz iyi olur. zaten anladigim kadariyla API URL'ler farkli. Anladigim kadariyla Yapikredinin PosNet'inin de 2 tur URL'i var, ikisi farkli sekilde calisiyor
