### ISSUE TITLE
3D yönlendirme URL'ini iframe içinde çalıştırma

### ISSUE THREAD

**Issue by ekremogul** [mewebstudio/pos#140]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | v0.12.1 |
| Gateway ismi| Ziraat, Ziraat 3d |
| Banka ismi| Ziraat |

## Sorunuz

Arkadaşlar selam. Aslında problemden ziyade bir soru. Yapmak istediğim, ihtiyacım olan fakat yapamadığım ve örneğini bulamadığım bir sorunum var. Yazılımımda tüm ödeme işlemleri Modal içerisinde gerçekleştiriliyor. Bütün adımlarda anlık ödeme gerçekleşiyor. Bir alışveriş sitesi değil. Sepet vs. mantığı ile değil aktif bir process devam ederken kişiler mesajlaşır gibi işlemler yürütüyor ve arada o process için ödemeler gerçekleştiyor. 

Sistemde Cüzdan yapısı var. Cüzdanında para varsa direk ödeme gerçekleştirebiliyor. Para yok ise kart ile ödeme yapması gerekiyor ve sorun burada devreye giriyor. Ödemelerde 3D yapacağı zaman yönlendirme yapmam gerekiyor ama yönlendirme yapmadan 3d yönlendirme URL'ini alabilirsem 2. bir modal içerisinde iframe ile ilgili yönlendirmeyi yapıp sonuca göre bir önceki modal'a dönmek istiyorum. Ödeme alınımda 3-5 den fazla varyasyon ve o varyasyonlar da kendi içerisinde 3-5 ayrı varyasyona sahip yönlendirme yapmak çok ama çok işimi zorlaştıracak. yeni bir varyasyon oluşturmak çok sıkıntılı ve sürdürülebilir olmayacak. 

Bu konuda beni yönlendirebilecek birileri olursa çok memnun olurum.

Teşekkürler

## Göndermeden önce kontroller

* [ ] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [ ] Dökümantasyonu okudum, araştırdım ve konuyla ilgili bilgileri bulamadım. [dökümantasyon](https://github.com/mewebstudio/pos/blob/master/README.md)
* [ ] İlgili örnek kodları kontrol ettim ve konuyla ilgili bilgileri bulamadım. [örnek kodlar](https://github.com/mewebstudio/pos/tree/master/examples)

**Comment by nuryagdym** [comment]
Merhabalar,
Modal ile kullanim ornegi coktan beri yapmak istiyorum, belki bu hafta sonu ekleyeceg 😄.

Hatirladigim kadariyla en son @mettleshade kendi projesinde modal ile yapmisti. Ancak Kuveytte sanirim sorun vardi, o da cozuldu diye biliyorum.



$pos->get3DFormData() methoddan gelen arrayi modal icinde bir forma basilmasi gerekiyor diye hatirliyorum. Bundan once de kredi kart bilgilerin kullanicidan alinmasi gerekiyor.

**Comment by ekremogul** [comment]
Zaten yapı şu şekilde. önce kredi kartı bilgilerini giriyor. Pay/Öde butonuna basınca 3D devreye girecek. 

<img width="786" alt="Ekran Resmi 2023-06-01 10 24 47" src="https://github.com/mewebstudio/pos/assets/4357998/1251f08b-f126-4ecf-8aa4-2d44ccf64171">

**Comment by nuryagdym** [comment]
**v0.13.0** versiyonda /examples altinda ornek kodlar yer almaktadir.
