### ISSUE TITLE
EstPos Response undefined index ERRORCODE on success

### ISSUE THREAD

**Issue by lansas** [mewebstudio/pos#143]
EstPos class ında mapStatusResponse fonksiyonu dahil bir çok response fonksiyonda

```

//$result['auth_code']      = $rawResponseData['Extra']['AUTH_CODE'];
$result['auth_code']      = $rawResponseData['Extra']['AUTH_CODE'] ?? null;

//'error_code'       => $responseData['Extra']['ERRORCODE'],
'error_code'       => $responseData['Extra']['ERRORCODE'] ?? null,
   
   
```

gibi satırlar isset kontrolü gerektiriyor. Çünkü her banka ERRORCODE elementini; error oluşmadığı sürece hiç array da tanımlayıp göndermiyor. Örnek: Card Plus KKTC kredi kartları.

**Comment by nuryagdym** [comment]
Merhabalar, 
bunlara bakarim, duzeltmeleri yaparim.
her bir input icin isset kontolu yapilmasina karsiyim, hepsine isset ekleyince hangileri basarili durumda gelmesi gerekiyor, hangisi gelmemesi gerekiyor anlasilmiyor. 

Kod icinde normalde bu durum genelde su sekilde ele aliniyor: https://github.com/mewebstudio/pos/blob/master/src/DataMapper/ResponseDataMapper/EstPosResponseDataMapper.php#L316

**Comment by nuryagdym** [comment]
Merhabalar, 

`$rawResponseData['Extra']['AUTH_CODE']`

 satiri kodda bulamadim
