### ISSUE TITLE
Ornek kodlar iceren dokumantasyon

### ISSUE THREAD

**Issue by thevobos** [mewebstudio/pos#148]
Merhaba,

Dokümantasyon readme'de örnek 3D ödeme örnegi var fakat geri kalan '3d HOST', '3D PAY HOSTING', '3D PAY' ve 'REGULAR' gibi örneklerin örnek klasor içeriği çok karışık ve bunun readme'de oldugu gibi örnek şeklinde veririseniz çok daha sağlıklı olacaktır.  Teşekkürler.

**Comment by nuryagdym** [comment]
Merhaba, 
Katiliyorum, zaman buldugumda eklerim.

**Comment by nuryagdym** [comment]
v1.0.0 versiyonda `/docs` altinda ornek kodlar eklendi
