### ISSUE TITLE
EST Ziraat Hk.

### ISSUE THREAD

**Issue by FikretCin** [mewebstudio/pos#149]
Merhabalar, 0.12 versiyonunda bulunan est ile çalışan ziraat configi artık çalışmadığı için mi kaldırıldı ? Sistemin verdiği hesap bilgileri ile yeni zirraat-vpos (paylex) uyuşmuyor. Config e manuel eklesek çalışır mı ?

`
        'ziraat'    => [
            'name'  => 'Ziraat Bankası',
            'class' => Mews\Pos\Gateways\EstPos::class,
            'urls'  => [
                'production'    => 'https://sanalpos2.ziraatbank.com.tr/fim/api',
                'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/api',
                'gateway'       => [
                    'production'    => 'https://sanalpos2.ziraatbank.com.tr/fim/est3dgate',
                    'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
                ],
                'gateway_3d_host'       => [
                    'production'    => 'https://sanalpos2.ziraatbank.com.tr/fim/est3dgate',
                    'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
                ],
            ],
        ],
`

**Comment by nuryagdym** [comment]
Merhablar, saglanan configler ornek amaclidir.
O yuzden README.MD ornekte kopyala ornegi saglanmistir. 

Eski ayarlari kullanabilirsiniz, ancak EstPos (Asseco) ile calisan bankalar artik sha512 hashkeme metoduna geciyorlar.
Eski SHA1 algoritma (EstPos'un kullandigi) artik calismayabilir.

Kisacasi Ziraat eski konfigurasyonunuzda
```
'ziraat'    => [
	'name'  => 'Ziraat Bankası',
	'class' => Mews\Pos\Gateways\EstPos::class,
	'urls'  => [
		'production'    => 'https://sanalpos2.ziraatbank.com.tr/fim/api',
		'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/api',
		'gateway'       => [
			'production'    => 'https://sanalpos2.ziraatbank.com.tr/fim/est3dgate',
			'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
		], 
		'gateway_3d_host' =>  [ 
			'production'    => 'https://sanalpos2.ziraatbank.com.tr/fim/est3dgate',
			'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate', 
		], 
	], 
],
```
bu kismi: 
```
'class' => Mews\Pos\Gateways\EstPos::class,
```

su sekilde degisterip deneminiz tavsiye ederim: 

```
'class' => Mews\Pos\Gateways\EstV3Pos::class,
```

**Comment by FikretCin** [comment]
Teşekkürler
