### ISSUE TITLE
İş Bankası (Asseco) islemtipi => TranType olarak degisti

### ISSUE THREAD

**Issue by huseyinyildirim** [mewebstudio/pos#150]
Merhaba,

İlk önce belirtmeliyimk ki open source dünyasına böyle bir library kazandırdığınız için teşekkür ederim.

Kütüphanenizi kullanarak İş Bankasını implemente ediyorum ama İş Bankasından aldığım dokümana göre endpointlerine "TranType=Auth" diye bir parametre daha göndermem gerekiyor. İncelediğimde kütüphane mapperlarında "islemtipi" var ama banka galiba orada bir özelleştirme yapmış. İşbankası için gönderdiğim forma yeni bir parametre/hidden nasıl ekleyebilirim.

İyi çalışmalar.

**Comment by nuryagdym** [comment]
Merhabalar, dokumantasyonu paylasirsaniz sevinirim.
```
$formData = $pos->get3DFormData();
```
islemtipi'ne nu sekilde erisilebilir:  `$formData['inputs']['islemtipi']`

$formData icerigi kullaniciya gondermeden once isteginize gore degistirebilirsiniz.

```
$formData['inputs']['TranType'] = 'Auth';
unset($formData['inputs']['islemtipi']);
```

**Comment by nuryagdym** [comment]
Is bankasi icin bir de EstPos yerine EstV3Pos'u kullanmayi deneyin

**Comment by huseyinyildirim** [comment]
> dokumantasyonu paylasirsaniz sevinirim.

https://easyupload.io/h9bnj7

**Comment by huseyinyildirim** [comment]
> Is bankasi icin bir de EstPos yerine EstV3Pos'u kullanmayi deneyin

Nasıl kullanabilirim? AccountFactory classı altında EstV3Pos ile ilgili bir method göremedim.

**Comment by nuryagdym** [comment]
surda anlatildigi gibi yapmaniz yeterli: https://github.com/mewebstudio/pos/issues/149

**TranType** icin ayri bir guncelleme cikarim zaman buldugumda

**Comment by huseyinyildirim** [comment]
> Alttaki sekilde cekip test edip haber verirseniz sevinirim.

Güncelleme için teşekkür ederim. Kütüphanenize yabancıyım, nasıl bir test yapmam gerekiyor? İyi çalışmalar.

**Comment by nuryagdym** [comment]
README.MD 3D odeme icin ornek kodlar var.

ayni ordaki kodlar calisirsa, calisiyor demek. 
**EstV3Pos** ile test edilecek.

**Comment by huseyinyildirim** [comment]
> README.MD 3D odeme icin ornek kodlar var.
> 
> ayni ordaki kodlar calisirsa, calisiyor demek. **EstV3Pos** ile test edilecek.

pos.php aşağıdaki gibi ekleme yaptım ve _config.php aşağıdaki gibi düzenlediğimde pos işlemi yaptı. Çekim gerçekleşmedi ama başka bir sebebi var. Bu şekilde çalışıyor.

`'isbank-v3'    => [
            'name'  => 'İşbank T.A.S.',
            'class' => Mews\Pos\Gateways\EstV3Pos::class,
            'urls'  => [
                'production'    => 'https://sanalpos.isbank.com.tr/fim/api',
                'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/api',
                'gateway'       => [
                    'production'    => 'https://sanalpos.isbank.com.tr/fim/est3Dgate',
                    'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
                ],
                'gateway_3d_host'       => [
                    'production'    => 'https://sanalpos.isbank.com.tr/fim/est3Dgate',
                    'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
                ],
            ],
        ],`

`$account = \Mews\Pos\Factory\AccountFactory::createEstPosAccount(
    'isbank-v3',
    'xxxxxxxxxx',
    'xxxxxxxxx',
    'xxxxxxxxx',
    \Mews\Pos\Gateways\AbstractGateway::MODEL_3D_SECURE,
    'xxxxxxxxx',
    AbstractGateway::LANG_TR
);`

**Comment by nuryagdym** [comment]
kodda sorun yok, yayinlayabilirim yani?

Birde canli ortamda denenmesi gerekiyor.
Test ortam ile canli ortam arasi farklilik olabilir

**Comment by huseyinyildirim** [comment]
Yayınlayın. Başka bir sorunla karşılaşırsam ivedikle bildiririm.

**Comment by nuryagdym** [comment]
0.13.2 versiyonu indirebilirsiniz.
