### ISSUE TITLE
İş Bankası İmece Tarım Kartları Hk.

### ISSUE THREAD

**Issue by huseyinyildirim** [mewebstudio/pos#153]
Merhaba,

İş Bankası'nın İMECE Tarım kartları var ve faizsiz ödemeyi dilediğiniz ay kadar ileri atmaktadır.

Servislere ise bununla ilgili aşağıdaki gibi parametrelerde gönderim yapmam gerekiyormuş.

Bu parametreleri nasıl eklemem gerekiyor. İyi çalışmalar.

`<Extra>
<IMCKOD>İmece Ürün Bilgisi</IMCKOD>
<FDONEM>Faizsiz Dönem Bilgisi</FDONEM>
</Extra>`

**Comment by huseyinyildirim** [comment]
<img width="905" alt="estposv3" src="https://github.com/mewebstudio/pos/assets/6034013/46034c9f-58ac-43d6-94e1-ac4dafcbfd92">

Banka bizden resimdeki formatta istiyor. Payten destek ile görüştüm ve bu konuda tarafıma bilgi döndüğünde gelişmeleri buraya aktaracağım.

**Comment by nuryagdym** [comment]
Merhabalar, 

1. `Extra` alani baktigim kadariyla kutuphane su an sadece status, cancel ve refund islemlerde gonderiyor. Odeme islemleri icin bu alani gondermiyor. Bendeki dokumantasyonlarina baktigimda da odeme islemlerinde extra alani gonderildigini goremedim. 
Ama denem olarak suradaki https://github.com/mewebstudio/pos/blob/master/src/DataMapper/EstPosRequestDataMapper.php#L74
`$requestData` icine ekleyip calisip calismadigini kontrol edebilirsiniz.

2. Hash ile ilgili bir sorun olmamasi gerekiyor. Bunlarin istedigi haslama yontemde degiskenlerin siralamasi onemli degil sadece gonderilecek tum alanlar (arraydeki siralamasi neyse) oldugu gibi hashlenecek ve o Hash deger gonerilecek. 
Hash ile ilgili sorun olmamasi gerekiyor. Test ortamda calisiyor bende. Sorun olsaydi hash sorunu oldugunu belirten bir hata verirdi.

**Comment by huseyinyildirim** [comment]
Cevabınız için teşekkür ederim.

Bankadan dün aldığımız bilgiye göre, bize açtığı sanal pos sadece İMECE kartları geçmek içinmiş. İşin ilginç tarafı İMECE kartla geçtiğimizdede aynı hatayı almamız oldu. Banka bu konuda pazartesi cevap verecektir. Ona göre bir düzenleme gerçekleştirebiliriz.

**Comment by nuryagdym** [comment]
ayni hata derken?
bir de IMECE kart normal VISA/MASTER kart oluyor degil mi?

**Comment by huseyinyildirim** [comment]
İlk hata :SL113 Seçilen bölümde, ilgili işlem tipine ait mali koşul tanımı bulunmamaktadır.
Son hata: SL109 Seçilen bölümde, ilgili işlem tipine ait mali koşul tanımı bulunmamaktadır.

İş bankası imece kartlarını "4410 77" ile başlayan VISA ticari debitlere tanımlamış.

**Comment by huseyinyildirim** [comment]
Merhaba,

Imece kartlarda bankaya ayrıca parametre iletmek gerekiyormuş. Dokümantasyon ektedir.

Aşağıdaki gibi FDONEM ve IMCKOD parametrelerini aşağıdaki örnekteki gibi, hash içine alfabetik sıra ile eklemek gerekiyormuş.

`amount|BillToCompany|BillToName|callbackUrl|clientid|currency|failUrl|**fdonem**|hashAlgorithm|**imckod**|Inst alment|lang|okurl|refreshtime|rnd|storetype|TranType|storeKey`

[İs Bankası_İmece Kart_Üye İşyeri Entegrasyon Dokümanı_v3.0.pdf](https://github.com/mewebstudio/pos/files/12527097/Is.Bankasi_Imece.Kart_Uye.Isyeri.Entegrasyon.Dokumani_v3.0.pdf)

**Comment by nuryagdym** [comment]
Merhaba,

Imece kart icin test kart var midir?
Test kart varsa test ortamda calisir mi? 
Bir de bu IMECE kart sadece isbanka ozel mi yoksa diger bankalar tarafindanda verilir mi?

Hash islemi dedigim gibi degisiklik gerektirmeden calismasi gerekiyor.
**3D_SECURE** odeme kullaniyorsaniz yukarda anlattigim gibi burda
https://github.com/mewebstudio/pos/blob/master/src/DataMapper/EstPosRequestDataMapper.php#L74
`$requestData` icine ekleyip calisip calismadigini kontrol edebilirsiniz.

Bu asamada zaten hashing yapilmiyor.

**Comment by huseyinyildirim** [comment]
> Imece kart icin test kart var midir?
> Test kart varsa test ortamda calisir mi?

Bunların bilgisini alıp bildireceğim.

> Bir de bu IMECE kart sadece isbanka ozel mi yoksa diger bankalar tarafindanda verilir mi?

IMECE kart İşbankasına özel tarım kartıdır. Ticari debit kart ve özelliği ise fdonem parametresi ile gönderilen int değere göre faizsiz ödemeyi erteliyor. Diğer bankalarda tarım kartları var ama özelliği nedir bilmiyorum.

> **3D_SECURE** odeme kullaniyorsaniz

Evet kullanıyorum.

> https://github.com/mewebstudio/pos/blob/master/src/DataMapper/EstPosRequestDataMapper.php#L74
> `$requestData` icine ekleyip calisip calismadigini kontrol edebilirsiniz.

Gerekli düzenlemeleri yapar ve test eder, tarafınıza bildirim yaparım.

Teşekkürler.

**Comment by huseyinyildirim** [comment]
> Imece kart icin test kart var midir?
> Test kart varsa test ortamda calisir mi?

4242 4242 4242 4242
10/2028
123

**Comment by nuryagdym** [comment]
Hmm, denedigimde 3D onaylama asamasinda "Authentication unavailable (DS)" hatasi aliyorum.

Belki bendeki test API hesap bilgileri bu kart icin uygun degil. 

Kendiniz calistirirsaniz haber verirseniz kodlari ona gore guncellerim.

**Comment by huseyinyildirim** [comment]
EstV3Pos ilemi denediniz?

**Comment by nuryagdym** [comment]
Evet

**Comment by huseyinyildirim** [comment]
> **3D_SECURE** odeme kullaniyorsaniz yukarda anlattigim gibi burda
> https://github.com/mewebstudio/pos/blob/master/src/DataMapper/EstPosRequestDataMapper.php#L74
> `$requestData` icine ekleyip calisip calismadigini kontrol edebilirsiniz.

Burada benim anlamadığım bir şey var. Frontend tarafında forma bir hidden eklemem yeterli olmuyor mu?

**Comment by nuryagdym** [comment]
3D secure kullaniyorsaniz, yani AbstractGateway::MODEL_3D_SECURE, formun icerigini degistirmemeniz gerekiyor. 
Sadece vendor/ altinda `EstPosRequestDataMapper` bu sinifi bulup create3DPaymentRequestData() methodu su alttaki kod ile degistirip tekrar deneyin:

```
public function create3DPaymentRequestData(AbstractPosAccount $account, $order, string $txType, array $responseData): array
{
    $requestData = $this->getRequestAccountData($account) + [
            'Type'                    => $this->mapTxType($txType),
            'IPAddress'               => (string) ($order->ip ?? ''),
            'Email'                   => (string) $order->email,
            'OrderId'                 => (string) $order->id,
            'UserId'                  => (string) ($order->user_id ?? ''),
            'Total'                   => (string) $order->amount,
            'Currency'                => $this->mapCurrency($order->currency),
            'Taksit'                  => $this->mapInstallment($order->installment),
            'Number'                  => $responseData['md'],
            'PayerTxnId'              => $responseData['xid'],
            'PayerSecurityLevel'      => $responseData['eci'],
            'PayerAuthenticationCode' => $responseData['cavv'],
            'Mode'                    => 'P',
            'Extra' => [
                'IMCKOD' => 'İmece Ürün Bilgisi',
                'FDONEM' => 'Faizsiz Dönem Bilgisi',
            ]
        ];

    if ($order->name) {
        $requestData['BillTo'] = [
            'Name' => (string) $order->name,
        ];
    }

    if (isset($order->recurringFrequency)) {
        $requestData += $this->getRecurringRequestOrderData($order);
    }

    return  $requestData;
}

```

**Comment by huseyinyildirim** [comment]
Merhaba,

Bu şekilde çalıştırdım. Teşekkür ederim. Buna göre bir güncelleme yapacakmısınız? Güncellemelerde patlamak istemem.

Diğer konu form inputlarından buraya gerekli parametreleri gönderebilirim? Repo içindeki example düzenleme yaparak kullanıyorum.

**Comment by nuryagdym** [comment]
bu ozelligi destekleyen v0.14.0 versiyon ciktim.
Kullanim sekline burdan bakabilirsiniz: https://github.com/mewebstudio/pos/blob/master/docs/CHANGELOG.md

**Comment by huseyinyildirim** [comment]
> bu ozelligi destekleyen v0.14.0 versiyon ciktim.
> Kullanim sekline burdan bakabilirsiniz: https://github.com/mewebstudio/pos/blob/master/docs/CHANGELOG.md

Güncelleme için teşekkür ederim.

`if (isset($order->is_imece_card) && true === $order->is_imece_card) {
    $requestData['Extra']['IMCKOD'] = 'İmece Ürün Bilgisi';
    $requestData['Extra']['FDONEM'] = 'Faizsiz Dönem Bilgisi';
}`

Burayı biraz daha esnek hale getirebileceğimizi düşünüyorum.

IMCKOD bilgisini banka vermektedir ve İşbankası için bu 9999'dur.

Ziraat Bankası'da Asseco alt yapısını kullanmaya başlamış ve Ziraat Bankasının vereceği tarım kart imckod bilgisi 9999'dan farklı olabilir.

Ayrıca FDONEM kullanıcının form tarafından gönderileceği bir parametredir. Banka üye iş yerine FDONEM max değer tanımlıyor.

Ödeme yapacak kişide 1-5 ay arasında, vade farkına göre seçim yapar. Örneğin 4 seçti, geçtiği meblağı çiftçi bankaya 4 ay sonra faizsiz ödeyecektir.

Bizim form üzerinden IMCKOD ve FDONEM bilgisini gönderebilmemiz gerekiyor.

**Comment by nuryagdym** [comment]
Merhabalar,

Isterseniz gereken guncellemeleri yapip PR acabilirsiniz.

**Comment by huseyinyildirim** [comment]
> Merhabalar,
> 
> Isterseniz gereken guncellemeleri yapip PR acabilirsiniz.

PR oluşturdum. Bu parametre isimleri bankadan bankaya değişebilir. Ona göre eklemeler yapabiliriz.
