### ISSUE TITLE
Yapıkredi Bankası'nda "Geçersiz Para Birimi" Hatası

### ISSUE THREAD

**Issue by yorulmazsinan** [mewebstudio/pos#154]
Diğer tüm bankalarda işlemler sorunsuz ilerlerken, Yapıkredi bankasında banka ekranına yönleneceği esnada şu hatayı alıyorum:

Exception {#1368 ▼
  #message: "Para Birimi Uygun Değil."
  #code: 0
  #file: "/var/www/vendor/mews/pos/src/Gateways/PosNet.php"
  #line: 137
  trace: {▶}
}

**Comment by nuryagdym** [comment]
Orderda hangi para birimi kullaniyorsunyz?

**Comment by yorulmazsinan** [comment]
> Orderda hangi para birimi kullaniyorsunyz?

TRY

**Comment by yorulmazsinan** [comment]
> > Orderda hangi para birimi kullaniyorsunyz?
> 
> TRY

Sorun bununla alakalıymış. "TL" gönderince düzeldi.
