### ISSUE TITLE
Yeni Sorgu Ekleme

### ISSUE THREAD

**Issue by huseyinyildirim** [mewebstudio/pos#156]
Merhaba,

Aşağıdaki gibi sorguyu EST için kütüphaneye nasıl ekleyebiliriz?

```
<?xml version="1.0" encoding="UTF-8"?> <CC5Request>
<Name>ApiUser</Name>
<Password>Pword</Password>
<ClientId>190008325</ClientId>
<OrderId></OrderId>
<Type>Query</Type>
<Number>5169321111111111</Number>
<Expires>12/2022</Expires>
<Cvv2Val>123</Cvv2Val>
<Total>10.00</Total>
<Currency>949</Currency>
<Extra>
<BASAKSORGU></BASAKSORGU>
</Extra> </CC5Request>
```

**Comment by nuryagdym** [comment]
Merhabalar, 

bu konuda genel bir guncelleme yapmayi planliyorum, aklimdakileri yapmak icin bir kac ay gerekebilir. O zamana kadar testleri gececek sekilde PR acarsaniz kabul edebilirim.

**Comment by nuryagdym** [comment]
Burdaki istenilen yeni tip sorgu mu? yoksa var olan sorguya yeni ekstra veri eklmeme mi?

Yeni tip sorgu eklenmesi ise ne tip bir istek oldugunu anlamam gerekiyor.
