### ISSUE TITLE
EST V3 HASH Doğrulama

### ISSUE THREAD

**Issue by esakarya** [mewebstudio/pos#161]
Arkadaşlar bu hash sırasında bi sıkıntı mı var, benmi tutturamıyorum anlamadım.  hiç bir şekilde ilk requestteki doğrulama hashını checkHash ile doğrulayamadım. bu hash dataya kart bilgileri falan alfabetik sırayla komple dahil oluyor. ilk requestteki ErrMsg, mdErrorMsg MaskedPan falanda dahil oluyor doğrumudur ?

**Comment by nuryagdym** [comment]
Merhabalar, test ortaminda denedigimde EstV3Pos sorunuz calisiyor. Bu kodda bir guncelleme yapilmadi.
Asseco'nun en son istedigi o sekilde hashlamak, gonderilen ve gelen verilerin tamaminin alphabetik siraya gore siralanip hashlanmesi.

Belki `$pos->setTestMode(true/false)` hatali olabilir.
Yani istegi gonderirken  canli mode'da gonderip, bankadan donen cevabi islerken test modda isliyor olabilirsiniz.
Ya da hesap bilgiler hatali, yani istek gonderilirken kullanilan hesap bilgileriyle, bankadan donen veriyi islemek icin kullanilan hesap bilgileri ayni degil. 

Hangi banka bu arada?
Olmadi EstV3Pos yerine EstPos'u kullanmayi dener misiniz.

**Comment by esakarya** [comment]
EstPostda sıkıntı yok, büyük küçük harf sıralaması ile ilgili bi durum sanırım.  deniyorum

**Comment by esakarya** [comment]
Sıralamadada yok check hası devre bıraktığımda çok güzel çalışıyor :) benim yolladığım hash doğru muhtemelen. gelen hash doğrumu değilmi onu beceremedim :)

**Comment by esakarya** [comment]
Son bir sorum olucak, gelen post datayı direk kod ile direk hash e çeviriyorum gene gelen veriyi elde edemyiorum. test ortamın bir sıkıntısı olabilirmi?

**Comment by esakarya** [comment]
@nuryagdym rica etsem başarılı bir sonuçta sana gelen request data ve hashstr nin çıktsını verebilirmisin ?
dünden beri bununla uğraşıyorum benim oluşturduğum hash doğru ama karşıdan geleni doğrulamada bi sıkıntı var. diziimde nerde hata var ordan yakalarım belki.

**Comment by nuryagdym** [comment]
Merhabalar, ben 1 haftalik tatile ciktim, bilgisayar yanimda degil. Ornek olarak test klasore bakabilirsiniz. 
**tests/Crypt/EstV3PosCryptTest.php** icinde test olmasi gerekiyor. 

Isterserseniz epostama sizdeki kodlari (kullandiginiz test account bilgilerle beraber) gonderin kontrol edeyim.

**Comment by esakarya** [comment]
çok makbule geçer

**Comment by esakarya** [comment]
Gönderdim, şimdiden teşekkür ederim. gelen request datada ki hash ı hiç bir şekilde tutturamadım.

**Comment by nuryagdym** [comment]
bana gonderdiginiz veriye bakinca bir sorun goremedim, 
Bilgisayar olmadan yardimci olamiyorum. 

Hesap icin MODEL_3D_SECURE ile odemeyi dener misiniz. Sizdeki su an MODEL_3D_PAY anladigim kadariyla

**Comment by esakarya** [comment]
Aslinda checkhash i devre disi biraktigimda odemede aliyor iptalde ediyor bi sorun gozukmuyor, sadece veride gelen hash i dogrulayamiyoruz, evet 3d pay bide secure ile deniyim olmadi checkhash i devre disi birakirim, tesekkurler ilgin icin

________________________________

**Comment by nuryagdym** [comment]
Sorun cozuldu sanirim, sorun neymis merak ettim 😄

**Comment by esakarya** [comment]
😅 Gelen reposive islem id si ekliyordum daha sonra, siparisin durumunu guncellemek icin, o kacmis gözden
