### ISSUE TITLE
Kuveyttürk ödeme sistemi sms ekranına yönlenmiyor

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#162]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  |
| PHP versiyonu | 8.0.1 |
| Gateway ismi|  |
| Banka ismi| kuveyt türk |

### Hatanın özeti

_(yaşadığınız sorunun detayları)_
kart bilgileri girdikten sonra formdata oluşmuyor sms geliyor fakat sms ekranına gitmiyor
### Bağımsız kod veya hatayı yeniden oluşturmanın bir yolu

_(Sorunu düzeltmemize yardımcı olmak için lütfen aşağıdaki metni doldurun)_

### Beklenen Sonuç

_(Beklenen (doğru) davranış neydi?)_

### Gerçek sonuç

_(Mevcut (hatalı) davranış nedir?)_

## Göndermeden önce kontroller

* [ ] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [ ] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
Merhabalar,

Burdaki 
https://github.com/mewebstudio/pos/blob/master/src/Gateways/KuveytPos.php#L354

**$bankResponse** icerigini .txt file icine koyarak benin epostama gonderir misin.

Bir tek KuveytPos HTML response donuyor. onu da parse edip form data olusturuyorum. Gonderilen HTML farkli formatta olabilir bu yuzdende parse edememistir.

**Comment by mettleshade** [comment]
> Merhabalar,
> 
> Burdaki https://github.com/mewebstudio/pos/blob/master/src/Gateways/KuveytPos.php#L354
> 
> **$bankResponse** icerigini .txt file icine koyarak benin epostama gonderir misin.
> 
> Bir tek KuveytPos HTML response donuyor. onu da parse edip form data olusturuyorum. Gonderilen HTML farkli formatta olabilir bu yuzdende parse edememistir.

dün akşamda 10 dan itibaren hata almaya başladı şuan hiç ödeme yapılamıyor bankaya bildirdim inceliyorlar sizede atıyorum

**Comment by nuryagdym** [comment]
bu satiri https://github.com/mewebstudio/pos/blob/master/src/Gateways/KuveytPos.php#L368
su sekilde degistirerek tekrar dener misin
```
$dom->loadHTML($response, LIBXML_NOERROR);
```

**Comment by mettleshade** [comment]
ödeme düzeldi bu sorun yeni mi oldu banka güncelleme mi verdi bilginiz varmı

**Comment by mettleshade** [comment]
> tmm, sonra bir guncelleme cikarim.
> 
> Sorun kart bazli olabilir. Kullandiginiz kart ile bu zamana kadar test yapilmamis olabilir.
> 
> Nasil bir kart kullandiniz?

bende ziraat bankası vardı müşterilerde almaya başladı akşam 22 den sonra başladı bu sorun buraya yazmadan 1 saat öncede bütün kartları kabul etmemeye başladı, niğdede bizim kullandığımız bankaya 3 kişi daha bildirim yapmış onlarda bu paketi kullanıyor olabilir, müsaitseniz hemen güncelleme çıksanız iyi olur diye düşünüyorum çünkü banka request istedi yarım saat kadar önce

**Comment by nuryagdym** [comment]
Tmm, bu aksam release cikmaya calisirim.

**Comment by nuryagdym** [comment]
sorunu duzelttim ve v0.15.1 olarak yeni release ciktim
