### ISSUE TITLE
Kuveyt turk Halkbank,Ziraat gibi bankalarda sorun.

### ISSUE THREAD

**Issue by esakarya** [mewebstudio/pos#164]
Öncelikle bankadan alamadığımız desteği vermeye calıştığınız için cidden teşekkür ederim. 
Kuveyt posta şöyle bir sorun yaşıyoruz.  Özellikle devlet bankalarında Ziraat, Halkbank gibi kredi kartlarında 3d ödeme ekranı oluşmuyor 
Şifre girme ekranı, hatalar ve diğer işlem sonucuna göre dönmesi gereken verinin hepsi dönüyoır. Bu sorunu yaşayan oldumu daha önce ? 
3d ekranı için oluşması gereken kuveytten gelen veriyi ekliyorum. yardımclı olabilecek çıkarsa sevinirim.

[kuveyt_3d.txt](https://github.com/mewebstudio/pos/files/13224445/kuveyt_3d.txt)

**Comment by nuryagdym** [comment]
Merhabalar,

Dün de bununla ilgili issue #162 oluşturuldu.
Ayni sorun oldugunu tahmin ediyorum.

Kutuphaneyi 0.15.1 versiyona guncelleyip tekrar dener misiniz.

**Comment by esakarya** [comment]
Hocam merhaba kütüphane olarak kullanmıyorum çalışmanızı. malesef farklı dilde kullanıyorum. tam olarak bu LIBXML_NOERROR kodu dönen html den hangi taglı datayı temizliyor ?

**Comment by esakarya** [comment]
Ayrıyetten benim sıkıntım şu şekilde. aynı sorundanmı kaynaklanıyor acaba ? @nuryagdym 
![image](https://github.com/mewebstudio/pos/assets/61056242/e8380584-c975-42da-8e5b-c02c914699fb)

**Comment by nuryagdym** [comment]
@mettleshade bakar misin, senin karsilastigin sorun ile ayni mi bu?

@esakarya  https://github.com/mewebstudio/pos/blob/f1a42a715998a0104cfdc39f0dad6e25ae1680ce/src/Gateways/KuveytPos.php#L369
burda yazdigim gibi `APM_DO_NOT_TOUCH` taglar hataya sebep oluyordu.

**Comment by esakarya** [comment]
form oluşturmada sıkıntı olduğunu düşünmüyorum ben python etree html parser ile pars ettirip inputları topluyorum. direk kuveytten gelen 3d form bilgisi bozuk gibi. anlamadım gitti kaç gündür ne bunun için ne iptal iadede dönen 404 sonuc için bi destek alamadık. bulaşılmaması gereken bir banka

**Comment by nuryagdym** [comment]
Ekran goruntuye gore TROY kart ile denemissiniz.
banktan donen HTML form icerigi TROY'da farkli olabilir. 
Surdaki 4 test verisiyle https://github.com/mewebstudio/pos/blob/f1a42a715998a0104cfdc39f0dad6e25ae1680ce/tests/Gateways/KuveytPosTest.php#L256
 sizdeki kod denendiginde  ayni sonuc veriyorsa kodlar ayni sekilde calisiyor demek

**Comment by esakarya** [comment]
bi kontrol edeyim. desteklede görüşmem sürüyor yanıt alabilirsem yazarım inşallah

**Comment by esakarya** [comment]
Destek papağan gibi aynı dökümanı atıp durdu, sonuç alamadım.

**Comment by nuryagdym** [comment]
kutuphane ile ilgili sorun olmadigi icin kapatiyorum
