### ISSUE TITLE
Kuveyt Türk Pos Kurulum Destek

### ISSUE THREAD

**Issue by nzmprlk** [mewebstudio/pos#166]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 0.15.1 |
| Gateway ismi|  KUVEYTTÜRK|
| Banka ismi| KUVEYTTÜRK |

## Sorunuz

Merhabalar codeneigter4 tabanlı e-ticaret websiteme kuveyttürk pos kurulumu yapmak istiyorum.Ama hiç bir form oluşmuyor.Kütüphaneyi composer ile kurdum. Sonrasında githup tests klasörü altındaki kuveyttürktestpos.php dosyasındaki kodları kopyalıyıp posun gözükmesi istediğim dosyaya yazdım **Class "PHPUnit\Framework\TestCase" not found** şeklinde hata alıyorum. Daha öncesinde paytr-iyzico gibi poslar kurmuştum.Bunlar dışındaki herhangi bir pos kurulumu yapamadım. İframe şeklinde bir form dosyası gözükmesi yeterli benim için.Bu işlemi nasıl yapacağımı anlatabilir misiniz?

## Göndermeden önce kontroller

* [ ] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [ ] Dökümantasyonu okudum, araştırdım ve konuyla ilgili bilgileri bulamadım. [dökümantasyon](https://github.com/mewebstudio/pos/blob/master/README.md)
* [ ] İlgili örnek kodları kontrol ettim ve konuyla ilgili bilgileri bulamadım. [örnek kodlar](https://github.com/mewebstudio/pos/tree/master/examples)

**Comment by nuryagdym** [comment]
Merhabal kurulum konusunda yardimci olamam. 

kullanman gereken kodlar `/examples` altinda, `/tests` altinda degil.
