### ISSUE TITLE
3d secure ile kullanımı

### ISSUE THREAD

**Issue by emreakay** [mewebstudio/pos#17]
Merhabalar, Öncelikle elinize sağlık çok güzel bir çalışma olmuş.

3d secure kullanımı için bir dökümantasyon mevcut mu?

Teşekkürler

**Comment by nuryagdym** [comment]
Merhabalar, hangi bankanin? examples/ klasor altinda example kullanimlar var

**Comment by mewebstudio** [comment]
@nuryagdym'nin söylediği gibi örnekler mevcut. Issue'yu kapatıyorum, örneklerle ilgili bir sorunuz olursa tekrar açarsınız @emreakay.
