### ISSUE TITLE
Kuveyt Türk API Versiyon Güncellemesi

### ISSUE THREAD

**Issue by FikretCin** [mewebstudio/pos#172]
Merhabalar;

Kuveyt POS kullanıcılarımıza bankadan gelen maile istinaden bildirmek istedim api v1 kullanımı ocak sonunda son bulacak v2 devreye alınacakmış. Paralel kullanım devam edecek mi bilmiyorum her ihtimale karşı v2 dökümanlarını paylaşmak istedim. Kodlamaya vakit bulup maalesef katkıda bulunamayacağım.

[Non3D Model.pdf](https://github.com/mewebstudio/pos/files/13842703/Non3D.Model.pdf)
[3D Secure Model Kurulum Dokümanı.pdf](https://github.com/mewebstudio/pos/files/13842704/3D.Secure.Model.Kurulum.Dokumani.pdf)
[İptal_İade_Kısmiİade.pdf](https://github.com/mewebstudio/pos/files/13842705/Iptal_Iade_KismiIade.pdf)

Ayrıca şahsi not eklemek isterim 3Ds için zorunlu tuttukları alanlar (il isocode, ülke isocode vs.) gereksiz saçma ve pakedin order objesine müdahale gerektirecek şeyler. 

Kolaylıklar dilerim.

**Comment by nuryagdym** [comment]
Merhabalar, 
Bilgiler icin tesekkurler. 
Evet bu alanlarin 
![image](https://github.com/mewebstudio/pos/assets/26792980/2275da31-3df7-4804-afce-f35b74dfe8cf)
zorunlu olmasi sacma olmus, ama zorunlu derken alanlara gercek deger vermeyi mi kastediyor acaba, yoksa bosh veya sabit degerler gonderebilir miyiz.

Kuveytin entegrasyonu zor. Yurt disindan (bulundum yer) API'larina istek gonderince cevap alamiyorum. Test ortamini yurt disi IP'lerine bloklamislar sanirim. Ayrica test API hesap bilgileri lazim olacak. 

Benim de cok ta baslayasim yok buna :). v1'i bir yayina alayim sonra bakarim, yani Mart'tan once olmayabilir.
Cok bir degisiklik gerektirmiyorsa v1 ile beraber yayina alirim subata kadar

**Comment by nuryagdym** [comment]
Yeni aklima geldi, 15 sene once amerikadayken ben internetten alis veris yaparken Billing adresi zorunluydu, websitede girdigim billing address ile debit karti aldigim bankadaki kayitli adresim uyusmadigi zaman odeme basarisiz aliyordu. Ayni durum olabilir burda da.

**Comment by FikretCin** [comment]
Anladığım kadarıyla request bodyde olması zorunlu ve değerlerinin tespiti de zor örneğin :

`<BillAddrCity>İstanbul</BillAddrCity>`

`<BillAddrCountry>792</BillAddrCountry> // Türkiye yerine ISO 3166-2 kodu`

`<BillAddrLine1>XXX Mahallesi XXX Caddesi No 55 Daire 1</BillAddrLine1>`

`<BillAddrPostCode>34000</BillAddrPostCode>`

`<BillAddrState>34</BillAddrState> İl ISO 3166-2 kodu`

 -- Ek olarak **Ayrica test API hesap bilgileri lazim olacak** her pdf in en alında test apileri ve test kartı olması lazım.

**Comment by mettleshade** [comment]
Merhabalar, sistemlerde bugun itibariyle kesinti yaşanacağı bildirildi ve şuanda bende iptal ve iadede sorun var, RetryCount alanını istiyor ama başka ne istiyor tam tespit edemedim. @nuryagdym @FikretCin

**Comment by nuryagdym** [comment]
gereken guncellemeleri yaptim, ama yurt dusunda oldugumdan ve kuveyt'in IP kisitlamasindan dolayi test edemiyorum.
```sh
composer require symfony/event-dispatcher mews/pos:dev-172-kuveyt-turk-api-versiyon-guncellemesi
```
ile bu branchteki degisiklikleri cekip test eder misiniz.

Not:
1. Bu guncelleme v1.0.0'e eklendi, bu yuzde once kodlarinizi v1.0.0 ile calisacak sekilde guncellemeniz gerekiyor.
2. Kuveyt'a ozel olarak ekstra alanlar istedigi icin bu alanlari kutuphane icine eklemedim, ama isteklerin calismasi icin bu alanlar gonderilmesi gerekiyor. Bunun yerine yeni eklenen `event`'larla bu ozel alanlari ekledim, ekstra alan ekleme ornegini [burda ](https://github.com/mewebstudio/pos/blob/172-kuveyt-turk-api-versiyon-guncellemesi/docs/THREED-PAYMENT-EXAMPLE.md)bulablirsiniz
