### ISSUE TITLE
Ziraat bankasi icin entegre

### ISSUE THREAD

**Issue by MehmetAkcil** [mewebstudio/pos#175]
Ziraat bankasi icin entegre yapmak istiyorum fakat

Isyeri kullanim tipi desteklenmiyor.

seklinde donus aliyorum est pos ile ziraat entegresi yapmaya calistim nasil bir yol izlemeliyim?

**Comment by nuryagdym** [comment]
Merhaba,

1. Ziraatin EstPos (Asseco) alt yapi kullanmaniz gerektiginden emin misin? Ziraatin PayFlex alt yapi destegi de var.
2. Hangi odeme yontemi kullaniyorsun (3D, 3D_PAY, 3D_HOST)?
3. ne tur bir islem yapmaya calisiyorsun?
4. hangi ortamda (test/prod) islem yapmaya calisyorsunuz? Eger test ise, test otram bilgilerini nuryagdy@mustapayev.com eposta'ma gonderir misin.
