### ISSUE TITLE
Ziraat hash hatası 

### ISSUE THREAD

**Issue by esakarya** [mewebstudio/pos#177]
nationalidno bunuda ekledim ama hash uyumsuzluğu devam ediyor haric tutulması gereken daha farklı bişeyler olabilirmi ?

**Comment by nuryagdym** [comment]
#169'da nationalidno yu hash hesaplamadan cikarildi. 

Hash hesaplama ile ilgili baska bir guncelleme yapilmadi, bankadan sorar misin sebebini

**Comment by nuryagdym** [comment]
sorun hala devam ediyor mu?
