### ISSUE TITLE
API isteklere ekstra bilgi eklenmesi

### ISSUE THREAD

**Issue by KeremWho** [mewebstudio/pos#178]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 0.16.1 |
| Gateway ismi| ESTv3 ve PosNet |
| Banka ismi| TEB, İş, YKB |

## Sorunuz

Bir müşterimiz, müşteri takibini bankaların sunduğu sanal pos arayüzü üzerinden yapıyor. Dolayısıyla müşteri ismini bankaya iletmemiz gerekiyor. 3D yönlendirme formuna dışarıdan ekleme yaptığımızda da hash kontrolüne takılıyor dolayısıyla dışarıdan ekleme de yapamıyoruz.

Order arrayine opsiyonel olarak müşteri bilgileri ekleme şansımız mevcut mudur?

## Göndermeden önce kontroller

* [X] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [X] Dökümantasyonu okudum, araştırdım ve konuyla ilgili bilgileri bulamadım. [dökümantasyon](https://github.com/mewebstudio/pos/blob/master/README.md)
* [X] İlgili örnek kodları kontrol ettim ve konuyla ilgili bilgileri bulamadım. [örnek kodlar](https://github.com/mewebstudio/pos/tree/master/examples)

**Comment by nuryagdym** [comment]
Merhabalar, 
Su anlik bu ozellik desteklenmiyor. 
yeni version (v1) uzerinden calisiyorum, orda bu ozelligi ekledim ama henuz biteremedim. Mart ayinda v1'i yayina almayi dusunuyorum.
O zamana kadar acil ise refactoring-08 branch'i kullanarak ekstra bilgiler ekleyebilirsiniz. O branch'te `/docs` altinda nasil yapilacagi ornekleri ekledim.

**Comment by nuryagdym** [comment]
v1.0.0 ile bu ozellik eklendi, orneklere [burdan ](https://github.com/mewebstudio/pos/blob/1.0.0/docs/THREED-PAYMENT-EXAMPLE.md)bakabilirisiniz.
