### ISSUE TITLE
hash ver3

### ISSUE THREAD

**Issue by lansas** [mewebstudio/pos#180]
Merhabalar,

`
$storeKey = "TEST1234";
			$escapedStoreKey = str_replace("|", "\\|", str_replace("\\", "\\\\", $storeKey));	
			$hashval = $hashval . $escapedStoreKey;
			
			$calculatedHashValue = hash('sha512', $hashval);  
			$hash = base64_encode (pack('H*',$calculatedHashValue));
`

Hashv3 geçişine uygun fonksiyonları daha öncesinde yazmış mıydınız?

**Comment by lansas** [comment]
selamlar

$pos->payment(); halen /pos\/src\/Gateways\/EstPos.php e gider, doğru hash değerini tutturabilmesi için son bankadan siparişi sonlandırma esnasında EstV3Pos.php e gitmeli. Yoksa bir yönlendirme yaptınız mı başka?

**Comment by nuryagdym** [comment]
Dediginizi tam olarak anlamadim.

EstPos'u artik kullanmamaniz getekiyor.

pos config array'de **gateway** **EstV3Pos** kullanacak sekilde ayarlanmasi gerekiyor.

**Comment by lansas** [comment]
response.php (gateway'den döndükten sonra çalışacak kod) içeriğindeki php kodu çalıştırdıktan sonra verdiği hata:
  
 Type: Mews\\Pos\\Exceptions\\HashMismatchException; Message: Fatal Error - Hash Mismatch!; File: \/var\/www\/dev1-ws.netonline.net\/etc\/core\/lib\/composer\/mews\/pos\/src\/Gateways\/EstPos.php; Line: 48;"


`require 'config.php';

$order = $session->get('order');

$pos->prepare($order, \Mews\Pos\Gateways\AbstractGateway::TX_PAY);

// Ödeme tamamlanıyor,
// Ödeme modeli (3D Secure, 3D Pay, 3D Host, Non Secure) $account tarafında belirlenir.
// $card değeri Non Secure modelde ve Vakıfbank için 3DPay ve 3DSecure ödemede zorunlu.
try  {
    $pos->payment($card);

    // Ödeme başarılı mı?
    $pos->isSuccess();

    // Sonuç çıktısı
    dump($pos->getResponse());
    // response içeriği için /examples/template/_payment_response.php dosyaya bakınız.
} catch (Mews\Pos\Exceptions\HashMismatchException $e) {
   // todo
}`

**Comment by nuryagdym** [comment]
Bu hatanin sebepleri genelde:
- hatali API bilgileri
- response.php'deki $pos'un ortami hatali ($pos->setTestMode(true/false)). Odeme akisi boyunca ayni kalmasi gerekiyor.

**Comment by lansas** [comment]
selamlar

![image](https://github.com/mewebstudio/pos/assets/1222507/e576fb43-440f-4d62-a3dc-fdcd73e92e2e)

ESTPOS için TROY cart tipi desteği yok mu?

 Type: Mews\Pos\Exceptions\CardTypeNotSupportedException; Message: Fatal Error - Card type is not supported by this gateway!; 
mews/pos/src/Factory/CreditCardFactory.php; Line: 59;

**Comment by nuryagdym** [comment]
Merhabalar, bu bir ayri konu, ayri issue acalim bunun icin.

Payten Dokumantasyonda TROY karti hakkinda bir bilgi olmadigi icin eklenmedi.
Bununla ilgili dokumantasyon bulursaniz, dokumantasyonla beraber PR acabilirsiniz.

**Comment by nuryagdym** [comment]
hash sorunu ile ilgili sorun kalmadi sanirim, issue'i kapatiyorum
