### ISSUE TITLE
Vakıf Katılım

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#181]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu |  |
| PHP versiyonu | 8.1.0 |
| Gateway ismi| createPayFlexAccount-MODEL_3D_PAY |
| Banka ismi| Vakıf Katılım |

### Hatanın özeti

Vakıf Katılım sanal pos;
vakifbank kullanınca Host merchant format is invalid hatası
vakifbank-cp kullanınca : İşlem gerçekleştirilemiyor sorunu var

## Vakıf Katılım Api Dökümanları :
[GuvenliOdemeSayfasiEntegrasyonDokumani.pdf](https://github.com/mewebstudio/pos/files/14228216/GuvenliOdemeSayfasiEntegrasyonDokumani.pdf)
[SanalPOSApiEntegrasyonDokumani.pdf](https://github.com/mewebstudio/pos/files/14228217/SanalPOSApiEntegrasyonDokumani.pdf)
[SanalPOSKullanimKilavuzu.pdf](https://github.com/mewebstudio/pos/files/14228218/SanalPOSKullanimKilavuzu.pdf)

**Comment by nuryagdym** [comment]
Merhabalar, hatalar bu sekilde paylasilmasi guzel, cozumleri de paylastikca internette hatayi aratanlara yardimci oluruz. 

PayFlexV4 classi kullanip ta dener misin

Ise yaramazsa bankaya sorar misin.

**Comment by mettleshade** [comment]
> Merhabalar, hatalar bu sekilde paylasilmasi guzel, cozumleri de paylastikca internette hatayi aratanlara yardimci oluruz.
> 
> PayFlexV4 classi kullanip ta dener misin
> 
> Ise yaramazsa bankaya sorar misin.

Demek istediğinizi tam anlayamadım ama kütüphaneinin example kısmındaki örneklerden kontrol ettim bir eksik göremedim 

```
$account = \Mews\Pos\Factory\AccountFactory::createPayFlexAccount(
                                    $banka,
                                    $username,
                                    $storekey,
                                    $customer,
                                    \Mews\Pos\Gateways\AbstractGateway::MODEL_3D_PAY
                                );
```

**Comment by mettleshade** [comment]
Vakıf Katılım bankasını vakıfbank ile aynı apiye sahip diye düşünüyordum fakat urlleri değişik olduğunu fark ettim, eklemek istediğim banka vakıf katılım @nuryagdym

**Comment by nuryagdym** [comment]
PayFlex'in iki versiyonu var.
Biri PayFlex Ortak Odeme (common payment), digeri ise PayFlex V4 MPI.

Bunlardan biri 3D_PAY destekliyor, digeri 3D_SECURE.

Config ayarlarinda PayFlex veya PayFlexV4 olacak sekilde ayarlayabilirsin

**Comment by nuryagdym** [comment]
O zaman Valif Katilimin dokumantasyonu lazim olacak. En erken Nisan ayi gibi entegre edebilirim diye tahmin ediyorum

**Comment by mettleshade** [comment]
> O zaman Valif Katilimin dokumantasyonu lazim olacak. En erken Nisan ayi gibi entegre edebilirim diye tahmin ediyorum

Dökümanları konuya dahil ettim, ben ekleyemeye çalışacağım başarabilirsem bilgi veririm.

**Comment by nuryagdym** [comment]
Merhabalar, 
Entegrasyon uzerinde calisayim dedim. Vakif Katilim'dan test hesap bilgileri istedim, ancak gondermediler.
Test ortami stabil calismadigini soylediler, musterilerine de prod ortamda test etmelerini tavsiye ediyorlarmis.

Bana duzgun bir Sanal POS sistem gibi gelmedi. 
Zaman buldukca entegrasyon uzerinde calisirim, sonra kutuphane kullanicilari test ettikce hatalari duzeltiriz.

**Comment by nuryagdym** [comment]
Merhabalar,  test ortam bilgilileri varsa espotama gonderebilir misin?

Bu gateway KuveytPos gateway'ne benziyormus, ama biraz farklari var.

**Comment by nuryagdym** [comment]
Merhabalar,

Elimde test ortam bilgileri olmadiginda dokumantasyona gore entegre ettim.
```sh
composer require symfony/event-dispatcher mews/pos:dev-181-vakif-katilim-entegrasyonu
```
ile bu branchteki degisiklikleri cekip test eder misin.

Bana her islem bankadan gelen responselari .txt file icinde hangi istegin response'u oldugun belirterek gonderirsen sevinirim.
Basarili basarisiz fark etmez, hepsinden ornek response isime yarar. Bu response verileri kullanarak testler ekleyecegim.
Istenilen responselar veriler:
- **NonSecure normal odeme** (PosInterface::TX_TYPE_PAY_AUTH) basarili/basarisiz. (ayni siparis ID ile odeme yapmak istedigin banka basarisiz response donmesi lazim).
- **NonSecure on otorizasyon odeme** (PosInterface::TX_TYPE_PAY_PRE_AUTH) basarili/basarisiz. (ayni siparis ID ile odeme yapmak istedigin banka basarisiz response donmesi lazim).
- **NonSecure on otorizasyon kapama** odeme (PosInterface::TX_TYPE_PAY_POST_AUTH) basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- normal odemeli siparis **iptali** basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- normal odemeli siparis **iadesi** basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- **on otorizasyon iptali** basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- **on otorizasyon iadesi** basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- odeme  **durum sorgulama** basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- odeme  **tarihce sorgulama** basarili/basarisiz. (hatali siparis ID gonderince banka basarisiz response donmesi lazim).
- tarih araligiyla **tarihce sorgulama** basarili/basarisiz. (hatali tarih araligi verilince banka basarisiz response donmesi lazim).
- **3DSecure** odeme 3D otorizasyon basarili/basarisiz. (3D sifre sayfasinda hatali sifre veya iptal edersen olusan durum)
- **3DSecure** odeme 3D provizyon basarili/basarisiz. (3D sifre girme islemi basarili olduktan sonra gonderilen istek, provizyon islemi basarisiz duruma getirmek zor olabilir.)
- **3DHost** odeme basarili/basarisiz.

Bankadan gelen API responselari bu satirda: https://github.com/mewebstudio/pos/blob/181-vakif-katilim-entegrasyonu/src/Gateways/VakifKatilimPos.php#L173
```
$response->getBody()->getContents(); // sekilde erisebilirsin
$response->getBody()->rewind(); // ama sonrasinda bu satirida eklemen gerekiyor.
```

Ornek kodlara buralardan erisebilirsin:
https://github.com/mewebstudio/pos/tree/181-vakif-katilim-entegrasyonu/docs
https://github.com/mewebstudio/pos/tree/181-vakif-katilim-entegrasyonu/examples/vakif-katilim



Not: Bu guncelleme v1.0.0'e eklendi, bu yuzde once kodlarini v1.0.0 ile calisacak sekilde guncellemen gerekiyor.
