### ISSUE TITLE
Vakıfbank Hatali Gateway URL (Site is working hatası)

### ISSUE THREAD

**Issue by gorkie** [mewebstudio/pos#186]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 0.16.1  |
| PHP versiyonu | 8.2 |
| Gateway ismi| PayFlex MPI VPOS V4 |
| Banka ismi| Vakıfbank |

### Hatanın özeti

Herkese merhaba, Vakıfbank 3D Ödeme geliştirmesi yapıyoruz. Test ortamında herhangi bir sorun yok. Tüm fonksiyonlar sorunsuz çalışıyor. Ancak production ortamında 3D ödeme callback uygulamaya dönüş yapmıyor. Şifre onayından sonra bizim verdiğimiz callback URL'e yönlendirme yapmak yerine "https://3dsecure.vakifbank.com.tr/" adresine yönlendirme yapıyor ve çıkan ekranda"Site is working" yazıyor. 

`\Mews\Pos\Gateways\AbstractGateway::MODEL_3D_SECURE` kullanıyorum.

Bu durumu ilk olarak Vakıfbank'ta ilgili ekibe sorduk. Cevabı aynen buraya ekliyorum. 

> Merhaba,
> 
> 3D secure post url adresi doğru gönderilmediği için site is working hatası alınmış. Aşağıdaki doğru urle işlem post edilebilir mi?
> 
> 3D secure: https://3dsecure.vakifbank.com.tr/MPIAPI/MPI_Enrollment.aspx  
> 
> Güncel dokümanımız aşağıdadır:
> 
> https://www.vakifbankpos.com.tr/assets/files/VPOS%20724%20_GET724_ENTEGRASYON_DOKUMANI.zip
> 
> Saygılarımızla.

Kütüphaneyi incelediğimde URL'de sadece port farkı bulunuyor. Ancak yinede dökümandaki gibi güncellemek lazım diye düşünüyorum. 

Kütüphanedeki URL : 
`https://3dsecure.vakifbank.com.tr:4443/MPIAPI/MPI_Enrollment.aspx`

Vakıfbank'ın Önerdiği URL : 
`https://3dsecure.vakifbank.com.tr/MPIAPI/MPI_Enrollment.aspx`

### Bağımsız kod veya hatayı yeniden oluşturmanın bir yolu

Production ortamında "PayFlex MPI VPOS V4" gateway kullanarak Vakıfbank 3D ödemesi (`MODEL_3D_SECURE`) denenmesi gerekiyor. 

### Beklenen Sonuç

Production ortamında vermiş olduğumuz success/fail callback url değerine başarılı veya hatalı sonucu post etmesi gerekiyordu.

### Gerçek sonuç

"https://3dsecure.vakifbank.com.tr/" adresine yönlendirme yapıyor ve çıkan ekranda"Site is working" yazıyor. 

<img width="926" alt="Ekran Resmi 2024-02-27 12 42 42" src="https://github.com/mewebstudio/pos/assets/16632488/b3fa0639-3e4c-4ad0-af27-8759791882f9">

## Göndermeden önce kontroller

* [x] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [x] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
Merhabalar,
bildirim icin tesekkurler, guncellemeyi yaparim veya kendiniz de MR acabilirsiniz.

`config/pos.php` dosyayi direk kullanmaniz tavsiye etmem, bu dosya sadece ornek amaclidir.
Kendiniz bir tane olusturup onu kullaniniz.

**Comment by mehmetkalayci** [comment]
@gorkie #184 Buradaki hatayı yapmış olabilir misiniz?

'success_url' => 'BURAYA BANKAYA AİT DEĞİL UYGULAMANIZA AİT KOD GELMESİ GEREKİYOR',
'fail_url' => 'BURAYA BANKAYA AİT DEĞİL UYGULAMANIZA AİT KOD GELMESİ GEREKİYOR',

**Comment by gorkie** [comment]
> @gorkie #184 Buradaki hatayı yapmış olabilir misiniz?
> 
> 
> 
> 'success_url' => 'BURAYA BANKAYA AİT DEĞİL UYGULAMANIZA AİT KOD GELMESİ GEREKİYOR',
> 
> 'fail_url' => 'BURAYA BANKAYA AİT DEĞİL UYGULAMANIZA AİT KOD GELMESİ GEREKİYOR',

Hayır kendimize ait uygulama url'imizi veriyoruz. Hatta bizde success/fail ikiside aynı. Endpoint değiştirerek test edeceğim, sonuçları paylaşırım.

**Comment by gorkie** [comment]
Durumun Vakıfbank kaynaklı eksik tanımlamalardan olduğu anlaşıldı. Konuyu kapatıyorum.
