### ISSUE TITLE
YKB Redis Connect Hatası

### ISSUE THREAD

**Issue by onuryildirimm** [mewebstudio/pos#19]
Merhaba,
YKB Posnet üzerinde işlem yapmaya çalışıyorum. Host üzerinden redis aktif ancak aşağıdaki hatayı alıyorum. Sebebi ne olabilir ? 

Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php on line 10

Fatal error: Uncaught RedisException: php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php:10 Stack trace: #0 /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php(10): Redis->connect('pos_redis', 6379) #1 /home/****/public_html/pos-test/vendor/mews/pos/examples/ykb/3d/_config.php(3): require('/home/****/...') #2 /home/****/public_html/pos-test/vendor/mews/pos/examples/ykb/3d/index.php(3): require('/home/****/...') #3 {main} thrown in /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php on line 10

**Comment by nuryagdym** [comment]
Merhabalar, 
Projeyi docker uzerinden mi ayaga kaldirdiniz? dokumantasyonda docker ile nasil calistiracaginizi aciklanmisti (2-3 adim).
Doker ile calistirmadiysaniz, 
/examples/_main_config.php icinde redis connection bilgilerini ayarlamaniz gerekiyor.

Ayrica hatirladigim kadariyla YKB localhost uzerinden tes t yapamiyoruz, yayinda olan bir sunucu lazim. 
Son tavsiyem ise mumkunse YKB Posnet'ten uzak durun :), dokumantasyonlari cok kotu, guncel degil. web yonetim paneli de doksanlardan kalma.

**Comment by onuryildirimm** [comment]
Birden fazla banka kullanıyoruz ve maalesef ykb yı kullanmak zorundayız :( projeyi direk hostuma yükledim. Hali hazırda posnet hesabımız ip tanımlamalarımız yapılı. Redis ayarlarında ip adresimi yazdığımda refuse hatası almaktayım. Maalesef bir çözüm bulamadım :(

**Comment by nuryagdym** [comment]
refuse dediginiz yukardakiyle ayni hata mi?
eskiden orneklerde PHP session ileydi, ama ben de bankadan geri donuste PHP session sifirlandigi icin redis olarak guncelledim

**Comment by onuryildirimm** [comment]
Fatal error: Uncaught RedisException: Connection refused in /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php:10 Stack trace: #0 /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php(10): Redis->connect('***.***.***.**', 6379) #1 /home/****/public_html/pos-test/vendor/mews/pos/examples/ykb/3d/_config.php(3): require('/home/****/...') #2 /home/****/public_html/pos-test/vendor/mews/pos/examples/ykb/3d/index.php(3): require('/home/****/...') #3 {main} thrown in /home/****/public_html/pos-test/vendor/mews/pos/examples/_main_config.php on line 10

ip adresimi redis e tanımladıktan sonra aldığım hata bu. ip adresi yerine localhost şeklinde tanımlama yapsamda sonuç değişmiyor. hata nerede anlayamadım açıkcası
