### ISSUE TITLE
Kuveyttürk Kısmi Iade : Satış tutarı ile iade tutarı eşleşmemektedir.

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#204]
Kuveyttürk ile 76 tllik bir ödeme yaptım canlıdan, aynı günde iade olmadığı için bir gün bekledim bugün tekrar denedim 30 tl iade etmeyi fakat 

`
Array
(
    [order_id] => 
    [auth_code] => 
    [proc_return_code] => DbLayerError
    [transaction_id] => 
    [currency] => 
    [error_message] => Satış tutarı ile iade tutarı eşleşmemektedir. Değerleri kontrol ediniz.
    [ref_ret_num] => 
    [status] => declined
    [error_code] => TransactionAmountMismatchException
    [status_detail] => 
    [all] => Array
        (
            [DrawBackResult] => Array
                (
                    [Results] => Array
                        (
                            [Result] => Array
                                (
                                    [ErrorMessage] => Satış tutarı ile iade tutarı eşleşmemektedir. Değerleri kontrol ediniz.
                                    [ErrorCode] => TransactionAmountMismatchException
                                    [IsFriendly] => 
                                    [Severity] => BusinessError
                                )

                        )

                    [Success] => 
                    [Value] => Array
                        (
                            [IsEnrolled] => 
                            [IsVirtual] => 
                            [ResponseCode] => DbLayerError
                            [OrderId] => 0
                            [TransactionTime] => 0001-01-01T00:00:00
                            [MerchantId] => 
                            [BusinessKey] => 0
                        )

                )

        )

)
`

sonucunu aldım, readme'de belirtmişsiniz DrawBackResult yerine PartialDrawbackResult kullanıyor diye fakat yukardaki yanıtta DrawBackResult olarak geçiyor

**Comment by nuryagdym** [comment]
Orda yaptigim degisiklikten dolayi.
Eskinde iade icin PartialDrawback kullaniyorduk, Drawback kullanacak sekilde degistirdim.
Drawback tam iade icin, PartialDrawback ise bir kismini iade etmek icin.
Bu tarz durum 2-3 gatewayden karsilastim, ilerde bunun icin ayri TX_TYPE olusturmayi dusunuyorum. Diger gatewaylerde genelde kismi iade ile tam iade arasinda ayrim yok.

Kutuphaneye Partial refund destegi ekleninceye kadar, kismi iade yapilmak istendiginde docs/ altindaki orneklerde oldugu gibi eventListener kullanarak Drawback degeri PartialDrawbacke degistirerek cozebilirsin.

**Comment by nuryagdym** [comment]
kutuphane kodunu degistirmemeni tavsiye ederim, kutuphaneyi guncellediginde bu yaptiginde degisiklikler silinir.
event listener ile kutuphane kodunu degistirmeden TransactionType'i degistirebilirsin.
Bu ornek calismasi lazim:

```php
/** @var \Symfony\Component\EventDispatcher\EventDispatcher $eventDispatcher */
$eventDispatcher->addListener(
    \Mews\Pos\Event\RequestDataPreparedEvent::class,
    function (\Mews\Pos\Event\RequestDataPreparedEvent $event) {
       //istersen burda original tutar ile refund edilmek istenen tutarlari karsilastiririp ona gore bu alttaki kodlari calistirabilirsin:
        $requestData                                   = $event->getRequestData();
        $requestData['VPosMessage']['TransactionType'] = 'PartialDrawback';
        $event->setRequestData($requestData);
    });
   $pos->refund($order);
```
`$eventDispatcher` $pos istance'i  olusturmakta kullandiginin aynisi.

**Comment by mettleshade** [comment]
Attığınız kodu ekledim 
AbstractGateway.php 315'inci satıra
`file_put_contents('a2.txt',json_encode($data));`
kodunu ekledim bankaya giden datayı görmek için kod doğru şekilde gidiyor fakat halen iade olarak dönüş yapıyor banka.
KuveytPosRequestDataMapper.php dosyasında direk değiştirdiğim zaman kısmi iade oluyor nerde neyi atlıyorum çözemedim :)

**Comment by mettleshade** [comment]
@nuryagdym sorunu buldum, KuveytPos.php dosyasında sendSoapRequest kullanılarak atılıyor bu istek
265. satırda 
`$result = $client->__soapCall($this->requestDataMapper->mapTxType($txType), ['parameters' => ['request' => $contents]]);`
kodundaki $this->requestDataMapper->mapTxType($txType) 'Drawback' olarak geçiyor, $contents'te PartialDrawback olsada banka Drawback olarak görüyor

**Comment by nuryagdym** [comment]
anladim, unuttum burasini, o zaman KuveytPosRequestDataMapper'de Drawback'i PartialDrawback'e degistirmen gerekecek.

Bu issue acik kalsin, partial refund uzerinde musait oldugumda calisirim

**Comment by nuryagdym** [comment]
@mettleshade **PartialDrawback** ile tam iadeyi yapabiliyor muyuz?
kontrol eder misin

**Comment by mettleshade** [comment]
@nuryagdym olmuyor daha öncedende denemiştim ama şimdi tekrar denedim
![Screenshot_10](https://github.com/mewebstudio/pos/assets/51230161/f9188193-6cf4-4c23-b196-65163f13d8d4)

**Comment by nuryagdym** [comment]
@mettleshade bendeki test ortam bilgileri calismamaya basladi.
Aklima bir cozum geldi ama test ortam bilgileri calismadigi icin test edemiyorum.
Bu yuzden sana anlatayim sen dener misin.
Yapman gereken degisiklikler:
1. https://github.com/mewebstudio/pos/blob/e1733994ff052d7eeac0f2808bfabaacf22fe0c7/src/Gateways/KuveytPos.php#L263 bu satir su sekilde degisecek: `$result = $client->__soapCall($contents['VPosMessage']['TransactionType'], ['parameters' => ['request' => $contents]]);`
2. refund kod su sekilde olacak
```php
    /** @var \Symfony\Component\EventDispatcher\EventDispatcher $eventDispatcher */
    $eventDispatcher->addListener(
      \Mews\Pos\Event\RequestDataPreparedEvent::class,
      function (\Mews\Pos\Event\RequestDataPreparedEvent $event) {
         //istersen burda original tutar ile refund edilmek istenen tutarlari karsilastiririp ona gore bu alttaki kodlari calistirabilirsin:
          $requestData                                   = $event->getRequestData();
          $requestData['VPosMessage']['TransactionType'] = 'PartialDrawback';
          $event->setRequestData($requestData);
      });
     $pos->refund($order);
 ```


Eger yukardaki degisiklikler calisirsa, ayrica ustteki degisikliklere ek olarak bu satiri da silip dener misin https://github.com/mewebstudio/pos/blob/e1733994ff052d7eeac0f2808bfabaacf22fe0c7/src/DataMapper/RequestDataMapper/KuveytPosRequestDataMapper.php#L328

**Comment by mettleshade** [comment]
@nuryagdym En kısa zamanda deneyip dönüş yapıyorum.

**Comment by mettleshade** [comment]
@nuryagdym ilk 2 adımı yaptım başarılı, 3. adımı TransactionType sildim yine bir sıkıntı yok güncellemeye eklenebilir.

**Comment by nuryagdym** [comment]
v1.3.0 kismi iade destegi ekledim.
event listenere gerek yok.
refund order verisine ekstra olarak `order_amount` degeri eklenmesi gerekiyor.
yani
- `amount` degeri eskisi gibi iade edilecek tutar olacak.
- `order_amount` ise siparisin tutari olacak. 
- 
- Kutupahen ikisi arasinda karsilastirma yaparak tam iade mi, kismi iade mi olduguna karar verecek.
