### ISSUE TITLE
EstPos TROY kart destegi

### ISSUE THREAD

**Issue by nuryagdym** [mewebstudio/pos#205]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 1.1.0  |
| PHP versiyonu |   |
| Gateway ismi|  EstPos |
| Banka ismi|  |

### Hatanın özeti

TROY kart denenince kutuphane hata veriyor

### Beklenen Sonuç

Payten banka dokumanlarinda TROY kart icin hangi `cardType` degeri gonderilmesi gerektigini yazmiyor.
Payten destegine sordum, cardType parametre zorunlu degil dediler:

![image](https://github.com/mewebstudio/pos/assets/26792980/a3db0fca-dda3-491b-b914-ad0b94c1f541)

Cozum olarak cardType degeri EstPos icin kaldirabiliriz.

@mettleshade

**Comment by mettleshade** [comment]
Teşekkürler, deneyip size olumlu olumsuz dönüş yapacağım.

**Comment by mettleshade** [comment]
@nuryagdym 
`                        $card = \Mews\Pos\Factory\CreditCardFactory::createForGateway(
                            $pos,
                            strval($kartno),
                            strval($yil),
                            strval($gun), 
                            strval($cvc),
                            strval($isim)
                        );`
                        
                        şeklinde yolladım bütün kart tiplerini tanımamaya başladı bende direk 3 olarak troy kartı ekledim kütüphaneye

**Comment by nuryagdym** [comment]
bununla ilgili guncelleme yaptim, bir sonraki versiyonda yayina alirim, est pos card type zorunlu degil dedi, o yuzden cardType'i EstPosRequestDataMapper'den kaldiraracagim

**Comment by nuryagdym** [comment]
@mettleshade cardType degerleri kaldirdim.
Yayina almadan once production testi yapabilirsek guzel olur.

Lokalindeki EstPosRequestDataMapper.php
icerigini burdakiyle degistirip odeme yapmayi dener misin
https://github.com/mewebstudio/pos/blob/master/src/DataMapper/RequestDataMapper/EstPosRequestDataMapper.php

TROY ve diger kartlar'la deneyebilirsen guzel olur.

**Comment by mettleshade** [comment]
@nuryagdym kart tipini sorun etmedi ama kart benim olmadığı için ödemeyi gerçekleştirmedim sms ekranına girdim çıktım bir sorun yok, kütüphaneye güncelleme çıkınca tam deneriz
