### ISSUE TITLE
Yapıkredi 3D Hatası

### ISSUE THREAD

**Issue by xenophan3s** [mewebstudio/pos#206]
Örnek kodları kullanırken yapıkredi 3D aşamasında https://setmpos.ykb.com/3DSWebService/YKBPaymentService bu URL açılıyor ve sadece bir resim gözüküyor. Non secure ise success dönüyor.  Sebebini anlayamadık. Eğer bilginiz varsa yardımcı olursanız sevinirim.

**Comment by nuryagdym** [comment]
Merhabalar, test ortamda kullanilacak test kart bilgileri varsa epostama gonderir misiniz.

Bendeki test kartin suresi gectigi icin yapikrediyi test edemiyorum.

**Comment by nuryagdym** [comment]
Kredi kart bilgileri icin tesekkurler, bendeki test hesap bilgileri de calismiyor sanirim, NON secure odeme basarisiz 0148 UNAUTHORIZED REQUEST hatasi aliyorum.

3D odemede deiginiz gibi bende de bosh sayfa acildi:
![image](https://github.com/mewebstudio/pos/assets/26792980/91a38bff-dfaf-438b-994c-7043ae9cddd6)

Sorunun nerede oldugunu bankadan ogrenmemiz gerekiyor. 
Burdaki:
https://github.com/mewebstudio/pos/blob/e1733994ff052d7eeac0f2808bfabaacf22fe0c7/src/Gateways/PosNet.php#L248
 `$xml` degerin icerigini bankaya gonderip burda ne sorun oldugu sorar misin. 
Bunun icerigini https://setmpos.ykb.com/PosnetWebService/XML bu adrese POST ediyoruz, sonra bankaden gelen cevabi HTML forma basip bankaya (yani https://setmpos.ykb.com/3DSWebService/YKBPaymentService) yonlendirme  yapiyoruz.
Yani bankadan aldigimiz veriyi tekrar bankaya gonderiyoruz, neden kendi verdikleri veriyi kabul etmiyorlar bilemedim.

**Comment by nuryagdym** [comment]
guncel test ortam varsa, espotama gonderirseniz sevinirim

**Comment by devmdeniz** [comment]
Yapı Kredi'nin 3D ekranı bende sıkıntısız bir şekilde çalıştı. SMS doğrulamasını yapamadığım için bir sonraki evreye geçemedim ama test kartlarıyla denediğim için SMS doğrulamasını başarılı bir şekilde gönderdiğini iddia eden kısma kadar geldim.

**Comment by esakarya** [comment]
Yapı kredi non securede başarılı olan varmı ? aşağıdaki hata dönüyor. requesttde OrderId olmayacak dediler kaldırdım gene aynı.
Ve destek ekibi bana hata dönmesine dağmen istek yok diyor. ilginç bi durum

<?xml version='1.0' encoding='iso-8859-9'?>
<posnetResponse>
    <approved>0</approved>
    <respCode>0666</respCode>
    <respText>Teknik Hata</respText>
</posnetResponse>

**Comment by esakarya** [comment]
OrderId nin D si büyük olcak mış arkadaşlar :)

**Comment by nuryagdym** [comment]
bendeki dokumantasyonda `orderID` sekilde gonderilecek diye belirtilmis. 
Kodda da o sekilde gonderiliyor.
