### ISSUE TITLE
EstPos : Undefined array key "AuthCode"

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#207]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 1.1.0  |
| PHP versiyonu |  |
| Gateway ismi| EstPos |
| Banka ismi| Ziraat Bankası |

### Hatanın özeti
Yeni ödeme yaparken, iade ve iptal yaparken bazı siparişlerde 
Undefined array key "AuthCode" hatası alıyorum

### Bağımsız kod veya hatayı yeniden oluşturmanın bir yolu
Oluşturulan siparişin iptali veya iadesi

**Comment by nuryagdym** [comment]
burda https://github.com/mewebstudio/pos/blob/e1733994ff052d7eeac0f2808bfabaacf22fe0c7/src/DataMapper/ResponseDataMapper/EstPosResponseDataMapper.php#L288 $rawResponseData icerigini paylasir misin, bendeki test ortam bilgileri nedense calismamaya basladi

**Comment by mettleshade** [comment]
@nuryagdym mailden ilettim.

**Comment by nuryagdym** [comment]
tesekkurler, yeni yakinda yeni release'de bu hatayi ele alacagim. 
Iptal veya iade basarili oldugunda sorun yasamaman gerekiyor. 
Basarisiz durumda bu hatayla karsilasiyosundur.

**Comment by mettleshade** [comment]
aslında ilk iptalden alıyorum bu hatayı yani sipariş oluşur oluşmaz iptal etmiş müşteri iadeyi atmış ama sonuç doğru gelmemiş bu hataya düşmüş

**Comment by nuryagdym** [comment]
ama gonderidigin veride "İptal edilmeye uygun satış işlemi bulunamadı." hata mesaji var. belki 2 kere iptal yapilmaya calisilmistir.
Iptal edilmis islemi tekrar iptal etmek istersen bu hata olusuyordur.

**Comment by mettleshade** [comment]
Müşteri siparişini iptal etmiş normalde iade edilip siparişe yansır ödeme iade edildi diye ama yazmadığı için ben deniyorum ben denediğimdede bu hatayı atıyor yani müşteri ilk yaptığında ödemeyi iade etmiş

**Comment by nuryagdym** [comment]
Ilk musteri iade islemi yapildiginda neden senin tarafinda basarisiz oldugunu anlamam icin $rawResponseData icerigi lazim.

`AuthCode` undefined index sorunu icin guncelleme yaptim, ama bu asil sorununu cozmez. 
Asil sorun neden ilk denemede iade basarili olarak gosterilmedi. 

Ayrica siparisin son durumuny ogrenmek icin `$status = $pos->status()` kullanabilirsin.
ornegin 
- odeme basarili oldugunda `$status['order_status'] === PosInterface::PAYMENT_STATUS_PAYMENT_COMPLETED` olur,
- odeme iptal edildiginde `$status['order_status'] === PosInterface::PAYMENT_STATUS_CANCELED`
- iade edildiginde ise  `$status['order_status'] === PosInterface::PAYMENT_STATUS_PAYMENT_COMPLETED` donuyor, bunun normalde PAYMENT_STATUS_FULLY_REFUNDED olmasi gerekiyor, ama banka response'na gore neyden refund oldugunu anlayacagimi cozemedi

**Comment by mettleshade** [comment]
Şuanda net olarak sipariş iptalinde farklı bir hata aldım
`Undefined array key "ERRORCODE" - Satır : 273`

**Comment by nuryagdym** [comment]
$rawResponseData icerigini gondermen mumkun mu?

**Comment by mettleshade** [comment]
@nuryagdym AuthCode için tam log ilettim, iptal hatasını logluyorum olunca göndereceğim

**Comment by nuryagdym** [comment]
@mettleshade 420iadeodemelog.txt isimle son gonderdigin dosyada `refund()` isleminde bankadan gelen cevapmi?

**Comment by mettleshade** [comment]
@nuryagdym evet

`    public function mapRefundResponse(array $rawResponseData): array
    {
        file_put_contents(rand(0,1500).'iadeodemelog.txt',json_encode($rawResponseData));
        /** @var PaymentStatusModel $rawResponseData */
        $rawResponseData = $this->emptyStringsToNull($rawResponseData);
        $procReturnCode  = $this->getProcReturnCode($rawResponseData);
        $status          = self::TX_DECLINED;
        if (self::PROCEDURE_SUCCESS_CODE === $procReturnCode) {
            $status = self::TX_APPROVED;
        }

        return [
            'order_id'         => $rawResponseData['OrderId'],
            'group_id'         => $rawResponseData['GroupId'],
            'auth_code'        => $rawResponseData['AuthCode'],
            'ref_ret_num'      => $rawResponseData['HostRefNum'],
            'proc_return_code' => $procReturnCode,
            'transaction_id'   => $rawResponseData['TransId'],
            'num_code'         => $rawResponseData['Extra']['NUMCODE'],
            'error_code'       => $rawResponseData['Extra']['ERRORCODE'],
            'error_message'    => $rawResponseData['ErrMsg'],
            'status'           => $status,
            'status_detail'    => $this->getStatusDetail($procReturnCode),
            'all'              => $rawResponseData,
        ];
    }`

**Comment by nuryagdym** [comment]
@mettleshade bilgileri icin tesekkurler, gereken duzeltmeleri yaptim.

Yayina alincaya kadar EstPosResponseDataMapper.php'de degisiklikleri manuel yapabilirsin.
https://github.com/mewebstudio/pos/pull/208/files#diff-667e940cbf15f7852b9478d156df7f06e78ec830f5c50b029a81327751a0b923

**Comment by mettleshade** [comment]
@nuryagdym ne demek sizin yaptıklarınız yanında hiç bişey. iptal ile log ilettim.

**Comment by mettleshade** [comment]
@nuryagdym Undefined array key "GroupId" - Satır : 269 yeni bir hata yakaladım mailden logu ilettim.

**Comment by nuryagdym** [comment]
@mettleshade  groupId sorunu da ele alindi

**Comment by mettleshade** [comment]
şuan başka bir eksikle karşılaşmadım karşılaşırsam konuya eklerim
