### ISSUE TITLE
Garanti Dns Sorunu

### ISSUE THREAD

**Issue by lutfuahmet** [mewebstudio/pos#21]
Merhabalar;

3d secure yönlendirmesinden (https://sanalposprovtest.garanti.com.tr/servlet/gt3dengine) sonra şöyle bir url ye gönderiyor.

https://3dsecurepit.garanti.com.tr/acs/0038243730558395871310004398/merchant/control/master

dns çözülmediğinden hata veriyor.

**Comment by nuryagdym** [comment]
Merhabalar, Garanti desteginden sormayi denediniz mi?
Bu yonlendirmeyi bu kutuphane yapmiyor, Garanti tarafindan yapilan bir yonlendirme

**Comment by lutfuahmet** [comment]
ilginiz için teşekkürler.

Garanti destek 3d için geçerli test kartlarını gönderdi.

Kartlar alacakları MD status ve host cevapları aşağıdaki şekilde;

 

Status :00

MD status 1

 

4282**//2090**//0434**//8015

Vade 0822 cvv 123

 

3756**//2200**//5485**//014

Vade 1025 cvv 123
