### ISSUE TITLE
EstPos Payten Hash Versiyon 3 Güncellemesi

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#210]
Ziraat Bankası Hash Versiyon 3 Hakkında
Değerli Üye İşyerimiz,
Üye İşyerlerinden gelen talep üzerine, tarafınızca uyumlanması beklenen hash algoritmasında yapılacak değişiklik için son tarih 31 Temmuz 2024 olarak güncellenmiştir. Bu tarih PCI DSS 4.0 uyumlanma şartlı alınmış tarihtir ve ötelenmeyecektir.
PCI DSS 4.0 ile uyumsuzluk ve riskler içerdiğinden tüm işyerlerimizin "hash ver3" yapısına geçmeleri gerekmektedir. Hash ver3'e geçiş için tarafınızda kod değişikliği gerektirdiğinden, öncelikle test ortamları üzerinden denemeler gerçekleştirmenizi, daha sonra da canlı ortama geçiş yapmanızı bekliyoruz.
31 Temmuz 2024 tarihinden itibaren Hash ver3 ya da ver2 yapısına uyumlanmayan iş yerlerinin 3D Secure işlemleri kesilecektir. Bu tarihe kadar tüm versiyonlar kullanımda kalacaktır. Bu tarihten sonra sadece Hash ver2 ve ver3 algoritmaları üzerinden işlem yapabileceksiniz.
Hash ver3 için entegrasyonunuzda kullanabileceğiniz gerekli entegrasyon dokümanlarını ekte paylaşıyoruz. Dokümanı inceledikten sonra oluşabilecek sorularınız için....

Saygılarımızla,
İyi çalışmalar.

Payten
[Uploading Hash ver3 Sample Codes (1).zip…]()

**Comment by mettleshade** [comment]
mailden ilettim arşivi, şuanda kullanmıyorumda hesapta uyarı şeklinde eklemişler bende bildirmek istedim.

**Comment by berkansahin** [comment]
Merhaba banada aynı içerikli bir mail ulaştı iş bankası tarafından aynı güncellemeyi içeriyor diye düşünüyorum doğru mu acaba ?

<img width="639" alt="Screenshot 2024-08-05 at 03 10 01" src="https://github.com/user-attachments/assets/0552a3d3-70fc-405e-8282-835fc03d822b">

**Comment by nuryagdym** [comment]
Merhaba, evet iceriyor
