### ISSUE TITLE
ykb ve estpos hata veriyor

### ISSUE THREAD

**Issue by faguvenli** [mewebstudio/pos#22]
merhaba hocam. uzun süredir kodlarınızı kullanıyorum. ellerinize sağlık müthiş bir çalışma.
bir problemim var
geçenlerde sistemimizi amazona taşıdık. o gün itibarıyla yapıkredi ve estpos modülleri hata vermeye başladı
yapıkredide 
vendor/mews/pos/src/PosNet.php:324
Trying to get property 'approved' of non-object
hatası verirken estpos'ta da tx-data ile ilgili bir hata veriyor.
bu hataları kullanıcı telefona gelen şifreyi girdikten sonra veriyor.
servere mcrypt kurdum fakat sorun düzelmedi.
konuyla ilgili yardımcı olabilir misiniz?
Not: Finansbank sorunsuz çalışıyor.

**Comment by nuryagdym** [comment]
Merhabalar, _v0.4.0_ dener misiniz, orda `mcrypt` kaldirilmisti.
O da calismazsa son _v04.5_ versiyonu bir dener misiniz?
Son versiyonda sorun var ise cozelim, onceki versiyonlarda destek olamiyorum

**Comment by faguvenli** [comment]
problem yaşadığım version zaten v04.5 hocam.
test etmek için v0.4.0 ile deneyeceğim. gelişmeleri yazıcam.

**Comment by nuryagdym** [comment]
v0.4.5'de _vendor/mews/pos/src/PosNet.php bu dosya yok, o yuzden kullandiginiz versiyon v0.4.5 olamaz

**Comment by faguvenli** [comment]
ben yanlış yazmışım kusura bakmayın hocam
Yapıkredi'nin verdiği hata: 
[2021-03-30 19:15:35] local.ERROR: Trying to get property 'approved' of non-object {"userId":2,"exception":"[object] (ErrorException(code: 0): Trying to get property 'approved' of non-object at ... /vendor/mews/pos/src/Gateways/PosNet.php:582)
[stacktrace]


Garanti bankası ve Finansbank yeni pos sorunsuz çalışıyor.

akbank, iş bankası, ziraat bankası da aşağıdaki hatayı veriyor:
[2021-03-30 19:31:44] local.ERROR: Undefined index: txstatus {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined index: txstatus at ... /vendor/mews/pos/src/Gateways/EstPos.php:492)
[stacktrace]

**Comment by nuryagdym** [comment]
test ortami bilgilerini paylasmaniz mumkun mu? 
direk bakarak sorunu bulmam zor olur. test ortami bilgileri bende yok

**Comment by nuryagdym** [comment]
isterseniz teamviewer ile baglanayim beraber bakalim

**Comment by faguvenli** [comment]
Mustafa hocam desteğin için çok teşekkür ederim.
Çalışmalarınızda başarılar dilerim.

**Comment by faguvenli** [comment]
> 

o hata su anda bende de var. yapıkrediyle çekim yapamıyorum malesef. incelemek için vakit de bulamadım.

**Comment by erenilhan** [comment]
ben biraz baktım muhtemelen decrypt/encrypt yapamadığı için approved e erişemiyor.

Eğer çözüm bulursam sizle de paylaşırım.
