### ISSUE TITLE
YapıKredi The requested URL was rejected

### ISSUE THREAD

**Issue by husmen73** [mewebstudio/pos#223]
Merhaba,

Test ayarlarım şu şekilde;

> 'yapikredi' => [
>             'gateway_class'     => \Mews\Pos\Gateways\PosNet::class,
>             'test_mode'         => true,
>             'lang'              => \Mews\Pos\PosInterface::LANG_TR,
>             'credentials'       => [
>                 'payment_model' => \Mews\Pos\PosInterface::MODEL_3D_SECURE,
>                 'merchant_id'   => '6706598320',
>                 'terminal_id'   => '67005551',
>                 'user_name'     => '9644',
>                 'enc_key'       => '10,10,10,10,10,10,10,10',
>             ],
>             'gateway_endpoints' => [
>                 'payment_api' => 'https://setmpos.ykb.com/PosnetWebService/XML',
>                 'gateway_3d' => 'https://setmpos.ykb.com/3DSWebService/YKBPaymentService',
>             ],
>         ],

        
Oluşturulan form submit edildikten sonra açılan sayfada şu hatayı alıyorum:

Hata Sayfası: https://setmpos.ykb.com/3DSWebService/YKBPaymentService

> The requested URL was rejected. Please consult with your administrator.
> 
> Your support ID is: 103537322291734628
> 
> [[Go Back]]

Test kredi kartı bulamadım. Başka yerden bulduğum bir kaç kart ile denedim aynı sonucu aldım. Sorun nedir çözemedim maalesef, destek istemek zorunda kaldım.

**Comment by nuryagdym** [comment]
Merhabalar,
#206 ile ayni hata olabilir. 
Elimde gecerli test ortam bilgileri ve kredi kart bilgileri olmadan destek olamiyorum. 

Bankayla iletisime gecmeniz gerekiyor

**Comment by husmen73** [comment]
merchantURL'de local adres olmaması gerekiyormuş. IP tanımlaması falan yaptırdık test ortamı için, düzeldi. 

Ancak şu an aşağıdaki hatayı alıyorum banka response'unda.

> 'Undefined array key "procreturncode"'

Başka detay gerekli mi?

**Comment by husmen73** [comment]
Bu sorun tamamen banka ile çözülmesi gereken durummuş. Bankadan test server ip'si için yetkilendirme yaptırdık ve gönderdikleri test kartlarını kullandık. Başarılı bir şekilde yapı kredi çalışıyor. Test ortamı için bile local ip adresi istemiyorlar merchantReturnURL'de.

**Comment by nuryagdym** [comment]
Merhabalar, 
merchantReturnURL'i kaldirip test ortaminda odeme dendim  **E150 - Geri Dönüş adresi null ya da boş olamaz** hatasi aldim.

Mumkunse test ortam bilgileri ve kart bilgileri epostama atar misin ce.nuryagdy@gmail.com

**Comment by husmen73** [comment]
Test bilgilerini göndermem birşey ifade etmeyecek. Şirkete ait sanalpos için test ortam bilgileri hazırlıyor sanırım, çünkü öncesinde bizden terminal bilgilerimiz falan istediler.

Localde test yapılamaz. İlk istek içerisinde local ip adresi kesinlikle olmayacak ve test serverından istek yapmadan önce server ip'sini izinli listeye eklemelerini istemek gerekiyor.

**Comment by nuryagdym** [comment]
Anladim, PosNet kodlarda her hangi bir degisiklige gerek var mi?

**Comment by husmen73** [comment]
Ben kendi ihtiyacıma göre düzenlemesini yaptım. Çoklu pos (garanti, yapıkredi, işbank) kullanıyorum. Normal şartlarda ödeme işlemi tamamlanıyor. Değişikliğe gerek yok. Yapıkredi için geliştiricilerin test ortamı için ip tanımlatması ve yaptıkları isteklerde lokal adres kullanmamaları yeterli olur. Bilgi olarak dursun burada da.

**Comment by husmen73** [comment]
İptal ve iade işlemlerini yapmadım. Şunları denemiş miydin?

> ProvUserID                                : PROVAUT / PROVRFN / PROVOOS
> ProvisionPassword                    : 123qweASD/

**Comment by nuryagdym** [comment]
PROVOOS ne icin oldugunu bilmiyorum, ama digerlerini kullandim.

**Comment by nuryagdym** [comment]
Ben de anlamadim sebebini, tekrar denedim acik ise neden bu hatayi aliyorum.
1-2 ay onceye kadar iptal iade calisiyordu, son zamanlar calismiyor

**Comment by husmen73** [comment]
Şu an bende de 

> "proc_return_code" => "05"

dönüyor normal ödeme yaparken. Muhtemelen servislerinde hata var şu an.
