### ISSUE TITLE
Backend API 3D Ödeme

### ISSUE THREAD

**Issue by Smokietr** [mewebstudio/pos#225]
Paketi yeni kullanacağım biraz göz gezdirdim ama bununla ilgili bir şey göremedim. Storage session driver yerine database yapılabilir mi ? Birde redirect URL'lerini yani front end'e backend serverdan dönebileceğimi URL yapısı var mı ?

**Comment by nuryagdym** [comment]
Ornek kolayligi icin session storage tercih edildi, istediginiz medium'da storage edebilirisiniz.

success url ve fail url diyorsaniz order datasi icinde kutuphane saglamaniz gerekiyor, sonra $pos->get3DFormData() ile aldiginiz form verisi icinde bu URL'lar yer alir.

**Comment by nuryagdym** [comment]
@mewebstudio abi https://github.com/mewebstudio/pos/graphs/community burdan discussion'lari acabilir misin, issue olmayan konular icin issue aciliyor.
