### ISSUE TITLE
vakıfbank query api değişimi

### ISSUE THREAD

**Issue by sekizlipenguen** [mewebstudio/pos#229]
Selamlar,
vakıfbank 

 'query_api' => 'https://sanalpos.vakifbank.com.tr/v4/UIWebService/Search.aspx', adresi kullanılmıyor 
 adresini 
 
                 'query_api' => 'https://onlineodeme.vakifbank.com.tr:4443/UIService/Search.aspx',
                 
                 ile değiştirmen gerekiyor.
                 
                 
ayrıca şu bölümde hata veriyor.

$defaultResponse['first_amount']     = $this->formatAmount($txResultInfo['CurrencyAmount']); bölümü Amount olarak değiştirilmeli.

ben geçici sonuç için böyle yaptım ancak senin bunu düzeltmen çok önemli. Diğer bankalara devam ediyorum
**PayFlexV4PosResponseDataMapper**

array:24 [ // vendor/mews/pos/src/DataMapper/ResponseDataMapper/PayFlexV4PosResponseDataMapper.php:180
  "PaymentTransactionId" => "gizlendi"
  "TransactionType" => "Sale"
  "TransactionId" => "gizlendi"
  "OrderId" => "gizlendi"
  "Amount" => "0.25"
  "AmountCode" => "949"
  "AuthCode" => "gizlendi"
  "ReferenceTransactionId" => "gizlendi"
  "IsCanceled" => "false"
  "IsReversed" => "false"
  "IsRefunded" => "true"
  "TotalRefundAmount" => "0.25"
  "ECI" => "05"
  "CAVV" => "gizlendi="
  "ResultCode" => "0000"
  "Rrn" => "gizlendi"
  "HostDate" => "gizlendi"
  "ResponseMessage" => "İŞLEM BAŞARILI"
  "HostResultCode" => "000"
  "IsBatchClosed" => "false"
  "TransactionThreedSecureType" => "Secure"
  "PanMasked" => "gizlendi****gizlendi"
  "RequestInsertTime" => "2024-08-12T12:03:04.98"
  "CustomItems" => array:1 [
    "CustomItem" => array:2 [
      "Name" => "CardHolderName"
      "Value" => "gizlendi* gizlendi*"
    ]
  ]
]

**Comment by nuryagdym** [comment]
Merhaba, teseskkurler, vakifbankla ilgili baska sorun var mi?

**Comment by nuryagdym** [comment]
Mumkunse Vakifbank'tan guncel salan pos dukmanlarini isteyip paylasir misin.

Bendeki dokumanlarda her yerde **CurrencyAmount** olarak geciyor.

**Comment by sekizlipenguen** [comment]
Selamlar,

sana mail olarak atıyorum vakıfbank böyle iletmiş bize. Bu arada ziraat bank ödeme alıyor ancak hata veriyor onu da atıcam birazdan sana.

**Comment by sekizlipenguen** [comment]
Selamlar,

https://www.vakifbankpos.com.tr/assets/files/VAKIFBANK%20ENTEGRASYON%20DOKUMANLARI.zip

bu doküman bize: Thursday, June 6, 2024 8:37 PM gelmiş

*Murat DEMİRFull Stack Developer*


nuryagdym ***@***.***>, 12 Ağu 2024 Pzt, 13:13 tarihinde şunu
yazdı:
