### ISSUE TITLE
ziraat bank ödeme hata işlemi

### ISSUE THREAD

**Issue by sekizlipenguen** [mewebstudio/pos#230]
#message: "Failed to parse time string (0812134015) at position 7 (0): Unexpected character"
  #code: 0
  #file: "
/mews/pos/
src/DataMapper/ResponseDataMapper/PayFlexV4PosResponseDataMapper.php"

şeklinde hata dönüyor.

sorun şurada başlıyor.

PayFlexV4PosResponseDataMapper.php 212 satır

 $commonResponse['transaction_time'] = new \DateTimeImmutable($rawPaymentResponseData['HostDate']);
 
 $rawPaymentResponseData dönen sonuç aşağıdaki gibidir;
 
 
array:19 [▼ // vendor/mews/pos/src/DataMapper/ResponseDataMapper/PayFlexV4PosResponseDataMapper.php:211
  "MerchantId" => "gizlendi"
  "TransactionType" => "Sale"
  "TransactionId" => "gizlendi"
  "ResultCode" => "0000"
  "ResultDetail" => "İŞLEM BAŞARILI"
  "InstallmentTable" => null
  "CampaignResult" => null
  "AuthCode" => "gizlendi"
  "HostDate" => "0812134340"
  "Rrn" => "gizlendi"
  "TerminalNo" => "gizlendi"
  "CurrencyAmount" => "0.25"
  "CurrencyCode" => "949"
  "OrderId" => "gizlendi"
  "ECI" => "05"
  "ThreeDSecureType" => "2"
  "TransactionDeviceSource" => "0"
  "BatchNo" => "2023"
  "TLAmount" => "0.25"
]

  "HostDate" => "0812134340" buradaki değeri new \DateTimeImmutable($rawPaymentResponseData['HostDate']) ile çözemiyoruz ancak ödeme başarılı oluyor dediğim gibi, bunu da hızlıca çözebilir miyiz ben bu alanı commit ile geçici kapadım sorun çözüldü.

**Comment by nuryagdym** [comment]
ziraat hala payflex API'i sagliyor mu? en son Payten'i kullaniyordu diye hatirliyorum.

**Comment by sekizlipenguen** [comment]
> ziraat hala payflex API'i sagliyor mu? en son Payten'i kullaniyordu diye hatirliyorum.

ziraat-vpos olarak şunu kullanıyoruz. eski yapında da bu yok muydu 1.4 geçiriyorum her şeyi de?

 'ziraat-vpos' => [
            'name' => 'Ziraat Bankası',
            'class' => Mews\Pos\Gateways\PayFlexV4Pos::class,
            'gateway_endpoints' => [
                'payment_api' => 'https://sanalpos.ziraatbank.com.tr/v4/v3/Vposreq.aspx',
                'gateway_3d' => 'https://mpi.ziraatbank.com.tr/Enrollment.aspx',
                'query_api' => 'https://sanalpos.ziraatbank.com.tr/v4/UIWebService/Search.aspx',
            ],
        ],

**Comment by sekizlipenguen** [comment]
Payten dediğimiz şey EstV3Pos demek midir? teb bankasında ip kısıtlaması hatası alıyoruz da ip kısıtlama yok ortada? eskiden bu da çalışıyordu :/

**Comment by nuryagdym** [comment]
eskiden vardi, ancak genel olarak ziraat icin payten (EstV3Pos) kullaniyorlar diye biliyorum.
gecmiste biri artik ziraat payflexv4'u desteklemiyor dedi diye hatirliyorum.

**Comment by sekizlipenguen** [comment]
hm anladım dediğim gibi şu an halen aşağıdakini kullanıyoruz ve destek sağlıyor görülüyor.

 'ziraat-vpos' => [
            'name' => 'Ziraat Bankası',
            'class' => Mews\Pos\Gateways\PayFlexV4Pos::class,
            'gateway_endpoints' => [
                'payment_api' => 'https://sanalpos.ziraatbank.com.tr/v4/v3/Vposreq.aspx',
                'gateway_3d' => 'https://mpi.ziraatbank.com.tr/Enrollment.aspx',
                'query_api' => 'https://sanalpos.ziraatbank.com.tr/v4/UIWebService/Search.aspx',
            ],
        ],

**Comment by nuryagdym** [comment]
@sekizlipenguen testlerin bitt mi?
Baska sorun yok ise bugun ya da yarin release cikarim.

**Comment by sekizlipenguen** [comment]
Selamlar, mail ile attığım şeyler dışında her şey çalıştı çözdük eline aağlık 🙏
