### ISSUE TITLE
Para çekimi ve iade

### ISSUE THREAD

**Issue by 21azad** [mewebstudio/pos#232]
### Hatanın özeti

Ben dün copilot aldım ancak bilgilendirme de 30 gün ücretsiz deneme yazıyordu bende alışverişe devam ettim ancak kartımdan iki kez çekim olmuş ard arda ve bugün iptal ettiğim zaman çekilen ardı ardına iki para da kartıma yansımadı

### Banka ismi

İş bankası 

### Gateway ismi

PayForPos

### İşlem Tipi

MODEL_3D_SECURE ödeme

### Checks

- [X] Bu konuda zaten bir hata bildirimi olmadığından eminim.
- [X] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
copilotun bu kutuphane ile ne alakasi var?
