### ISSUE TITLE
formatAmount(): Argument #1 ($amount) must be of type string, null given

### ISSUE THREAD

**Issue by nzrylmz** [mewebstudio/pos#237]
### Hatanın özeti

Ödeme işleminden sonra cevap aşamasında aşağıdaki hatayı alıyorum.

```
$config = \App\Helpers\SanalPos::config($pos_key);

$paymentModel = $config['paymentModel'] ?? null;
$transactionType = $config['transactionType'] ?? null;
$posGateway = $config['posGateway'] ?? null;
$order = $session->get('order');
$card  = null;

$posGateway->payment(
    $paymentModel,
    $order, // order içindeki verileri kontrol ettim, ödeme aşamasında girdiğim verilerle uyuşuyor
    $transactionType,
    $card
);
```

$posGateway->payment kısmında bu hatayı veriyor.

```
Mews\Pos\DataMapper\ResponseDataMapper\EstPosResponseDataMapper::formatAmount(): Argument #1 ($amount) must be of type string, null given, called in /**proje yolu**/DataMapper/ResponseDataMapper/EstPosResponseDataMapper.php on line 132
```

Ödeme aşamasında miktarı hem sayı hem string olarak girmeyi denedim. Ama zaten ödeme aşamasında değil, cevap döndüğünde sorun oluyor.

### Banka ismi

İş Bankası

### Gateway PHP sınıfı

EstV3Pos

### İşlem Tipi

MODEL_3D_SECURE ödeme

### Kütüphane versiyonu

1.4.1

### Checks

- [X] Bu konuda zaten bir hata bildirimi olmadığından eminim.
- [X] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
Merhaba,
mumkunse bu methodun 
https://github.com/mewebstudio/pos/blob/e9a15fa42a8bece131fa896af37528379221ffa7/src/DataMapper/ResponseDataMapper/EstPosResponseDataMapper.php#L112
en basina bu kodu
```php
echo json_encode($raw3DAuthResponseData);
echo json_encode($rawPaymentResponseData);
```
ekleyerek odemeyi tekrar deneyip sonucu paylasir misin,
hassas verileri gizlemen gerekecek.

**Comment by nzrylmz** [comment]
$raw3DAuthResponseData içinde sadece 'HASH' ve 'rnd' var  
$rawPaymentResponseData ise null geliyor

**Comment by nuryagdym** [comment]
`$raw3DAuthResponseData` icinde sadece 'HASH' ve 'rnd'  olsaydi o satira gelmeden once hata vermesi gerekiyordu.
`$raw3DAuthResponseData` icerigini gormeden guncelleme yapamam, cunku tek sorun `amount` olmayabilir.
Amount kismi duzelttikten sonra, sonraki satirlarda yine patlayabilir.

**Comment by nzrylmz** [comment]
Şu an farkettim. Localde sorunsuz çalışıyor, ama sunucuya yüklediğimde cevap sadece 'HASH' ve 'rnd' olarak dönüyor. Banka ile alakalı bir durum sanırım.

**Comment by nuryagdym** [comment]
farkli ortamlar ise (production/test) farkli cevaplar donebilir. 
test icin assecoya istek gonderilir, production icin isbankin sunucularina
