### ISSUE TITLE
AbstractGateway class bulunamadı hatası

### ISSUE THREAD

**Issue by ysfkarakaya** [mewebstudio/pos#238]
Fatal error: Uncaught Error: Class "AbstractGateway" not found in C:\laragon\www\ziraat2\test.php:11 Stack trace: #0 {main} thrown in C:\laragon\www\ziraat2\test.php on line 11
böyle bir hata alıyorum yardımcı olabilir misiniz?

**Comment by nuryagdym** [comment]
Merhabalar, kutuphane dosyalari eksik, tekrar indirmeyi deneyiniz.

**Comment by ysfkarakaya** [comment]
direk composer ile kuruyorum ama config dosyasında bu hatayı alıyorum baktım gateway içerisinde AbstractGateway dosyası da var.
`<?php

require 'vendor/autoload.php';

// API kullanıcı bilgileri
$account = \Mews\Pos\Factory\AccountFactory::createEstPosAccount(
'ziraat', //pos config'deki ayarın index name'i
'xxx', 
'xx',
'xxxx',
AbstractGateway::MODEL_3D_SECURE, //storetype
'xxx',
AbstractGateway::LANG_TR
);

// API kullanıcı hesabı ile paket bir değişkene aktarılıyor
try {
    $pos = \Mews\Pos\Factory\PosFactory::createPosGateway($account);
    //değere göre API URL'leri test veya production değerler kullanılır.
    $pos->setTestMode(true);
} catch (\Mews\Pos\Exceptions\BankNotFoundException | \Mews\Pos\Exceptions\BankClassNullException $e) {
    dd($e);
}`

**Comment by nuryagdym** [comment]
Bu hatanin kutuphane ile alakasi, kutuphaneyi projenize nasil eklediginiz nasil kullandiginizla ilgili.
Sagladiginiz kodda bir sorun gormuyorum.
Bu hata konusunda yardimci olamayiz.

**Comment by nuryagdym** [comment]
Sorunu anladim simdi, sanirim kutuphanenin eski versiyonunu kullaniyorsunuz. 

require 'vendor/autoload.php'; sonra
```php
use \Mews\Pos\Gateways\AbstractGateway;
```
eklemen gerekiyor.

Yeni versiyona gectiyseniz, `/docs` altindaki orneklere bakmaniz gerekiyor.

**Comment by ysfkarakaya** [comment]
evet dediğiniz gibiymiş docs içerisinde yer aldığı gibi ve examples klasöründeki gibi ilerledim ama form gödnerince böyle bir sorunla kaşılaştım bu konuda bilginiz var mı peki?
https://prnt.sc/OqWONuHflzLc

**Comment by nuryagdym** [comment]
Kutuphanenin hangi versiyonu kullaniyorsunuz? composer.lock icersinde hangi versiyonu kullandiginiz yazar. 

EstPos artik kullanmamaniz gerekiyor.
kutuphane configinden EstPos'u EstV3Pos olarak degistirmeniz gerekiyor.

https://github.com/mewebstudio/pos/blob/e9a15fa42a8bece131fa896af37528379221ffa7/config/pos_production.php#L18

**Comment by ysfkarakaya** [comment]
evet dediğiniz şekilde kullanıyordum zaten. 3d klasörünü kullanıyordum diğer klasördeki kodları da denedim '3d-pay-hosting' sadece bunda çalışıyor diğerlerinde hata alıyorum. İlginiz için teşekkür ederim.
