### ISSUE TITLE
Ziraat-estpos 'mdErrorMsg' bulunmadı.

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#239]
### Hatanın özeti

EstPosResponseDataMapper.php : map3DPaymentData fonksiyonundaki $raw3DAuthResponseData datasına bankadan gelen veri 
`Array
(
    [amount] => 0.01
    [clientid] => *
    [currency] => *
    [Ecom_Payment_Card_ExpDate_Month] => 0
    [Ecom_Payment_Card_ExpDate_Year] => 0
    [ErrMsg] => Girilen kart numarası doğru formatta değildir. Kart numarasını kontrol ederek tekrar işlem deneyiniz.
    [ErrorCode] => HPP-1001
    [failUrl] => https://*.com/odeme/f05e81c8-4ea0-44a9-8fe8-d45b854c62d9
    [HASH] => **/fxNKZvC4E2EbQOgiqNi9FeXBMj636Q==
    [hashAlgorithm] => ver3
    [lang] => tr
    [maskedCreditCard] => ***
    [MaskedPan] => **
    [oid] => f05e81c8
    [okUrl] => https://*.com/odeme/d45b854c62d9
    [Response] => Error
    [rnd] => MZrcwoSd1+-*
    [storetype] => 3d
    [taksit] => 
    [traceId] => ****
    [TranType] => Auth
)`

**141. satırda istenen $raw3DAuthResponseData['mdErrorMsg'] veri bulunamadığı için hata dönüyor.**

Çözüm olarak 141. satırı alttaki gibi güncellediğimde sorun çözüldü.
`  'md_error_message'     => $this->is3dAuthSuccess($mdStatus) ? null : $raw3DAuthResponseData['ErrMsg'],`

### Banka ismi

Ziraat Bankası Payten

### Gateway PHP sınıfı

EstV3Pos

### İşlem Tipi

MODEL_3D_SECURE ödeme

### Kütüphane versiyonu

1.4.1

### Checks

- [X] Bu konuda zaten bir hata bildirimi olmadığından eminim.
- [X] Hatayı yeniden oluşturmak için gereken detayları ekledim.

**Comment by nuryagdym** [comment]
Tesekkurler, sorunu cozup **v1.4.2** release ciktim
