### ISSUE TITLE
Akbank sanal pos değişikliği

### ISSUE THREAD

**Issue by evrenonur** [mewebstudio/pos#243]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 0  |
| Gateway ismi| 0 |
| Banka ismi| Akbank |

## Sorunuz

Merhaba. https://sanalpos-prep.akbank.com/#entry adresinde akbank için yeni sanal pos düzenlemesi yapılmış. Kütüphaneye güncelleme yapıldımı

## Göndermeden önce kontroller

* [x] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [x] Dökümantasyonu okudum, araştırdım ve konuyla ilgili bilgileri bulamadım. [dökümantasyon](https://github.com/mewebstudio/pos/blob/master/README.md)
* [x] İlgili örnek kodları kontrol ettim ve konuyla ilgili bilgileri bulamadım. [örnek kodlar](https://github.com/mewebstudio/pos/tree/master/examples)

**Comment by nuryagdym** [comment]
Merhaba, bu gateway destegi var mi yok mu soruyorsaniz, cevabi var.
ornek kodlara https://github.com/mewebstudio/pos/tree/master/examples/akbankpos burdan bakabilirsiniz

**Comment by evrenonur** [comment]
aslında şöyle şuanki sistem 15.11.2024 tarihinden sonra geçersiz olacak. Akbank tarafından verilen bilgi bu yönde iletmiş olduğum sisteme geçiş yapılacakmış.

**Comment by nuryagdym** [comment]
Su an sistem dediginiz sanirim Asseco/Payten alt yapisi. Yeni alt yapiya gecis icin gonderdigim ornek kodlari kullarak ve pos config'e ilgili configi ekleyerek:
https://github.com/mewebstudio/pos/blob/6cd8a9872557dae409bb7071943a3c34b4d0f9a4/config/pos_production.php#L7-L13

kullanabilirsiniz.

Yeni alt yapisi kutuphanenin v1.1 ile baslayarak eklendi. 
Bu konuda ayrica zaten issue var: #191

**Comment by nuryagdym** [comment]
Burdaki ornekler daha anlasilir diye dusunuyorum:
https://github.com/mewebstudio/pos/blob/master/docs/THREED-PAYMENT-EXAMPLE.md

THREED-PAYMENT-EXAMPLE.md kodlarda yapmaniz gereken degisiklikler:

- `\Mews\Pos\Factory\AccountFactory::createEstPosAccount( 'akbank', ... )` yerine  `\Mews\Pos\Factory\AccountFactory::createAkbankPosAccount('akbank-pos', ... )` kullanilacak.
-  pos config'e https://github.com/mewebstudio/pos/blob/6cd8a9872557dae409bb7071943a3c34b4d0f9a4/config/pos_production.php#L7-L15 bu configler eklenecek, (bunlar canli ortam configleri)


Benden bu kadar, gerisi icin yardimci olamam, entegrasyon destegi de vermiyorum.

**Comment by seyyah** [comment]
Merhaba

https://virtualpospaymentgateway-prep.akbank.com/payhosting bunun test ortami olmasini bekliyoruz. Ancak url erisilemez, bilinen ve test ortaminda yapilan bir degisiklik midir? Yoksa akbank sanal test sunuculari mi kapali/erisilmez durumda veya erisim icin ozel bir islem mi gerekiyor.

Ilgi ve zamaniniz icin tesekkuler

**Comment by nuryagdym** [comment]
merhaba,

paylastiginiz url kutuphane'deki url ile ayni degil: 
https://github.com/mewebstudio/pos/blob/59cbf8772ca189dfceeaab2d9b0aa2a96aee8233/config/pos_test.php#L5-L13
