### ISSUE TITLE
Puan Sorgulama Destegi

### ISSUE THREAD

**Issue by semihyilmaz** [mewebstudio/pos#250]
| Information | Description |
|--------------|---------|
| Kütüphane versiyonu | 1.4.2 |
| Gateway ismi| İşbankası ImeceCard |
| Banka ismi|  İşbank|

## Sorunuz
Merhaba,
İşbankası ImeceCard ödeme öncesi bir Query çalıştırılıp, kart bilgileride iletilip, puan-hesap vs sorgulanıyor. Kütüphanede bu yöntemi ne ile sorgulamalıyım?
Payment, status, history değil. Ayrı bir Query olmalı. Eski versiyonda bunu harici query fonk ile yapmıştım.

## Göndermeden önce kontroller

* [x] Bu konuda zaten bir hata bildirimi olmadığından emin olun. Bakınız: [hata bildirimleri](https://github.com/mewebstudio/pos/issues)
* [x] Dökümantasyonu okudum, araştırdım ve konuyla ilgili bilgileri bulamadım. [dökümantasyon](https://github.com/mewebstudio/pos/blob/master/README.md)
* [x] İlgili örnek kodları kontrol ettim ve konuyla ilgili bilgileri bulamadım. [örnek kodlar](https://github.com/mewebstudio/pos/tree/master/examples)

**Comment by nuryagdym** [comment]
Merhaba, yeni versiyonda da ayni sekilde puan sorgulama gibi destek eklenmedi. 
Yeni versiyonda da eskisi gibi harici query ile yapmaniz gerekiyor.

Puan sorgulama icin yeterli kadar istek olursa kutuphane bazinda butun gatewayler icin eklemeyi dusunebilirim.

**Comment by semihyilmaz** [comment]
Aslında konu puan sorgulama değil.
Tarım veya Sektör kartlarda,
PaymentTemplate, Hesap, vb gibi seçimler oluyor. Sadece Puan demek burada yanlış bir durum. Konu puan değil.
Ben lib'i extend ederek $pos->query([
data
]);
şekline getirerek çözüyorum.

**Comment by nuryagdym** [comment]
Tmm, dedigim gibi yine ozel query yapman gerekiyor.

Diger konu ise open source library'larda inheritance kullanmayi tavsiye etmiyorum.
Genelde kutuphaneler inheritance kullanmasinlar diye `final` classlar yapiyorlar. Sebebi ise, internal kodu (ornegin  **protected** methodlari) user'lari etkilemeden rahat degistirebilme.

Yeni major versiyonda classlari `final` yapmayi dusunuyorum.

**Comment by semihyilmaz** [comment]
@nuryagdym teşekkürler. Yarın(5 kasım) deneyip, bilgi ileteceğim.
