### ISSUE TITLE
Akbank taksit.

### ISSUE THREAD

**Issue by necoakdogan** [mewebstudio/pos#29]
Merhabalar. Akbank entegrasyonu için taksit sistemi yapılabilir mi? Sistemde göremedim sanki. Bu konuda nasıl bir yol izlenmeli?

**Comment by nuryagdym** [comment]
Merhabalar, akbank kod orneginde var, installment degeri taksiti belirler ve calisiyor olmasi gerekiyor.

**Comment by necoakdogan** [comment]
Öncelikle cevabınız için teşekkürler. Aslında eksik anlattım; bin numarası üzerinden taksit sorgusu yapılabilir miyim diye sormam gerekiyordu.

**Comment by nuryagdym** [comment]
Bu islem icin dokumantasyonu varsa paylasirsaniz ekleyebiliriz. Taksit sorgusunu kutuphanedeki gatewaylerin hic biri desteklemiyor diye biliyorum

**Comment by mewebstudio** [comment]
@necoakdogan BIN numaraları ile kredi kartının tespiti v.s. konularını kendi uygulamanız içerisinde değerlendirmeniz gerek. Bu durum ödeme sisteminden bağımsız.
