### ISSUE TITLE
EST 3d_pay_hosting modeli

### ISSUE THREAD

**Issue by n0thing-inc** [mewebstudio/pos#30]
Kütüphanede 3d_pay_hosting modeli olmadığı için storekey hatalı uyarısı dönüyor. 
3d_pay ile aynı parametreleri alıyor ve hash hesaplaması aynı. EstPos Gateway'de ufak bir değişiklik ile sorunsuz çalışıyor.

Eski Kod Betiği : 
`if ($this->account->getModel() === '3d_pay') {
                $inputs = array_merge($inputs, [
                    'islemtipi' => $this->type,
                    'taksit' => $this->order->installment,
                ]);
            }`

Yeni Kod Betiği:
`if ($this->account->getModel() === '3d_pay'  || $this->account->getModel() === '3d_pay_hosting')) {
                $inputs = array_merge($inputs, [
                    'islemtipi' => $this->type,
                    'taksit' => $this->order->installment,
                ]);
            }`

Eski Kod Betiği : 
`elseif ($this->account->getModel() === '3d_pay') {
            $hashStr = $this->account->getClientId() . $this->order->id . $this->order->amount . $this->order->success_url . $this->order->fail_url . $this->type . $this->order->installment . $this->order->rand . $this->account->getStoreKey();
        }`

Yeni Kod Betiği : 
`elseif ($this->account->getModel() === '3d_pay' || $this->account->getModel() === '3d_pay_hosting') {
            $hashStr = $this->account->getClientId() . $this->order->id . $this->order->amount . $this->order->success_url . $this->order->fail_url . $this->type . $this->order->installment . $this->order->rand . $this->account->getStoreKey();
        }`

**Comment by nuryagdym** [comment]
Merhabalar, istediginiz guncellemeyi yapip merge request olusturdum, bir kontrol eder misiniz.
Ayrica 3d Host payment icin kullanilan anahtar kelime `3d_host` sizinde verdiginiz ornediginizdeki gibi `3d_pay_hosting` degil.

**Comment by mewebstudio** [comment]
@n0thing-inc, @nuryagdym bununla ilgili bir geliştirme yaptı. Deneyip dönüş yapar mısınız?
