### ISSUE TITLE
ESTPOS ORDERSTATUS

### ISSUE THREAD

**Issue by lansas** [mewebstudio/pos#32]
![image](https://user-images.githubusercontent.com/1222507/121556755-d36d9000-ca1c-11eb-9af4-e47febd1134b.png)

merhabalar,
Mevcut Order statusü orderid ye göre nasıl sorgulayabiliyoruz?

**Comment by nuryagdym** [comment]
Merhabalar, burdaki ornek isinize yaramasi lazim. https://github.com/mewebstudio/pos/blob/fa4a7b4792462a84cc9ccfbf9f86ff51c6b1a00c/examples/akbank/regular/status.php

**Comment by lansas** [comment]
çözdüğüm şekli paylaşayım:

`$a_pos_settings = [
                    'bank' => 'teb',
                    'model' => '3d',
                    'client_id' => '123456789',
                    'username' => 'resge',
                    'password' => 'X123PASS',
                    'store_key' => '1111111111',
                    'env' => 'production',
                    'lang' => \Mews\Pos\EstPos::LANG_TR
                ];
$o_pos = new \Mews\Pos\Pos($a_pos_settings);
$o_est = new \Mews\Pos\EstPos($o_pos->getConfig(),$o_pos->getAccount(),$o_pos->getCurrencies());
$meta["order_id"]="123456";
$o_result = $o_est->status($meta);
var_dump($o_result);
echo $o_result->getResponse()->order_status;
`

**Comment by nuryagdym** [comment]
sizdeki eski versiyon anladigim kadariyla, su anki versiyonda yukarda verdigim linkteki gibi

**Comment by lansas** [comment]
teşekkürler. Hatırlarsan daha önce tekrarlayan ödeme üzerine konuştuyduk, tekrarlayan ödemedeki orderstatus ü sorgulamak biraz daha karışık. Umarım çok şey eklemek gerekmez. Hiç güncelleme yaptınız mı bununla ilgili?
