### ISSUE TITLE
PHP versiyon düzenlemesi

### ISSUE THREAD

**Issue by nrtszr** [mewebstudio/pos#39]
Merhabalar,

PHP 8 de hata mesajı veriyor. 

 [InvalidArgumentException]
  Package mews/pos has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:
    - mews/pos 0.4.11 requires php ^7.1.3 which does not match your installed version 8.0.11.

İyi Çalışmalar

**Comment by mewebstudio** [comment]
Katkıların için teşekkürler @nuryagdym
https://github.com/mewebstudio/pos/pull/40
