### ISSUE TITLE
Bin kodu sorgulama

### ISSUE THREAD

**Issue by huseyinyildirimcom** [mewebstudio/pos#4]
Merhaba,

Taksitlendirme işlemi için bin kodlarını kontrol edebileceğimiz bir yapı varmıdır?

Teşekkürler.

**Comment by mewebstudio** [comment]
Merhaba. Bu yapıyı uygulamanızda kendiniz oluşturmalısınız. Paket sadece ödeme sistemlerinin api iletişimi için.
