### ISSUE TITLE
Garanti 3d_pay modeli ile ödemede response null sorunu 

### ISSUE THREAD

**Issue by zeydduran** [mewebstudio/pos#48]
https://github.com/mewebstudio/pos/blob/42a14916206a0d7f8c4359bab7ebafbdbdb10246/src/Gateways/GarantiPos.php#L148

İlgili satırdaki map3DPayResponseData methodu herhangi bir sonuç döndürmez bu yüzden response null olarak tanımlanır.

**Comment by nuryagdym** [comment]
Merhabalar, dediginiz sorunu bu hafta sonu halletmeye calisacagim, tesekkuler
