### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by cebozkurt** [mewebstudio/pos#5]
Merhaba, Payment isteğini start ettiğim zaman `$decrypted_data_list = array_map('strval', [

                $decrypted_data_array[0],

                $decrypted_data_array[1],

                $decrypted_data_array[2],

                $decrypted_data_array[3],

                $decrypted_data_array[4],

                $this->getHostName($decrypted_data_array[7]),

            ]);`

kısmından hata alıyorum? Bir çözümü var mıdır

**Comment by mewebstudio** [comment]
Hangi banka için kullandığınızda bu hatayı alıyorsunuz? Eğer YKB PosNet ise sunucunuzda mcrypt kurulu olmalı.
