### ISSUE TITLE
YKB 3D Encryption Key Bulunamadı Hatası

### ISSUE THREAD

**Issue by devsoftinyo** [mewebstudio/pos#54]
`Fatal error: Uncaught Exception: Encryption Key bulunamadı. in /home/public_html/mke/demo/odeme2/src/Gateways/PosNet.php:240 Stack trace: #0 /home/public_html/mke/demo/odeme2/examples/ykb/3d/form.php(35): Mews\Pos\Gateways\PosNet->get3DFormData() #1 {main} thrown in /home/public_html/mke/demo/odeme2/src/Gateways/PosNet.php on line 240`
examples/ykb/3d/form.php sayfasına post attığımda bu şekilde bi hatayla karşılaşıyorum.

`$account = AccountFactory::createPosNetAccount('yapikredi', 'XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXXX', 'XXXXXX', '3d', '10,10,10,10,10,10,10,10');`
Encryption keyi tanımlamış olmama rağmen.

**Comment by nuryagdym** [comment]
Merhabalar, benimle size verilen Yapikredi dokumenini paylasir misiniz nuryagdy@mustapayev.com .
Yapikredi kodu calisan bir kod, ve aldiginiz exception'a bakildiginda ilgili istekte encryption key bankaya gonderilen istekte gonderilmiyor. Bu zamana kadar gonderilmedi, belki yeni API'nda istiyorlar olabilir. Yardimci olabilmem icin dedigim gibi Yapikredini dokumantasyonu lazim

**Comment by alpereneymen** [comment]
Merhabalar,
Öncelikle hızlı dönüşleriniz ve bilgilendirmeleriniz için teşekkür ederim.
Biz biraz deneme yanılma, biraz da kurcalayarak POSU çözdük gibi.
Tecrübelerimi paylaşmak isterim.

Öncelik YapıKredi pos tarafında gerçekten çok kötü çalışıyor bunu bilerek entegrasyon sürecini yürütmek gerekli hayalkırıklıklarının önüne geçmek için. Encryption key tanımlanmadı hatasını mail ile çözdük kodumuz ile ilgili bir problem yokmuş.

Ayrıca YapıKredi'de test ortamında fix olarak '10,10,10,10,10,10,10,10' storekeyi kullanılıyor. Sonrasında üretim ortamına geçtiğinizde sanalpos ekranından yeni güncel keyi alıp tanımlanamız gerekiyor, yoksa issueda bahsettiğim hata yine dönüyor.

Tüm bunlarla beraber account tarafına karşılık gelen değişkenleri açıklama satırı olarak not düşüyorum, tüm arkadaşların rahatça kullanabilmesi için.

Teşekkürler
Saygılarımla...

**Comment by nuryagdym** [comment]
Merhabalar,
Bastan yapikrediden vaz gecin diyecektim :), susayim dedim. Kendim de en cok Yapikredi'de sorun yasadim. en kolayi EstPos entegrasyonu oldu benim icin. `examples` altindaki kodlar zaten ornek amacli.
