### ISSUE TITLE
Garanti Regular Ödeme merchantId problemi.

### ISSUE THREAD

**Issue by erenbiente** [mewebstudio/pos#56]
Merhaba,

Regular ödemede src/Gateways/GarantiPos.php dosyasında yer alan 262.satırdaki merchantId hatalı gözüküyor

`MerchantID' => $this->account->getTerminalId(),`

şu şekilde olması gerekmiyor mu?

` 'MerchantID' => $this->account->getClientId(),`

**Comment by nuryagdym** [comment]
Merhabalar, olabilir. Regular payment'i kullanan kullanan cok olmadigi icin eksiklikleri olabilir. siz test edebildiniz mi? Yani mumkunse o satiri degistirip calisip calismadigini soylerseniz duzeltelim. Baska sorunlar da olursa yazarsiniz, hepsini duzeltiriz.

Tesekkurler

**Comment by nuryagdym** [comment]
tmm, regular payment'in response'u da sorunsuz calisti mi?
Baska sorun yok ise, bu hafta ya da bir onumizdeki hafta duzeltip yeni release cikarim.

Deniz bank calismasi yok ama API dokumanlarini paylasirsaniz calismabilirim uzerinde, varsa ornek kodlari da.

**Comment by erenbiente** [comment]
Evet. regular sorunsuz çalışıyor gözüküyor.

Denizbank için elimde kodlar var. nasıl paylaşabilirim?

**Comment by nuryagdym** [comment]
tmm tesekkurler, 1 hafta icinde hallederim bu sorunu
