### ISSUE TITLE
Denizbank Entegrasyon

### ISSUE THREAD

**Issue by erenilhan** [mewebstudio/pos#57]
Merhaba,

Denizbank ile ilgili gerekli dokümanlar ve örnek kodları ekliyorum.

Bu konuda test ve development süreçlerinde yardımcı da olabililirim.

[DENIZBANK VPOS DOC 16.zip](https://github.com/mewebstudio/pos/files/8230060/DENIZBANK.VPOS.DOC.16.zip)

**Comment by nuryagdym** [comment]
Merhaba,
tesekkurler, bu ay icinde halletmeye calisirim

**Comment by nuryagdym** [comment]
Merhaba @erenilhan, 
calismaya basladim, ama gateway URL'lerine erisemiyorum. bu iki URL'i ornek koddan ve dokumantasyondan buldum: 
https://test.inter-vpos.com.tr/mpi/Default.aspx
https://sanaltest.denizbank.com/MPI/Default.aspx

**Comment by erenilhan** [comment]
Merhaba,
şimdi soruyorum ve detayları paylaşacağım @nuryagdym

**Comment by erenilhan** [comment]
Kurumun yazdığı cevap şu şekilde.

"Intervpos alt yapısı üzerinden destek veriyoruz.."
 
Dökümanda iletilen adres ve örnek scriptler çalışır durumdadır..

"Test ortamında işlem yapmak için, ip adresinize erişim yetkisi tanımlanması gerekir.. adresinizi iletirseniz network ekiplerimizden destek alabiliriz?
 
Gerçek ortamda hata alıyorsanız, örnek bir işlemin detaylarını iletebilir misiniz?"

**Comment by nuryagdym** [comment]
Tesekkurler,
Kusura bakmayin, kendim soramiyorum, musteri harici kimseye yardimci olmuyorlar genelde. Tmm, diger sanal poslarin gateway'lerine ping gondermeyi denedim, hepsinde pingler engellenmis durumda anladigim. 

IP adresi bugun yarin paylasirim sizinle.

**Comment by nuryagdym** [comment]
tekrar merhaba @erenilhan , IP address bu: **45.84.191.231**

**Comment by erenilhan** [comment]
@nuryagdym hocam erişim yetkisi tanımlanmış

**Comment by nuryagdym** [comment]
tesekkurler @erenilhan ,
denedim hala calismiyor. 
https://test.inter-vpos.com.tr/mpi/Default.aspx (kod ornekte verilen URL)
ve 
https://sanaltest.denizbank.com/MPI/Default.aspx (dokumantasyonda verilen URL)
ikisine de ulasilmiyor. Bankayla iletisime gecip test ortam URL'lerini teyit eder misiniz.
Kendiz ve Banka burdan deneyerek calismadigini gorebilirsiniz: 
https://mustapayev.com/pos/examples/interpos/3d/

**Comment by erenilhan** [comment]
Mail attım ve erişimi kontrol edip düzenlediler. 
"İletmiş olduğunuz ip bilgileri sunucu ip bilgisi mi ? 
3d işlemler için Pc nin internete çıkış ip bilgisi olması gerekiyor. 
Non secure işlemlerde ise sunucu ip bilgisi https://test.inter-vpos.com.tr/ adresi browserda açabiliyor musunuz? 

mailini attılar.  Ben de gerekli kontrolleri yapıp bilgilendirme sağladım.
@nuryagdym şu an erişim vermiş olmalılar. ama ben de yine çalışmadı. Siz de deneyebilir misiniz?

**Comment by nuryagdym** [comment]
Simdi 3D odemede 2 asama var.
1. Musteri kredi kart bilgilerini girer, sonra tek seferlik 3D sifresini girecegi sayfaya acilir. Bu islem bu adresde gerceklesir https://test.inter-vpos.com.tr/mpi/Default.aspx . Bu adrese herkes (butun musteriler) erisebilmesi lazim. Sunucu IP izni tanimlamaya gerek yok bunun icin.
2. Ikinci asamada, 3D sifresini girdikten sonra musteri websiteye geri yonledirilir, web site ise odemeyi tamamlamak icin 2. istegi banka sunucusuna gonderir. Bu istek icin web sitenin sunucusuna IP izni verilmesi gerekiyor.  

Yani anlatmak istedigim, 1. asamayi gecemiyoruz su an. 2. asamaya gecersek o zaman IP iznini konusabiliriz. 
ben yurt disinndayim, bu yuzden test ortaminin yurtdisindan erisimini kapatmis olabilirler. Ama sizin verdigim websitemin adresinden girip islemi yapabilmeniz gerekiyordu. eger siz de https://test.inter-vpos.com.tr/ adrese erisemiyorsaniz bu tamamen bankayla alakali bir sorun. IP izin ile hic alakasi yok

**Comment by nuryagdym** [comment]
Merhabalar,
@erenilhan kor goze gelistirme yaptim, kendi ortaminizda test yapar misiniz. 
henuz yayinlamadim, bu yuzden 
`composer require nuryagdym/pos:dev-interpos-integration`
sekilde indirip test eder misiniz.
mumkunse
- 3d
- 3d pay
- 3d Host
- non secure odeme
- durum sorgulama
- iptal
- iade
 islemlerin hepsini deneyebilirseniz sevinirim. 
Bu islemlerin ornegini, /examples/interpos altinda bulabilirsiniz

**Comment by nuryagdym** [comment]
@erenilhan 
Burdan cekmeyi dener misiniz o zaman: `composer require mews/pos:dev-interpos-integration`

**Comment by erenilhan** [comment]
@nuryagdym şu an çekti. testleri yapıp bilgilendireceğim. çok teşekkürler

**Comment by sekizlipenguen** [comment]
Selamlar, bu entegrasyonun sonuçlandı mı acaba?

**Comment by nuryagdym** [comment]
calisiyor, sorun bulunamadi
