### ISSUE TITLE
12 saatte puan toplama 

### ISSUE THREAD

**Issue by Marjinal2023** [mewebstudio/pos#73]
Arkadaşlar şuan için sadece puan toplamamı mevcut veya başka bir kazanç sistemi varmı ?
#githup #ibax

**Comment by nuryagdym** [comment]
Merhaba, hangi banka? puan toplama ile ilgili destek yok, ama dokumantasyon paylasirsaniz belki ekleriz

**Comment by Marjinal2023** [comment]
Efendim anlayamadım 23 Nis 2022 11:21 tarihinde nuryagdym ***@***.***> yazdı:
Merhaba, hangi banka? puan toplama ile ilgili destek yok, ama dokumantasyon paylasirsaniz belki ekleriz

**Comment by nuryagdym** [comment]
Merhabalar, ne istediginizi anlamaya calisiyorum.
kutuphane 7 farkli sanal posu destekliyoruz, her birinin kendine gore ozellikleri var.
Puan toplama derken hangi sanal pos (banka)?
Nasil bir ozellik?
bu ozelligin API dokumantasyonu var mi elinizde?
