### ISSUE TITLE
EstPos - 3d ödeme tamamlama sorunu

### ISSUE THREAD

**Issue by bugafix** [mewebstudio/pos#76]
Merhaba,

İş/ak bu bankalardan biriyle 3d ödeme yapmaya çalışıyorum. 3d ekranına yönleniyor şifre vs giriyorum. 
Daha sonra response dönüyor fakat "declined" hatası alıyorum. bankalarla iletişime geçtiğim zaman şu bilgiyi paylaştılar.

_Merhaba,
İlgili işlemi incelediğimde işlem 3D doğrulama aşamasına kadar gelip 3D doğrulamasında başarılı olup akışa devam etmeden yarıda kesilmiştir.
Kullandığınız standart 3D modeli iki aşamalı bir modeldir ve işlem ilk olarak 3D doğrulama aşamasına post edilip tamamlandıktan sonra API aşamasına post edilerek akışı tamamlamış olması gerekir fakat ilgili işlem ikinci aşamaya hiç gitmemiş; dolayısı ile bizim tarafımıza ulaşmamıştır._

3d döndükten sonraki kod parçacığı

```
        $temp = TempPayment::whereVirtualOrderId($virtualOrderId)->first();
        $account = new PaymentAccount();

        $pos = $account->getBankFactory($temp->bank, $temp->model);
        $pos->prepare($temp->order, AbstractGateway::TX_PAY);
        $pos->payment();

        $response = $pos->getResponse();
        return ($response);
```

dönen response değeri;
```

{
  "transaction_security": "MPI fallback",
  "md_status": "1",
  "hash": "sp8M+ECXVSaPb1fTqiLQsA80BjA=",
  "rand": "/UMa9kZAhn61o2moMRrt",
  "hash_params": "clientid:oid:mdStatus:cavv:eci:md:rnd:",
  "hash_params_val": "7006638672082022052098BD1ABIBAIMAAMUoAAAAEAAAAAAAAAA=02418342:9487EB80334D0AEED1F1601B7671A42D0E9BD53115AD1B3697937919E532389F:3679:##700663867208/UMa9kZAhn61o2moMRrt",
  "masked_number": "******",
  "month": "07",
  "year": "26",
  "amount": "0.10",
  "currency": "TRY",
  "eci": null,
  "tx_status": null,
  "cavv": null,
  "xid": "2022052098BD",
  "md_error_message": "Success",
  "name": "--------",
  "3d_all": {
    "oid": "2022052098BD",
    "cavv": "ABIBAIMAAMUoAAAAEAAAAAAAAAA=",
    "encoding": "UTF-8",
    "Ecom_Payment_Card_ExpDate_Month": "**",
    "currency": "949",
    "callbackCall": "true",
    "amount": "0.10",
    "eci": "02",
    "maskedCreditCard": "*****",
    "firmaadi": "****,
    "islemtipi": "Auth",
    "Ecom_Payment_Card_ExpDate_Year": "****",
    "ShipToStateProv": null,
    "storetype": "3d",
    "mdStatus": "1",
    "failUrl": "****/pos-callback/2022052098BD",
    "clientIp": "****",
    "mdErrorMsg": "Success",
    "clientid": "700663867208",
    "MaskedPan": "********6151",
    "Email": "****",
    "taksit": null,
    "BillToStateProv": null,
    "okUrl": "https://****/pos-callback/2022052098BD",
    "md": "***:9487EB80334D0AEED1F1601B7671A42D0E9BD53115AD1B3697937919E532389F:3679:##700663867208",
    "xid": "07HlbXHrL1+L+TDCSfaYVpNODqA=",
    "lang": "tr",
    "HASH": "sp8M+ECXVSaPb1fTqiLQsA80BjA=",
    "rnd": "/UMa9kZAhn61o2moMRrt",
    "HASHPARAMS": "clientid:oid:mdStatus:cavv:eci:md:rnd:",
    "HASHPARAMSVAL": "7006638672082022052098BD1ABIBAIMAAMUoAAAAEAAAAAAAAAA=02418342:9487EB80334D0AEED1F1601B7671A42D0E9BD53115AD1B3697937919E532389F:3679:##700663867208/UMa9kZAhn61o2moMRrt"
  },
  "id": null,
  "trans_id": null,
  "transaction_type": "pay",
  "transaction": "Auth",
  "auth_code": null,
  "host_ref_num": null,
  "proc_return_code": null,
  "code": null,
  "status": "declined",
  "status_detail": null,
  "error_code": null,
  "error_message": null,
  "response": null,
  "all": null,
  "order_id": "2022052098BD"
}
```

**Comment by bugafix** [comment]
<img width="1060" alt="Screen Shot 2022-05-20 at 11 29 07" src="https://user-images.githubusercontent.com/105905453/169487955-302de710-8526-405e-a304-973ddccbd242.png">
Merhaba tekrardan
src/Gateways/EstPos.php

bu kısımda yer alan kod ile ilgili olabilir mi? mdErrorMsg Success olarak dönüyor. ama commentlediğim if in ilk bloğuna girdiği için null dönüyor.

Orayı üstteki gibi yaptığım zaman ödemeyi API'den tamamlıyor. Ama başka bir soruna yol açar mı emin değilim.

**Comment by nuryagdym** [comment]
Merhaba, tmm tesekkurler, siz boyle kullanmaya devam edin, bu hafta sonu sorunu cozerim. 
1. Bu arada hangi versiyonu kullaniyorsunuz?
2. Hangi banka?

Enson baktigimda `mdErrorMsg === "Authenticated"` olarak geliyordu, bankadan bankaya degisiyor olabilir belki.

**Comment by nuryagdym** [comment]
`mdErrorMsg === "Authenticated"` kontrolu  EstPos Gateway icinde 4-5 yerde yer aliyor, hepsini `mdErrorMsg === "Success"` olarak degistirmeniz gerekiyor

**Comment by nuryagdym** [comment]
duzeltmeleri yaptim.
`composer require mews/pos:dev-master` sekilde son halini cekip dener misiniz. Sorun yok ise release cikarim

**Comment by lansas** [comment]
bu sorun devam ediyor olabilir mi? Ben de QNB Test işlemi tamamlıyorum ama TEB in canlı ortamında yarıda kalıyor. v0.9.0 da

**Comment by nuryagdym** [comment]
Merhabalar, 
En son sorun cozulmustu. Kendiniz debugging yaparak sorunu tespit etmeyi dener misiniz. Olusan loglar size yarimci olabilir. Loglamayi etkinlestirmek icin
example/_main_config.php burdaki ornek koda bakabilirsiniz. 

Olmadi benim ce.nuryagdy@gmail.com epostama olusan loglari atarsaniz kontrol edebilir ben de. Ama bilgisayar basina 3-4 hafta sonra gecebilirim gibi gozukuyor

**Comment by lansas** [comment]
selamlar,

Umarım iyisinizdir, 3-4 hafta bir yazılımcı için uzun bir süre, sorun yok inşallah?

Evet paytenlerin canlı ortamı da tamam. Sorun yoktur. Cardtype i payten altyapısında mecbur kılıyordu. Sorun buydu. Hatayı kolay yakalayamıyorum; try catch lerdeki expectationları pek beceremedim sanırım. Şu ana kadar sıkıntı yok . Hatta recurring i de eklemişsiniz, konuşmuştuk daha önce, o da çalışıyor. Şimdi ilerideki tekrarlayan ödemeyi iptale bakacağım. Yoksa eğer,  geçen seferki gibi ek olarak yazacağım.


________________________________
Gönderen: nuryagdym ***@***.***>
Gönderildi: 17 Eylül 2022 Cumartesi 10:19
Kime: mewebstudio/pos ***@***.***>
Bilgi: gunes erdemi ***@***.***>; Comment ***@***.***>
Konu: Re: [mewebstudio/pos] EstPos - 3d ödeme tamamlama sorunu (Issue #76)


Merhabalar,
En son sorun cozulmustu. Kendiniz debugging yaparak sorunu tespit etmeyi dener misiniz. Olusan loglar size yarimci olabilir. Loglamayi etkinlestirmek icin
example/_main_config.php burdaki ornek koda bakabilirsiniz.

Olmadi benim ***@***.******@***.***> epostama olusan loglari atarsaniz kontrol edebilir ben de. Ama bilgisayar basina 3-4 hafta sonra gecebilirim gibi gozukuyor

**Comment by nuryagdym** [comment]
Selam @lansas , Payten hangi banka alt yapisi oluyor? 

PayFor - QNB icin kullaniliyor
EstPos - Akbank/TEB ... icin kullaniliyor

Bu konuyla ilgili her hangi bir degisiklik yaptiniz mi kodda?

**Comment by nuryagdym** [comment]
sorun yok sanirim, kapatiyorum issue'yu
