### ISSUE TITLE
Garanti pos  isSuccess hatalı sonuç veriyor

### ISSUE THREAD

**Issue by nevfel** [mewebstudio/pos#78]
Merhaba,

AbstractGateway deki isSuccess her durumda true oluyor.

GarantiPos.php dosyasına bu fonksiyonu ekleyince doğru sonuç veriyor
    /**
     * Is success
     *
     * @return bool
     */
    public function isSuccess(): bool
    {
        return isset($this->response->response) && 'Approved' === $this->response->response;
    }

**Comment by nuryagdym** [comment]
Merhabalar,
hangi kutuphabe versiyonu kullaniyorsunuz? composer ile require ettiyseniz composer.lock'dan bakarak yazar misiniz.
Ben test ettigimde, test ortamda sorunsuz calisiyor son versiyon. 
 
Mumkunse, hatali calitigi durumda, GarantiPos icersindeki `map3DPaymentData(($raw3DAuthResponseData, $rawPaymentResponseData)` verilen agrumanlarin degerlerini (hassas verileri silerek) benimle paylasir misiniz: nuryagdy@mustapayev.com

**Comment by nevfel** [comment]
Merhaba,

v.07.1 versiyonunu kullanıyorum 

Garanti pos response:Declined veya response:Approved şeklinde sonuç veriyor,  "status":"approved" her durumda true oluyor,
bu sorunu uygulamada farkettim 
Aşağıdaki hatalı response mesajında görebilirsiniz.

{"id":"","order_id":"22061505230002_8EEB","trans_id":"22061505230002_8EEB","auth_code":"","host_ref_num":"216607526514","response":"Declined","transaction_type":"pay","transaction":"sales","transaction_security":"Full 3D Secure","proc_return_code":"","code":"","md_status":"1","status":"approved","status_detail":null,"hash":"D9E8323BC9E19867E615F72C7C70D01ED44C7576","rand":"VU6XvBbJr1QeyBu6g4Jg","hash_params":"clientid:oid:authcode:procreturncode:response:mdstatus:cavv:eci:md:rnd:","hash_params_val":"3069129722061505230002_8EEB1jCm0m+u\/0hUfAREHBAMBcfN+pSo=02WnSgn5zoQegm4jJvQhQdor+UOT6z+QkIZ3R9y3vMs39AprOcGRdxi3TuHU9YaNYklgFLN+1t097EwC6+FXq7Hr2xiE98N2LcY9zaAbt1JdU3DHKyDh6mQH\/QZZhVYoq9gg9mmxlGbElKlnbduNx4zj0c0vEoq9mjVU6XvBbJr1QeyBu6g4Jg","masked_number":"405090***8481","amount":"10000","currency":"949","tx_status":"Y","eci":"02","cavv":"jCm0m+u\/0hUfAREHBAMBcfN+pSo=","xid":"RszfrwEYe\/8xb7rnrPuh6C9pZSQ=","error_code":null,"error_message":"\u0130\u015fleminizi ger\u00e7ekle\u015ftiremiyoruz.Tekrar deneyiniz","md_error_message":"Authenticated","campaign_url":null,"email":"test@test.com,"extra":null,"3d_all":{"xid":"RszfrwEYe\/8xb7rnrPuh6C9pZSQ=","mdstatus":"1","mderrormessage":"Authenticated","txnstatus":"Y","eci":"02","cavv":"jCm0m+u\/0hUfAREHBAMBcfN+pSo=","paressyntaxok":"true","paresverified":"true","version":"2.0","ireqcode":"","ireqdetail":"","vendorcode":"","cavvalgorithm":"3","md":"WnSgn5zoQegm4jJvQhQdor+UOT6z+QkIZ3R9y3vMs39AprOcGRdxi3TuHU9YaNYklgFLN+1t097EwC6+FXq7Hr2xiE98N2LcY9zaAbt1JdU3DHKyDh6mQH\/QZZhVYoq9gg9mmxlGbElKlnbduNx4zj0c0vEoq9mj","terminalid":"30691297","oid":"22061505230002_8EEB","authcode":"","response":"","errmsg":"","hostmsg":"","procreturncode":"","transid":"22061505230002_8EEB","hostrefnum":"","rnd":"VU6XvBbJr1QeyBu6g4Jg","hash":"yTSvdQilq\/l\/SSQpO4mBJxFCJIs=","hashparams":"clientid:oid:authcode:procreturncode:response:mdstatus:cavv:eci:md:rnd:","hashparamsval":"3069129722061505230002_8EEB1jCm0m+u\/0hUfAREHBAMBcfN+pSo=02WnSgn5zoQegm4jJvQhQdor+UOT6z+QkIZ3R9y3vMs39AprOcGRdxi3TuHU9YaNYklgFLN+1t097EwC6+FXq7Hr2xiE98N2LcY9zaAbt1JdU3DHKyDh6mQH\/QZZhVYoq9gg9mmxlGbElKlnbduNx4zj0c0vEoq9mjVU6XvBbJr1QeyBu6g4Jg","clientid":"30691297","MaskedPan":"405090***8481","apiversion":"v0.01","orderid":"22061505230002_8EEB","txninstallmentcount":"","terminaluserid":"PROVAUT","secure3dhash":"D9E8323BC9E19867E615F72C7C70D01ED44C7576","secure3dsecuritylevel":"3D","txncurrencycode":"949","customeremailaddress":"test@test.com,"errorurl":"http:\/\/kdportal.test\/gs2","terminalmerchantid":"7000679","mode":"TEST","terminalprovuserid":"PROVAUT","txnamount":"10000","successurl":"http:\/\/kdportal.test\/gs1","customeripaddress":"188.119.3.229","txntype":"sales"},"group_id":"002321","ret_ref_num":"216607526514","batch_num":"004651","reason_code":"58","all":{"Mode":"","Terminal":{"ProvUserID":"PROVAUT","UserID":"PROVAUT","ID":"30691297","MerchantID":"7000679"},"Customer":{"IPAddress":"188.119.3.229","EmailAddress":"test@test.com"},"Order":{"OrderID":"22061505230002_8EEB","GroupID":""},"Transaction":{"Response":{"Source":"HOST","Code":"58","ReasonCode":"58","Message":"Declined","ErrorMsg":"\u0130\u015fleminizi ger\u00e7ekle\u015ftiremiyoruz.Tekrar deneyiniz","SysErrMsg":"15-015-SON KULLANIM TARIHI GECMIS"},"RetrefNum":"216607526514","AuthCode":"","BatchNum":"004651","SequenceNum":"002321","ProvDate":"20220615 17:23:52","CardNumberMasked":"405090******8481","CardHolderName":"","CardType":"PREPAID","HashData":"CB1A8579B8E7F0F612E6339E99507B18F18BB0C0","HostMsgList":"","RewardInqResult":{"RewardList":"","ChequeList":""},"GarantiCardInd":"Y"}}}

**Comment by nuryagdym** [comment]
tesekkuler, kontrol edecegim, mesjanizi ne olur ne olmaz siliyorum

**Comment by nuryagdym** [comment]
master branch'i cekerek tekrar dener misiniz.
composer kullaniyorsaniz `composer require mews/pos:dev-master` ile cekmeniz gerekiyor.
Sorun yok ise yeni versiyon cikacam

**Comment by nevfel** [comment]
Tamam sorun kalmadı
Teşekkürler

**Comment by nuryagdym** [comment]
v0.7.2 versiyon olarak yayina aldim cozumu.
