### ISSUE TITLE
Yapikredi (Posnet) 148 MID,TID,IP HATALI: X.X.X.X hatasi

### ISSUE THREAD

**Issue by nuryagdym** [mewebstudio/pos#8]
Ben de bu hata shared hosting kullandigimdan oldu.
kurdugum website'nin IPsi Cpanel'de, ping yapildiginda ayni gosteriyor. 
Ama website shared hosting'de oldugundan posnet'e gorunen IP farkli. 
Sonuc olarak bu farkli IP'yi de sistemlerine eklettim sorun cozuldu.

**Comment by BoraKaraca** [comment]
Merhaba aynı sorunu bende yaşıyorum hata mesajındaki IP değerini yetki verdiler fakat yine aynı hatayı almaktayım. VPN kullandığım için şirket çıkış IP değeri var hata mesajındaki yazan IP değeri sizin yapmış olduğunuz işlemi öğrenebilir miyim çözüm olarak hangi IP değerini vermiş oldunuzda sorun çözüldü yardımcı olur musunuz ?

**Comment by nuryagdym** [comment]
Merhabalar, 
Bizde site shared server uzerinden service ediliyor. Biz website icin ayri bir static IP almamiza ragmen Yapikrediye sorgu yapildiginda, Yapikredi websiteye ozel aldigimiz static IP'yi degil, bulundugu shared server'in IP adresini gordu. 
Hatirladigim kadariyla, destek ekibe sorunu soyledigimde basarisiz olan sorguyu hangi IP'den geldigini kendileri soyledi ve o IP'ye izin verelim mi diye sordular. Bana soyledikleri IP'nin ne IP'si oldugunu hosting firmaya sordum. Onlar shared server'in IPsi oldugunu soylediler. 
Siz de desteginden hangi IPden basarisiz sorgu geldigini sorsaniz soylerler, o IP'ye de izin verdirebilirsiniz.

**Comment by BoraKaraca** [comment]
Geri dönüşünüz için teşekkür ederim. Ben şuan geliştirmeyi local bilgisayarımda yaptığım için sadece VPNe  bağlıyken çıkış IP veya local kendi IP oluyordu.Bu iki IP değerine yetki verdiler. Bu issue başlığındaki hata mesajındaki gibi X.X.X yazan yerde hata alan IP değerlerine yetki verilmesine rağmen sorun düzelmemişti. 
Cevabınıza istinaden şunu anladım hata mesajında belirtilen IP haricinde desteğin görebildiği farklı bir IP değerine yetki verilince hata düzelmiş oldu. Bende bu şekilde destek ekiplerine soracağım.
Bilgilendirme için çok teşekkürler

**Comment by nuryagdym** [comment]
Local'de hic deneme yapmadim, yapani da gormedim :).
SSL sertificate, static IP, domain name istiyorlar POS basvurusu yaparken.
Demek istedigim local'da calisma ihtimali var mi bilmiyorum.

**Comment by BoraKaraca** [comment]
Bilgilendirme için teşekkürler. 
Canlı ortam bilgileriyle dediğiniz gibi local'de olmayabilir. Fakat bu geliştirme için yeni bir test ortamı oluşturmuştu yapıkredi bu bilgiler ile geliştirmeyi yapıyordum. O hata mesajındaki IP değerine yetki verdikleri halde yine aynı hata mesajını alıyorum. Bakalım bu sorun çözüldüğü taktirde güncelleme yaparım :) 
İyi günler

**Comment by nuryagdym** [comment]
Bu sorunun diger bir sebebi ise yanlis ortam kullanmaniz.
Bankaya istek gonderirken de, ve gelen cevap islerken de dogru ortam tanimlamaniz gerekiyor.
Test bilgilerle deniyorsaniz:
`$pos->setTestMode(true);`
satiri eklemeniz gerekiyor.

Production ortamda ise bu `$pos->setTestMode(true);` satiri kaldirmaniz gerekiyor.

Kutuphane tanimlanan ortama gore bankanin ilgili URL'lerine istek gonderir. Canli ortam bilgileriyle test URL'lere istek gonderirseniz bu hatayi alirsiniz.
