### ISSUE TITLE
YKB 3D Ödeme geçersiz transaction type gönderiyor

### ISSUE THREAD

**Issue by erenilhan** [mewebstudio/pos#80]
Merhaba,
YKB ile ödeme yapmaya çalıştığım zaman transactionType hatası veriyor. **create3DEnrollmentCheckRequestData** fonksiyonunda tranType  ='pay' olarak dönmekte. Onu **Sale** olarak çevirdiğim zaman sorun olmadan ödemeyi tamamlıyor.

bu kısmı
`'tranType'       => $txType,` kısmını;

Şöyle değiştirerek
`'tranType'=> $this->txTypeMappings[$txType]`

çalıştırabiliyorum.

acaba atladığınız bir şey olabilir mi? ya da ben mi hata yapıyorum?

kodun nihai hali;

`
public function create3DEnrollmentCheckRequestData(AbstractPosAccount $account, $order, string $txType, AbstractCreditCard $card): array
    {
        if (null === $card->getHolderName() && isset($order->name)) {
            $card->setHolderName($order->name);
        }
        return [
            'mid'            => $account->getClientId(),
            'tid'            => $account->getTerminalId(),
            'oosRequestData' => [
                'posnetid'       => $account->getPosNetId(),
                'ccno'           => $card->getNumber(),

                'expDate'        => $card->getExpirationDate(self::CREDIT_CARD_EXP_DATE_FORMAT),
                'cvc'            => $card->getCvv(),
                'amount'         => self::amountFormat($order->amount),
                'currencyCode'   => $this->mapCurrency($order->currency),
                'installment'    => $this->mapInstallment($order->installment),
                'XID'            => self::formatOrderId($order->id),
                'cardHolderName' => $card->getHolderName(),
                'tranType'       => $this->txTypeMappings[$txType],
            ],
        ];
    }
`

**Comment by nuryagdym** [comment]
Tesekkurler, sorunu duzelttim, 0.7.3 versiyon olarak release ciktim

**Comment by erenilhan** [comment]
Çok teşekkürler 👍  iyi çalışmalar
