### ISSUE TITLE
Garanti POS TROY - undefined index secure3dhash problemi

### ISSUE THREAD

**Issue by mhunesi** [mewebstudio/pos#82]
Merhabalar. 

Bir TROY kart ile şöyle bir hata almışız. 

MD Status 1 gelmiş fakat **secure3dhash** alanı yok. Kodu okuduğumda **secure3dhash** alanı her zaman gelecekmiş gibi davranılmış.  Aslında **hash** alanında gelen data ile Hash kontrolü yapılabilirmiş. 

<img width="510" alt="image" src="https://user-images.githubusercontent.com/15876915/179456510-c188ee66-6c73-468e-a130-35089ec495e2.png">

<img width="510" alt="image" src="https://user-images.githubusercontent.com/15876915/179456565-20261eb3-a673-4194-9ab5-ee2919c38286.png">

https://github.com/mewebstudio/pos/blob/master/src/Gateways/GarantiPos.php#L342 
Buradaki 

`            'hash'                 => $raw3DAuthResponseData['secure3dhash'],`

alanını 

`            'hash'                 => $raw3DAuthResponseData['secure3dhash'] ?? $raw3DAuthResponseData['hash'],`

bu şekilde kullanmak doğru olur mu sizce? Teşekkürler. Emeğinize sağlık.

**Comment by nuryagdym** [comment]
Merhabalar,
Tesekkurler 1-2 gun icinde duzeltmeyi yapip release cikarim.

**Comment by nuryagdym** [comment]
sorun giderildi, 0.7.4 release olarak ciktim. 

Deneme sanisiniz varsa master branch'i de test edebilir misiniz.
`composer require dev-master` olarak cektiginizde master branch indirir. Master branch'te Garanti 3D Odemelerinde eksik olan 3d hash ekledim, test ortamda calisiyor ama canli ortamda test etme imkanim yok benim
