### ISSUE TITLE
Ödeme Sonucu Dönen Array Key Sorunu

### ISSUE THREAD

**Issue by mettleshade** [mewebstudio/pos#86]
Kuveyttür sanal pos -- codeigniter 4

Kullandığım Ödeme kodu:

```
$account = \Mews\Pos\Factory\AccountFactory::createKuveytPosAccount(
            'kuveytpos',
            '111',
            'eeee',
            '3333',
            '4444'
        );
        try {
            $pos = \Mews\Pos\Factory\PosFactory::createPosGateway($account);
            $pos->setTestMode(false);
        } catch (\Mews\Pos\Exceptions\BankNotFoundException | \Mews\Pos\Exceptions\BankClassNullException $e) {
            dd($e);
        }

        $order = [
            'id' => 'MP-15',
            'amount' => 0.1,
            'currency' => 'TRY', //TRY|USD|EUR, optional. default: TRY
            'installment' => 0, //0 ya da 1'den büyük değer, optional. default: 0
            'success_url' => 'https://www.modamping.com/testodeme',
            'fail_url' => 'https://******.com/testodeme',
            'ip' => '85.107.127.45', //EstPos, Garanti, KuveytPos, VakifBank
            'email' => 'mail@customer.com', // EstPos, Garanti, KuveytPos, VakifBank
            'name' => 'mehmet paçal', // EstPos, Garanti
            'user_id' => '1', // EstPos
            'rand' => md5(uniqid(time())), // EstPos, Garanti, PayFor, InterPos, VakifBank. Rastegele değer.
            'lang' => AbstractGateway::LANG_TR, //LANG_TR|LANG_EN. Kullanıcının yönlendirileceği banka gateway sayfasının ve gateway'den dönen mesajların dili.
        ];

        session()->set('order', $order);

        $card = \Mews\Pos\Factory\CreditCardFactory::create(
            $pos,
            '111111111',
            '11',
            '01',
            '2323',
            'Mehmet Paçal',
            AbstractCreditCard::CARD_TYPE_MASTERCARD
        );

        $pos->prepare($order, \Mews\Pos\Gateways\AbstractGateway::TX_PAY, $card);

        try {
            $formData = $pos->get3DFormData();
        } catch (\Throwable $e) {
            dd($e);
        }

        ?>

        <form method="post" action="<?= $formData['gateway']; ?>" class="redirect-form" role="form">
            <?php foreach ($formData['inputs'] as $key => $value) : ?>
                <input type="hidden" name="<?= $key; ?>" value="<?= $value; ?>">
            <?php endforeach; ?>
            <div class="text-center">Redirecting...</div>
            <hr>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-lg btn-block btn-success">Submit</button>
            </div>
        </form>

        <?php

```

Sonuç sayfası : 

```
$account = \Mews\Pos\Factory\AccountFactory::createKuveytPosAccount(
            'kuveytpos',
            '111',
            'eeee',
            '3333',
            '4444'
        );

try {
    $pos = \Mews\Pos\Factory\PosFactory::createPosGateway($account);
    $pos->setTestMode(true);
} catch (\Mews\Pos\Exceptions\BankNotFoundException | \Mews\Pos\Exceptions\BankClassNullException $e) {
    dd($e);
}

echo "<pre>";

$order = [
    'id' => 'MP-12',
    'amount' => 0.1,
    'currency' => 'TRY', //TRY|USD|EUR, optional. default: TRY
    'installment' => 0, //0 ya da 1'den büyük değer, optional. default: 0
    'success_url' => '****.com/testodeme',
    'fail_url' => '****.com/testodeme',
    'ip' => '*****', //EstPos, Garanti, KuveytPos, VakifBank
    'email' => 'mail@customer.com', // EstPos, Garanti, KuveytPos, VakifBank
    'name' => 'John Doe', // EstPos, Garanti
    'user_id' => '1', // EstPos
    'rand' => '7893febf7a15ab***461363f6528', // EstPos, Garanti, PayFor, InterPos, VakifBank. Rastegele değer.
    'lang' => 'tr' //LANG_TR|LANG_EN. Kullanıcının yönlendirileceği banka gateway sayfasının ve gateway'den dönen mesajların dili.
];

//$order = session()->get('order');

$pos->prepare($order, \Mews\Pos\Gateways\AbstractGateway::TX_PAY);

        $card = \Mews\Pos\Factory\CreditCardFactory::create(
            $pos,
            '111111111',
            '11',
            '01',
            '2323',
            'Mehmet Paçal',
            AbstractCreditCard::CARD_TYPE_MASTERCARD
        );

$pos->payment($card);

$pos->isSuccess();

print_r($pos->getResponse());
```

Dönen hata ekranı :

https://prnt.sc/_bfQzr66d2jA

**Comment by nuryagdym** [comment]
Merhabalalar, 
tekrar deneneyip, KuveytPosRequestDataMapper.php dosyada 83. satira bu kodu: `dd($responseData); ` ekleyerek ciktiyi paylasir misin. 
Bu bilgileri icinde hassas veri varsa, onlari kaldirip oylep paylasir misin.

Kuveytgateway'i test etme imkanimiz olmadi, yardimci olursaniz, tamamlariz Kuveyti de

**Comment by mettleshade** [comment]
Görseldeki hatayı geçemiyor o keyi yorum satırına çektiğim zaman 

`'DisplayAmount'                => $responseData['VPosMessage']['DisplayAmount'],`

bu seferde bu keyi bulamıyor

**Comment by mettleshade** [comment]
> Merhabalalar, tekrar deneneyip, KuveytPosRequestDataMapper.php dosyada 83. satira bu kodu: `dd($responseData); ` ekleyerek ciktiyi paylasir misin. Bu bilgileri icinde hassas veri varsa, onlari kaldirip oylep paylasir misin.
> 
> Kuveytgateway'i test etme imkanimiz olmadi, yardimci olursaniz, tamamlariz Kuveyti de

**Comment by nuryagdym** [comment]
evet, ama yukarda dedigim response lazim bize, ona gore guncelleriz kodu

**Comment by mettleshade** [comment]
> evet, ama yukarda dedigim response lazim bize, ona gore guncelleriz kodu

verdiğiniz kodu alta koymuştum o yüzden geçememiş şuanda düzenledim boş sayfa açtı herhangi bir veri yazmadı

**Comment by nuryagdym** [comment]
pardon dd yerine print_r olacak yani `print_r($responseData);`

**Comment by mettleshade** [comment]
> pardon dd yerine print_r olacak yani `print_r($responseData);`

aynı key sorununa takılıyor bulunmayan keyleri kapattım bu seferde alttaki keyi bulamadı

https://prnt.sc/vJsavTFGOCxC

**Comment by nuryagdym** [comment]
kisacasi bunu cozebilmem icin gelen  banktan gelen response'un icerigi lazim bana. 
`print_r($responseData); die();` dener misin.die yapilmazsa Codeigniter basilan degeri temizliyor anladigim.

Bulunmayan keyleri kapatmaman gerekiyor cunku onlar bankaya gonderilmesi gereken degerler. O keyler ulasilamiyorsa belki baska turlu erismemiz gerekiyor o bilgilere.

**Comment by mettleshade** [comment]
> kisacasi bunu cozebilmem icin gelen banktan gelen response'un icerigi lazim bana. `print_r($responseData); die();` dener misin.die yapilmazsa Codeigniter basilan degeri temizliyor anladigim.
> 
> Bulunmayan keyleri kapatmaman gerekiyor cunku onlar bankaya gonderilmesi gereken degerler. O keyler ulasilamiyorsa belki baska turlu erismemiz gerekiyor o bilgilere.

evet alabildim değerleri

`Array
(
    [@xmlns:xsi] => http://www.w3.org/2001/XMLSchema-instance
    [@xmlns:xsd] => http://www.w3.org/2001/XMLSchema
    [VPosMessage] => Array
        (
            [OrderId] => 86297530
            [OkUrl] => https://www.modamping.com/testodeme
            [FailUrl] => https://www.modamping.com/testodeme
            [MerchantId] => ****
            [SubMerchantId] => 0
            [CustomerId] => *****
            [UserName] => fapapi
            [HashPassword] => Hiorgg24rNeRdHUvMCg//mOJn4U=
            [CardNumber] => ***********1609
            [BatchID] => 1576
            [InstallmentCount] => 0
            [Amount] => 10
            [CancelAmount] => 0
            [MerchantOrderId] => MP-15
            [FECAmount] => 0
            [CurrencyCode] => 949
            [QeryId] => 0
            [DebtId] => 0
            [SurchargeAmount] => 0
            [SGKDebtAmount] => 0
            [TransactionSecurity] => 3
            [DeferringCount] => Array
                (
                    [@xsi:nil] => true
                    [#] => 
                )

            [InstallmentMaturityCommisionFlag] => 0
            [PaymentId] => Array
                (
                    [@xsi:nil] => true
                    [#] => 
                )

            [OrderPOSTransactionId] => Array
                (
                    [@xsi:nil] => true
                    [#] => 
                )

            [TranDate] => Array
                (
                    [@xsi:nil] => true
                    [#] => 
                )

            [TransactionUserId] => Array
                (
                    [@xsi:nil] => true
                    [#] => 
                )

        )

    [IsEnrolled] => true
    [IsVirtual] => false
    [ResponseCode] => 00
    [ResponseMessage] => Kart doğrulandı.
    [OrderId] => 86297530
    [TransactionTime] => 0001-01-01T00:00:00
    [MerchantOrderId] => MP-15
    [HashData] => ucejRvHjCbuPXagyoweFLnJfSJg=
    [MD] => QHb9KI5Oss/KFth9Mel2h18tXLR825kVGK5s+0dHQPMg2ffJ0mKaTOGmrPIPlv64
    [BusinessKey] => 202208069555000000000140359
)`

**Comment by nuryagdym** [comment]
tesekkurler, inceleyecegim bunu, guvenlik amacli sildim response'u

**Comment by nuryagdym** [comment]
`KuveytPosRequestDataMapper::create3DPaymentRequestData()` methodu su sekilde guncelleyip dener misin, ondan sonra undefined key hatasi vermemesi gerekiyor bu metod'da:
```php
public function create3DPaymentRequestData(AbstractPosAccount $account, $order, string $txType, array $responseData): array
    {
        $hash = $this->create3DHash($account, $order, $txType, true);

        return $this->getRequestAccountData($account) + [
            'APIVersion'                   => self::API_VERSION,
            'HashData'                     => $hash,
            'CustomerIPAddress'            => $order->ip,
            'KuveytTurkVPosAdditionalData' => [
                'AdditionalData' => [
                    'Key'  => 'MD',
                    'Data' => $responseData['MD'],
                ],
            ],
            'TransactionType'              => $this->mapTxType($txType),
            'InstallmentCount'             => $responseData['VPosMessage']['InstallmentCount'],
            'Amount'                       => $responseData['VPosMessage']['Amount'],
            'DisplayAmount'                => self::amountFormat($responseData['VPosMessage']['Amount']),
            'CurrencyCode'                 => $responseData['VPosMessage']['CurrencyCode'],
            'MerchantOrderId'              => $responseData['VPosMessage']['MerchantOrderId'],
            'TransactionSecurity'          => $responseData['VPosMessage']['TransactionSecurity'],
        ];
    }
```
Ondan sonra, KuveytPos.php'de response da paylasir misin, 493. satira bu kodu eklemen gerekir: `print_r($raw3DAuthResponseData); die();` ciktiyi direk epostama gondersen iyi olur nuryagdy@mustapayev.com

**Comment by mettleshade** [comment]
> `KuveytPosRequestDataMapper::create3DPaymentRequestData()` methodu su sekilde guncelleyip dener misin, ondan sonra undefined key hatasi vermemesi gerekiyor bu metod'da:
> 
> ```
> public function create3DPaymentRequestData(AbstractPosAccount $account, $order, string $txType, array $responseData): array
>     {
>         $hash = $this->create3DHash($account, $order, $txType, true);
> 
>         return $this->getRequestAccountData($account) + [
>             'APIVersion'                   => self::API_VERSION,
>             'HashData'                     => $hash,
>             'CustomerIPAddress'            => $order->ip,
>             'KuveytTurkVPosAdditionalData' => [
>                 'AdditionalData' => [
>                     'Key'  => 'MD',
>                     'Data' => $responseData['MD'],
>                 ],
>             ],
>             'TransactionType'              => $this->mapTxType($txType),
>             'InstallmentCount'             => $responseData['VPosMessage']['InstallmentCount'],
>             'Amount'                       => $responseData['VPosMessage']['Amount'],
>             'DisplayAmount'                => self::amountFormat($responseData['VPosMessage']['Amount']),
>             'CurrencyCode'                 => $responseData['VPosMessage']['CurrencyCode'],
>             'MerchantOrderId'              => $responseData['VPosMessage']['MerchantOrderId'],
>             'TransactionSecurity'          => $responseData['VPosMessage']['TransactionSecurity'],
>         ];
>     }
> ```
> 
> Ondan sonra, KuveytPos.php'de response da paylasir misin, 493. satira bu kodu eklemen gerekir: `print_r($raw3DAuthResponseData); die();` ciktiyi direk epostama gondersen iyi olur [nuryagdy@mustapayev.com](mailto:nuryagdy@mustapayev.com)

Merhaba eposta gönderdim.

**Comment by nuryagdym** [comment]
Merhabalar, gelmedi nedense buna gondermeyi dener misin ce.nuryagdy@gmail.com

**Comment by mettleshade** [comment]
> Merhabalar, gelmedi nedense buna gondermeyi dener misin [ce.nuryagdy@gmail.com](mailto:ce.nuryagdy@gmail.com)

Tekrar gönderilmiştir.

**Comment by nuryagdym** [comment]
Geldi, ama bu gonderidigin response `print_r($raw3DAuthResponseData); die();` ile KuvetPos.php icinden basilan response mu?

**Comment by nuryagdym** [comment]
KuveytPost::tDPayResponseCommon() metodda bu satiri:
```php
$default['hash'] = $raw3DAuthResponseData['VPosMessage']['HashData'];
```
bu sekilde:
```php
$default['hash'] = $raw3DAuthResponseData['HashData'];`
```
degistirip tekrar dener misin

**Comment by nuryagdym** [comment]
Bir de elinde gunce KuveytPos dokumani varsa paylasir misin, mumkunse test ortam bilgileriyle. direk ce.nuryagdy@gmail.com epostama gonderebilirsin

**Comment by mettleshade** [comment]
> Bir de elinde gunce KuveytPos dokumani varsa paylasir misin, mumkunse test ortam bilgileriyle. direk [ce.nuryagdy@gmail.com](mailto:ce.nuryagdy@gmail.com) epostama gonderebilirsin

dediklerini yapıp detaylı bir mail gönderdim, test verileri ve güncel döküman almadım kuveytten direk canlıda test etmeye başladım.

**Comment by nuryagdym** [comment]
Sorunlar halledildi.
Not olarak burada alinan Kuveyt pos hata mesajlari ve aciklamalarini birakiyorum:

**MetaDataNotFound - Ödeme detayı bulunamadı.**
Hatasinin sebebi hatali environment URL'e istek gonderilmesi, yani production credentials ile test ortamina istek gonderilmesi.

**HashDataError - Şifrelenen veriler (Hashdata) uyuşmamaktadır.**
Bankadan donusde, provizyon tamamlamak icin bankaya gonderilen istege karsilik gelen hata mesaji.
Hatanin sebeplerinden biri response islediginiz sayfada Pos Gateway'e dogru order bilgilerinin verilmemesi.
