### ISSUE TITLE
Payten (estpos, netspay) 3D hash algoritma değişmesi

### ISSUE THREAD

**Issue by zeydduran** [mewebstudio/pos#89]
Selamlar, Payten 3d şifreleme de versiyon 3 geçişi yaptı eski şifreleme yöntemlerinde fraud atağı aldıklarını söylediler. versiyon 3e geçiş yapmayan sanal posları kapatacaklarını hatta belirlenen süre içinde geçiş yapmayanları BTK şikayet edip kullandığı diğer sanal posların kapanmasına da yol açılabileceğini ilettiler.
Elde ettiğim dokümanlarını paylaştım
[Hashv3_Sample_Codes.zip](https://github.com/mewebstudio/pos/files/9596980/Hashv3_Sample_Codes.zip)

**Comment by canerd7u** [comment]
+1

**Comment by nuryagdym** [comment]
Merhabalar, kod farklarina baktim, sadece hash algoritmasi degismemis. Yeni degiskenler eklenmis, var olanlarin key name'leri degismis. Bu degisiklikleri yapmam icin PDF documantasyon da olursa iyi olur.

**Comment by zeydduran** [comment]
Selamlar, saçma bir şekilde yeni dokümantasyon yayımlamamışlar. Elimde güncel olarak ekte paylaştığım dosyalar var

**Comment by nuryagdym** [comment]
Tmm tesekkurler, bu hafta icinde halletmeye calisirim.

Bu degisiklik sorunsuz calisiyor degil mi?
API URL'ler vs degistirmeye gerek yok degil mi?

**Comment by zeydduran** [comment]
Hayır yok

**Comment by canerd7u** [comment]
[Nestpay_Entegrasyon_Dokumani_3D (4).pdf](https://github.com/mewebstudio/pos/files/9746000/Nestpay_Entegrasyon_Dokumani_3D.4.pdf)
[Nestpay   bank SanalPOS Test_Bilgileri (2).pdf](https://github.com/mewebstudio/pos/files/9
[Nestpay_Entegrasyon_Dokumani_3D_Pay (3).pdf](https://github.com/mewebstudio/pos/files/9746002/Nestpay_Entegrasyon_Dokumani_3D_Pay.3.pdf)
746001/Nestpay.bank.SanalPOS.Test_Bilgileri.2.pdf)
[Nestpay_Entegrasyon_Dokumani_3D_PayHosting (1).pdf
[Nestpay_Entegrasyon_Dokumani_API (2).pdf](https://github.com/mewebstudio/pos/files/9746004/Nestpay_Entegrasyon_Dokumani_API.2.pdf)
](https://github.com/mewebstudio/pos/files/9746003/Nestpay_Entegrasyon_Dokumani_3D_PayHosting.1.pdf)

Merhaba gerekli dökümanlar bunlar  sanırım.

**Comment by nuryagdym** [comment]
Merhabalar, 
@zeydduran Mumkunse eposta test ortam bilgilerini atabilir misiniz. ce.nuryagdy@gmail.com
test kart dahil.
Kutuphanede var olan test ortamlar nedense 3D odeme calismiyor artik.

@canerd7u dokumanlar icin tesekkurler ama bunlar yeni hash algoritmayi icermiyor

**Comment by zeydduran** [comment]
Selamlar @nuryagdym ,
Faydalandığım dökümanları paylaştım. Test konusunda ziraat ekteki dökümanlar haricindeki kart bilgilerinden  hata dönüyor bilginize.
[Hash_Versiyon_3_Dökümantasyon.pdf](https://github.com/mewebstudio/pos/files/9792999/Hash_Versiyon_3_Dokumantasyon.pdf)
[Nestpay_Entegrasyon_Dokumani_3D.pdf](https://github.com/mewebstudio/pos/files/9793000/Nestpay_Entegrasyon_Dokumani_3D.pdf)
[Nestpay_ZiraatBankasi_Test_Bilgileri (2).pdf](https://github.com/mewebstudio/pos/files/9793001/Nestpay_ZiraatBankasi_Test_Bilgileri.2.pdf)

**Comment by berkansahin** [comment]
@nuryagdym Merhaba hash versiyon 3 ile ilgili bir email geldi isbankası tarafından bu güncelleme asseco ile birlikte bunuda içeriyor mu acaba ?

**Comment by nuryagdym** [comment]
Merhabalar, 3 hafta once denedigimde isbank v3 algoritmayi desteklemiyordu.

EstPos yerine EstPosV3 deneyebilirsiniz,

Calisirsa haber verirseniz sevinirim

**Comment by berkansahin** [comment]
![Screenshot 2023-07-09 at 14 19 56](https://github.com/mewebstudio/pos/assets/4026967/9ce58cc9-f21e-4d1f-9503-a77cc6a9feca)
Son gelen email bu şekilde EstPosV3 kısmını nasıl deneyebilirim acaba ? @nuryagdym

**Comment by nuryagdym** [comment]
Merhabalar,
config/pos.php'de yer alan su anki config su sekilde:
https://github.com/mewebstudio/pos/blob/master/config/pos.php#L79C1-L94C11
```
        'isbank'    => [
            'name'  => 'İşbank T.A.S.',
            'class' => Mews\Pos\Gateways\EstPos::class,
            'urls'  => [
                'production'    => 'https://sanalpos.isbank.com.tr/fim/api',
                'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/api',
                'gateway'       => [
                    'production'    => 'https://sanalpos.isbank.com.tr/fim/est3Dgate',
                    'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
                ],
                'gateway_3d_host'       => [
                    'production'    => 'https://sanalpos.isbank.com.tr/fim/est3Dgate',
                    'test'          => 'https://entegrasyon.asseco-see.com.tr/fim/est3Dgate',
                ],
            ],
        ],
```
bu satiri:
```
 'class' => Mews\Pos\Gateways\EstPos::class,
```

bu sekilde desgistirilecek
```
 'class' => Mews\Pos\Gateways\EstV3Pos::class,
```

Not:
`config/pos.php` - sadece ornek olarak tanimlanmistir, direk bu dosyayi kullanmayin, kendinize ayri bir tane olusturun, ve ihtiyaciniz oldugu ayarlari oraya tanimlayiniz

**Comment by berkansahin** [comment]
@nuryagdym çok teşekkür ederim bu şekilde çözdüm.
