### ISSUE TITLE
"taksit tablosu icin gecersiz deger" hatası

### ISSUE THREAD

**Issue by yorulmazsinan** [mewebstudio/pos#92]
Akbank veya diğer poslar farketmeksizin bu hatayı alıyorum.

```
$installments = [
	    0  => 'Peşin',
	    2  => '2 Taksit',
	    6  => '6 Taksit',
	    12 => '12 Taksit',
	];
```

**Comment by nuryagdym** [comment]
Merhabalar, acil ise 2 hafta sonra soruna bakabilirim. Acil ise v0.8.2 ve onceki versiyonlari dener misiniz

**Comment by yorulmazsinan** [comment]
> 

0.8.2 versiyonunun farkı nedir bundan? Diğer özelliklerde sıkıntı çıkabilir mi?

**Comment by yorulmazsinan** [comment]
Durumun bu değişkenle hiçbir alakası yokmuş, tamamen bankadan kaynaklı bir hata imiş.
