### ISSUE TITLE
YKB - ödeme sonrası doğrulama hatası 

### ISSUE THREAD

**Issue by erenilhan** [mewebstudio/pos#93]
Merhaba,
YKB 3D ödeme yapılırken sms doğrulama da girdikten sonra callbackte decrypt false dönüyor. 
o false dönünce `Attempt to read property "approved" on null`hatası veriyor.  - **Gateways/PosNet.php. 383**

kodu debug ettiğim zaman decrypt yaparken false döndüğünü gördüm. 

`        return openssl_decrypt($encryptedData, $this->algo, $this->detKey($key), OPENSSL_RAW_DATA, $iv);`

bu konu hakkında ne yapabilirim?

**Comment by nuryagdym** [comment]
Merhaba,
Kutuphanenin hangi versiyonunu kullaniyorsunuz?
```
$decryptedString = $this->crypt->decrypt($data['MerchantPacket'], $this-Key(>account->getStoreKey());
```
kodda bu sekilde decode yapiyor. Burda `$this-Key(>account->getStoreKey()` degeri dogru store key degeri dondurup dondurmedigini kontrol eder misiniz. Test/Prod ortama gore bu deger farkli olur, ortam bilgiyi de dikkate alarak kontrol eder misiniz.

**Comment by erenilhan** [comment]
Merhaba,

çok ilginçtir ama şu an çalışıyor ve hiçbir şey yapmadım. Sadece bankayla yazışmalarımda amount değeri x*100 olarak gönderdiğimiz (olması gereken) ama dönerken X olarak döndüğünü ilettiler. Bunu da manuel olarak 100 ile çarpmıştım. fakat şu an ona bile gerek olmadan çalıştı.  (0.90)
Sadece iptal ederken şöyle bi uyarı dönüyor. Bununla ilgili bankaya destek kaydı oluşturdum.
 Bankadan dönen mesaj: ORJINAL ISLEM BULUNAMADI-0123

İlginiz için teşekkür ederim.

**Comment by nuryagdym** [comment]
Anladim, 100 carpma islemi kutuphane istegi gonderirken otomatik yapiyor.
Iptal/Durum Sorgulama/Refund islemlerinde bazi gatewayler sizin taraftaki siparis ID'yi gondermez. Kendi tarafinda olusturulan order id degerini isterler. 

YKB durumu ise biraz farkli.
ornegin sizin `orderId=1234`
Bu deger istek gonderirilerken kutuphane 20 haneli string'e donusturur, yani: `00000000000000001234`.
Ondan sonra iptal/status/refund islemi icin ise (3D secure model icin) order id **TDSC** string eklenerek 24 haneli order id'ye donusturulur: `TDSC00000000000000001234`.
Durumu incelemek icin 
`Mews\Pos\DataMapper\PosNetRequestDataMapper::formatOrderId();` ve `Mews\Pos\DataMapper\PosNetRequestDataMapper::mapOrderIdToPrefixedOrderId();` methodlara bakabilirisniz.

Sizin YKB Sanal pos hesabi 3D secure hesap mi?

**Comment by erenilhan** [comment]
dediklerinizi inceleyip tekrar deneme yapacağım. 
- evet 3d.

**Comment by semihyilmaz** [comment]
Bu sorunu çözebildiniz mi?
Bence dönen data yı map ederken sorun var gibi.

**Comment by nuryagdym** [comment]
simdilik KuveytPos.php'daki metodu su sekilde degistirip kullanabilirsiniz:
```php
    private function builtInputsFromHTMLDoc(DOMNodeList $inputNodes): array
    {
        $inputs = [];
        foreach ($inputNodes as $el) {
            $key = null;
            $value = null;
            // for each input element select name and value attribute values
            for ($i = 0; $i < $el->attributes->length; ++$i) {
                if ('name' === $el->attributes->item($i)->name) {
                    $key = $el->attributes->item($i)->value;
                }
                if ('value' === $el->attributes->item($i)->name) {
                    $value = $el->attributes->item($i)->value;
                }
            }
            if ($key && null !== $value && !in_array($key, ['submit', 'submitBtn'])) {
                $inputs[$key] = $value;
            }
        }

        return $inputs;
    }
```

**Comment by nuryagdym** [comment]
@semihyilmaz kutuphanenin son versiyonunu kullanmayi denediniz mi?

**Comment by semihyilmaz** [comment]
Evet son versiyon kullanıyorum. Php 8.1 mcrpyt'de yüklü.  Dönen datalarda approve'da var.
Ama sorunu yakalayamadım. 3d Hash'te doğru çözülüyor.
Ama $this->data->approved verisi yok. returnProcCode ve returnProcResponse  collection a gidiyor çatlatıyor.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/6323272/209811698-f0eba3fb-c0ba-4390-8490-8185b8772bfc.png">

**Comment by nuryagdym** [comment]
isterseniz ozelden goruselim, google meet olabilir, ce.nuryagdy@gmail.com

**Comment by nuryagdym** [comment]
sorun tespit edildi, bu hafta yeni release ile sorun giderilecek

**Comment by nuryagdym** [comment]
@semihyilmaz musait oldugunda 0.10.3 versiyonu indirip kontrol eder misin.
