### ISSUE TITLE
garanti pos iade işlem tutar

### ISSUE THREAD

**Issue by sekizlipenguen** [mewebstudio/pos#96]
Selamlar,

Garanti pos için ödeme işleminden sonra iade işleminde aşağıdaki gibi hata alıyor baktım benim gönderdiğim amount değerini yok sayıp 100 gösteriyor devamlı bunu nasıl çözebiliriz sence?
<img width="451" alt="Screen Shot 2022-10-19 at 11 13 17" src="https://user-images.githubusercontent.com/36849861/196634956-f0c62a23-6a72-4d88-a8c5-b27e3c985d09.png">

<img width="274" alt="Screen Shot 2022-10-19 at 11 13 36" src="https://user-images.githubusercontent.com/36849861/196635026-4a4a8838-0db6-47e0-ae6e-a0dca035c7f3.png">
<img width="172" alt="Screen Shot 2022-10-19 at 11 15 11" src="https://user-images.githubusercontent.com/36849861/196635422-98d4cf7a-ae03-4201-866f-cdc5a1b4fa39.png">

**Comment by sekizlipenguen** [comment]
Selam tekrar sorunu buldum ancak buna güncelleme çıkman gerekiyor.

garanti pos için amount değerini sabit giriş yapmışsın.

<img width="653" alt="Screen Shot 2022-10-19 at 11 23 32" src="https://user-images.githubusercontent.com/36849861/196637747-fe4b6c3d-de77-4197-bd4c-b0357381a0c5.png">


garantipos.php içinde 1004 satırı değiştirmen gerekiyor gibi :/

 'amount'      => self::amountFormat($order['amount']), şekilde olmalı.

**Comment by nuryagdym** [comment]
Merhabalar, 
iptal islemi iceren guncel garanti pos dokumani paylasir misiniz. Benim hatirladigim cancel icin  Garanti pos amount 100 gonderilmesini istiyor.

Ayrica cancel islemi gun kapanpadan yani aksam 5'e kadar yapilmasi gerekiyor diye biliyorum, bu sure gectikten sonra cancel yerine iade islemi yapilmasi gerekiyor. Iade islemlerde amount deger dynamic.

**Comment by sekizlipenguen** [comment]
Selamlar,

elimde döküman yok ancak cancel ile refurnd aynı kullanılmış bu yüzden return dinamik olmuyordu. 
Hem cancel hemde refund için amount değeri bu şekilde olunca çalışıyor. cancel işlemlerinde prepare fonksiyonuna amount tanımsız yolluyorum ve sorunsuz çalışıyor.

<img width="560" alt="Screen Shot 2022-10-19 at 12 32 18" src="https://user-images.githubusercontent.com/36849861/196654153-721bc2d9-10b1-4961-9b34-d709d0d26f90.png">

**Comment by nuryagdym** [comment]
hmm, o zamat refund duzeltilmesi gerekiyor, ama cancel 100 gondermeye devam etmesi gerekiyor diye biliyorum. sen hangi islemi yapmaya calisiyorsun, refund mu? cancel mi?

**Comment by nuryagdym** [comment]
anladigim kadariyla refund islemi yapmaya calisiyorsun, 
prepareRefundOrder duzeltilmesi gerekiyor. amount dinamik olacak sekilde.
cancel ise oldugu gibi 100 gondermeye devam etmesi gerekiyor

**Comment by sekizlipenguen** [comment]
aynen iade işlemi yapmaya çalışıyorum iade işlemi ile iptal işleminde aynı fonksiyonu kullanmışsın bu da sorun çıkarıyor. şu şekilde ufak bir güncelleme ile yine çözüm sağlanıyor.

$order['amount'] ?? 1 eklemek yeterli oluyor.

NOT: iade ve iptal işlemi gerçek garanti pos bilgileri ile denenmiş ve başarılı olunmuştur.

0.9.0 versiyonu için denendi
```

    protected function prepareCancelOrder(array $order)
    {
        return (object)[
            'id' => $order['id'],
            'amount' => $order['amount'] ?? 1, //sabit deger gonderilmesi gerekiyor
            'currency' => $order['currency'] ?? 'TRY',
            'ref_ret_num' => $order['ref_ret_num'],
            'ip' => $order['ip'] ?? '',
            'email' => $order['email'] ?? '',
            'installment' => 0,
        ];
    }
```

**Comment by sekizlipenguen** [comment]
yakında seni finansbank içinde rahatsız edeceğim :) tüm posları neredeyse kullandığımız için güzel bi test yöntemi sağlıyoruz :) Bu arada gerçekten emeklerin için teşekkür ederim çok iyi iş çıkarıyorsun.

**Comment by sekizlipenguen** [comment]
ek olarak bunu ne zaman yayına alabilirsin? dev-master üzerinden mi erişmeliyim?

**Comment by nuryagdym** [comment]
issue #91 ile ilgili acan kisiyle gorusup son  kalan kismi yapmam gerekiyor, onunla beraber yayinlayayim diyorum. en gec bu hafta hallolur

**Comment by sekizlipenguen** [comment]
Bu konuda yardımcı olabileceğim bir şey olursa belirtebilirsin? Localde bankalar ile test yapabilirim. iş bankası, garanti, ak bank şu an aktif olanlarımız yakında finansbank bakacağım
