### ISSUE TITLE
enpara.com entegrasyonu

### ISSUE THREAD

**Issue by sekizlipenguen** [mewebstudio/pos#98]
Selamlar,

ben tam emin olmadığım için buradan soru açmak zorunda kaldım. Enpara.com pos finansbank için yaptığın "Finansbank PayFor" kullanıyor acaba bilgin var mıdır?

**Comment by nuryagdym** [comment]
Selam,
Benim bir bilgim yok bu konuda, Enpara'nin bir Sanal Pos hizmeti oldugunu da dusunmuyorum.

**Comment by sekizlipenguen** [comment]
Bir müşterimiz almış galiba sitesinde bende bulamadım ancak api bilgilerini iletiyor bir sonuç elde edersem buradan bilgilendireceğim, teşekkürler

**Comment by sekizlipenguen** [comment]
tamamadır kontrol ettirdim. içerde bi anlaşma yapıyorlar ama finansbank kullanıyorlar.
